#!/usr/bin/env bash
#
# Kin — one-command VPS installer (fresh Ubuntu/Debian → running stack).
#
# Path A (public-IP VPS + Traefik + Let's Encrypt). For the Mac/OrbStack tunnel path
# use install-mac.sh (separate). This brings up docker-compose.prod.yml: installs Docker
# if missing, generates secrets, prompts ONLY for what can't be auto-generated (LLM gateway
# key, domain, Cloudflare token), pulls the prebuilt multi-arch images from GHCR, starts the
# stack, and waits until it serves.
#
# Usage (run from the cloned kin repo root):
#   sudo bash scripts/install-vps.sh           # interactive
#   sudo bash scripts/install-vps.sh --yes     # non-interactive (required values from env)
#
# Non-interactive required env: APP_HOSTNAME ANTHROPIC_AUTH_TOKEN ANTHROPIC_BASE_URL
#   ANTHROPIC_MODEL ACME_EMAIL CF_DNS_API_TOKEN   (datastore/auth secrets are auto-generated)
#
set -euo pipefail

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env"
PROJECT="${KIN_PROJECT:-kin}"

NONINTERACTIVE=0
case "${1:-}" in --yes | --non-interactive) NONINTERACTIVE=1 ;; esac

c_g=$'\033[1;32m'; c_y=$'\033[1;33m'; c_r=$'\033[1;31m'; c_0=$'\033[0m'
log()  { printf '%s[kin]%s %s\n' "$c_g" "$c_0" "$*"; }
warn() { printf '%s[kin]%s %s\n' "$c_y" "$c_0" "$*" >&2; }
die()  { printf '%s[kin ERROR]%s %s\n' "$c_r" "$c_0" "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
rand() { openssl rand -hex 32; }

ask() { # ask VAR "prompt" [default]   — env value > interactive prompt > default
  local var="$1" q="$2" def="${3:-}" cur="" ans=""
  eval "cur=\${$var:-}"
  if [ -n "$cur" ]; then printf '%s' "$cur"; return; fi
  if [ "$NONINTERACTIVE" -eq 1 ]; then
    [ -n "$def" ] && { printf '%s' "$def"; return; }
    die "missing required \$$var (non-interactive mode)"
  fi
  read -r -p "  $q${def:+ [$def]}: " ans </dev/tty || true
  printf '%s' "${ans:-$def}"
}

# --- 0. preflight -----------------------------------------------------------
[ -f "$COMPOSE_FILE" ] || die "run this from the cloned kin repo root (no $COMPOSE_FILE here)."
have openssl || die "openssl is required."
have curl || die "curl is required."
if [ "$(id -u)" -ne 0 ]; then
  have sudo || die "run as root, or install sudo."
  SUDO="sudo"
else
  SUDO=""
fi

# --- 1. Docker --------------------------------------------------------------
if ! have docker; then
  log "Docker not found — installing via get.docker.com…"
  curl -fsSL https://get.docker.com | $SUDO sh
fi
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing (apt install docker-compose-plugin)."
log "Docker $(docker --version | awk '{print $3}' | tr -d ,) ready."

mem_gb=$(awk '/MemTotal/{printf "%d", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo 0)
[ "$mem_gb" -lt 8 ] && warn "Host has ~${mem_gb}GB RAM. Kin wants ~8GB to run; consider scripts/add-swap.sh."

# --- 2. .env (idempotent — never clobber existing secrets) ------------------
if [ -f "$ENV_FILE" ]; then
  log "$ENV_FILE exists — reusing it (secrets preserved)."
else
  log "Generating $ENV_FILE …"
  APP_HOSTNAME="$(ask APP_HOSTNAME 'Your domain (DNS on Cloudflare), e.g. kin.example.com')"
  [ -n "$APP_HOSTNAME" ] || die "APP_HOSTNAME is required."
  ANTHROPIC_AUTH_TOKEN="$(ask ANTHROPIC_AUTH_TOKEN 'LLM gateway token (ARK/Anthropic-compatible, Bearer)')"
  [ -n "$ANTHROPIC_AUTH_TOKEN" ] || die "ANTHROPIC_AUTH_TOKEN is required."
  ANTHROPIC_BASE_URL="$(ask ANTHROPIC_BASE_URL 'Gateway base URL' 'https://ark.cn-beijing.volces.com/api/coding')"
  ANTHROPIC_MODEL="$(ask ANTHROPIC_MODEL 'Default model id (per your gateway)')"
  [ -n "$ANTHROPIC_MODEL" ] || die "ANTHROPIC_MODEL is required (else the model menu is empty)."
  ACME_EMAIL="$(ask ACME_EMAIL 'Email for Lets Encrypt TLS')"
  [ -n "$ACME_EMAIL" ] || die "ACME_EMAIL is required for the default TLS path."
  CF_DNS_API_TOKEN="$(ask CF_DNS_API_TOKEN 'Cloudflare API token (Zone:DNS:Edit — for the wildcard cert)')"
  [ -n "$CF_DNS_API_TOKEN" ] || die "CF_DNS_API_TOKEN is required for the wildcard cert (or switch to Origin CA, see docker-compose.md)."

  uniq="$(openssl rand -hex 3)"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install-vps.sh $(date -u +%FT%TZ). SECRET — chmod 600. Do not commit.
# --- identity / domain ---
APP_HOSTNAME=${APP_HOSTNAME}
APP_NAME=Kin
APP_NAME_SANITIZED=kin-${uniq}
# --- image (prebuilt multi-arch from GHCR; pull by default) ---
# NOTE: :latest is published only on the main-branch release. Before that, pin a published
# tag, e.g. APP_TAG=<git-sha>. See: docker buildx imagetools inspect ghcr.io/deeptoai-com/kin/app
APP_IMAGE=${APP_IMAGE:-ghcr.io/deeptoai-com/kin/app}
APP_TAG=${APP_TAG:-latest}
APP_PULL_POLICY=${APP_PULL_POLICY:-always}
# --- datastore + auth (auto-generated random secrets) ---
POSTGRES_USER=kin
POSTGRES_PASSWORD=$(rand)
POSTGRES_DB=kin
MINIO_ROOT_USER=kin
MINIO_ROOT_PASSWORD=$(rand)
MINIO_BUCKET=kin-files
MEILI_MASTER_KEY=$(rand)
BETTER_AUTH_SECRET=$(rand)
JOBS_SECRET=$(rand)
# --- TLS (Let's Encrypt DNS-01 via Cloudflare → wildcard cert for previews) ---
ACME_EMAIL=${ACME_EMAIL}
CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
# --- LLM gateway (ARK uses Bearer ANTHROPIC_AUTH_TOKEN; do NOT set ANTHROPIC_API_KEY) ---
ANTHROPIC_AUTH_TOKEN=${ANTHROPIC_AUTH_TOKEN}
ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL}
ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
ANTHROPIC_DEFAULT_SONNET_MODEL=${ANTHROPIC_MODEL}
ANTHROPIC_DEFAULT_OPUS_MODEL=${ANTHROPIC_MODEL}
ANTHROPIC_DEFAULT_HAIKU_MODEL=${ANTHROPIC_DEFAULT_HAIKU_MODEL:-${ANTHROPIC_MODEL}}
CLAUDE_CODE_SUBAGENT_MODEL=${ANTHROPIC_MODEL}
# --- first-run UX (register the first account without an email round-trip) ---
ENABLE_EMAIL_VERIFICATION=false
EOF
  chmod 600 "$ENV_FILE"
  log "$ENV_FILE written (chmod 600)."
fi

host_domain="$(grep -E '^APP_HOSTNAME=' "$ENV_FILE" | cut -d= -f2-)"
img_ref="$(grep -E '^APP_IMAGE=' "$ENV_FILE" | cut -d= -f2-):$(grep -E '^APP_TAG=' "$ENV_FILE" | cut -d= -f2-)"

# --- 3. pre-flight: image tag exists + DNS (soft) ---------------------------
log "Pre-flight: checking image ${img_ref} is pullable…"
docker manifest inspect "$img_ref" >/dev/null 2>&1 || \
  die "image ${img_ref} not found. If :latest isn't published yet, set APP_TAG to a published sha in $ENV_FILE (docker buildx imagetools inspect ghcr.io/deeptoai-com/kin/app)."

pubip="$(curl -fsS https://api.ipify.org 2>/dev/null || true)"
dnsip="$(getent hosts "$host_domain" 2>/dev/null | awk '{print $1}' | head -1 || true)"
if [ -n "$pubip" ] && [ -n "$dnsip" ] && [ "$pubip" != "$dnsip" ]; then
  warn "DNS: ${host_domain} → ${dnsip}, this host is ${pubip}. With Cloudflare proxy (orange-cloud) that's expected; otherwise fix the A record."
fi
warn "Make sure DNS has BOTH: A '@' → your IP AND A '*' (wildcard) — the wildcard is required for the TLS cert + previews."

# --- 4. bring up ------------------------------------------------------------
dc() { docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" -p "$PROJECT" "$@"; }
log "Pulling images…"; dc pull
log "Starting the stack…"; dc up -d

# --- 5. health gate ---------------------------------------------------------
log "Waiting for https://${host_domain}/health (up to ~5 min; first run also issues the TLS cert)…"
ok=0
for _ in $(seq 1 60); do
  code="$(curl -sk -o /dev/null -w '%{http_code}' "https://${host_domain}/health" 2>/dev/null || true)"
  [ "$code" = "200" ] && { ok=1; break; }
  sleep 5
done
echo
if [ "$ok" -eq 1 ]; then
  log "✅ Kin is up → https://${host_domain}"
  log "   Open it and register the first account (email verification is off)."
else
  warn "Stack started but https://${host_domain}/health hasn't returned 200 yet."
  warn "Inspect:  $SUDO docker compose -f $COMPOSE_FILE -p $PROJECT ps   /   logs -f app traefik"
  warn "Usual causes: DNS '@'/'*' not live yet, or the Cloudflare DNS-01 cert still issuing."
fi
