#!/usr/bin/env bash
# Connect a HOST-run build of OxyGenie to the *running Docker backend* (the same
# Postgres + Redis + data the deployed stack uses) — without exposing ports on the
# real containers, without touching .env, and without migrating the shared schema.
#
#   scripts/local-backend.sh up     # create socat bridges + write oxygenie/.env.local
#   scripts/local-backend.sh down   # remove bridges + .env.local
#
# WHY: the backend containers run on an internal Docker network with NO host port
# mapping, so a process on the host can't reach them (localhost:5432 has no
# listener; the `redis` hostname doesn't resolve). We attach throwaway `socat`
# sidecars to that network, publish them to localhost, and point .env.local there.
set -euo pipefail
cd "$(dirname "$0")/.."                                  # -> oxygenie/

APP="${OXY_APP_CONTAINER:-oxygenie-app}"
DBC="${OXY_DB_CONTAINER:-oxygenie-db}"
RDC="${OXY_REDIS_CONTAINER:-oxygenie-redis}"
PORT="${OXY_LOCAL_PORT:-3100}"
DB_HOSTPORT="${OXY_DB_HOSTPORT:-15432}"
RD_HOSTPORT="${OXY_REDIS_HOSTPORT:-16379}"

bridge_up() { # name network target hostport containerport
  local name="$1" net="$2" target="$3" hostport="$4" cport="$5"
  if [ -n "$(docker ps -q -f name="^${name}$")" ]; then echo "  ✓ $name already running"; return; fi
  docker rm -f "$name" >/dev/null 2>&1 || true
  docker run -d --name "$name" --network "$net" -p "127.0.0.1:${hostport}:${cport}" \
    alpine/socat "tcp-listen:${cport},fork,reuseaddr" "tcp-connect:${target}:${cport}" >/dev/null
  echo "  ✓ $name  127.0.0.1:${hostport} -> ${target}:${cport}"
}

case "${1:-}" in
  up)
    command -v docker >/dev/null || { echo "✗ docker not found"; exit 1; }
    [ -n "$(docker ps -q -f name="^${DBC}$")" ] || { echo "✗ $DBC not running — start the Docker stack first"; exit 1; }
    NET="$(docker inspect -f '{{range $k,$_ := .NetworkSettings.Networks}}{{$k}} {{end}}' "$DBC" | awk '{print $1}')"
    echo "→ docker network: $NET"
    bridge_up oxygenie-devbridge-db    "$NET" "$DBC" "$DB_HOSTPORT" 5432
    bridge_up oxygenie-devbridge-redis "$NET" "$RDC" "$RD_HOSTPORT" 6379
    # Pull the REAL connection strings from the running app container (creds always
    # match) and rewrite the internal host:port to the host-side bridge.
    DB="$(docker exec "$APP" printenv DATABASE_URL | sed -E "s#([@/])[A-Za-z0-9_.-]+:5432#\\1localhost:${DB_HOSTPORT}#")"
    RD="$(docker exec "$APP" printenv REDIS_URL    | sed -E "s#([@/])[A-Za-z0-9_.-]+:6379#\\1localhost:${RD_HOSTPORT}#")"
    # Preserve operator-added secret blocks across regeneration (this file is rewritten
    # wholesale). Currently: the zhipu section (RAG embedding/rerank key, R0). Sourced
    # from the old .env.local, else from the shell env, else from the app container.
    ZHIPU_BLOCK=""
    if [ -f .env.local ] && grep -q '^# >>> zhipu' .env.local; then
      ZHIPU_BLOCK="$(sed -n '/^# >>> zhipu/,/^# <<< zhipu/p' .env.local)"
    elif [ -n "${ZHIPU_API_KEY:-}" ]; then
      ZHIPU_BLOCK=$'# >>> zhipu (RAG embedding/rerank; gitignored — DO NOT COMMIT)\nZHIPU_API_KEY='"${ZHIPU_API_KEY}"$'\n# <<< zhipu'
    elif KEY="$(docker exec "$APP" printenv ZHIPU_API_KEY 2>/dev/null)" && [ -n "$KEY" ]; then
      ZHIPU_BLOCK=$'# >>> zhipu (RAG embedding/rerank; gitignored — DO NOT COMMIT)\nZHIPU_API_KEY='"${KEY}"$'\n# <<< zhipu'
    fi
    cat > .env.local <<EOF
# GENERATED by scripts/local-backend.sh — gitignored, DO NOT COMMIT, DO NOT EDIT .env.
# Points a host-run build at the running Docker backend via socat bridges.
DATABASE_URL=$DB
REDIS_URL=$RD
AUTO_MIGRATE=false
BETTER_AUTH_URL=http://127.0.0.1:${PORT}
BETTER_AUTH_TRUSTED_ORIGINS=http://127.0.0.1:${PORT},http://localhost:${PORT}
EOF
    if [ -n "$ZHIPU_BLOCK" ]; then
      printf '\n%s\n' "$ZHIPU_BLOCK" >> .env.local
      echo "  ✓ preserved zhipu section in .env.local"
    else
      echo "  ⚠ no ZHIPU_API_KEY found (old .env.local / shell env / $APP) — RAG embedding disabled locally"
    fi
    echo "  ✓ wrote oxygenie/.env.local (AUTO_MIGRATE=false → shared schema untouched)"
    echo "→ ready. Run: scripts/local-prod.sh --build"
    ;;
  down)
    docker rm -f oxygenie-devbridge-db oxygenie-devbridge-redis >/dev/null 2>&1 || true
    rm -f .env.local
    echo "✓ removed socat bridges + oxygenie/.env.local"
    ;;
  *)
    echo "usage: $0 up|down"; exit 1 ;;
esac
