import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * App-wide content dictionary
 * Contains navigation titles, button labels, and page titles used across the application
 */
const appContent = {
  content: {
    nav: {
      claudeChat: t({
        en: 'Claude Chat',
        'zh-Hans': 'Claude Chat',
        fr: 'Claude Chat',
        ja: 'Claude Chat',
        ko: 'Claude Chat',
        'zh-Hant': 'Claude Chat',
      }),
      capabilityCenter: t({
        en: 'Capability Center',
        'zh-Hans': '能力中心',
        fr: 'Centre de capacités',
        ja: '機能センター',
        ko: '기능 센터',
        'zh-Hant': '能力中心',
      }),
      skillsStore: t({
        en: 'Skills Store',
        'zh-Hans': '技能商店',
        fr: 'Boutique Skills',
        ja: 'スキルストア',
        ko: '스킬 스토어',
        'zh-Hant': '技能商店',
      }),
      mcpStore: t({
        en: 'MCP Store',
        'zh-Hans': 'MCP 商店',
        fr: 'Boutique MCP',
        ja: 'MCP ストア',
        ko: 'MCP 스토어',
        'zh-Hant': 'MCP 商店',
      }),
      aiChat: t({
        en: 'AI Chat',
        'zh-Hans': 'AI 聊天',
        fr: 'Chat IA',
        ja: 'AI チャット',
        ko: 'AI 채팅',
        'zh-Hant': 'AI 聊天',
      }),
      aiWorkflow: t({
        en: 'AI Workflow',
        'zh-Hans': 'AI 工作流',
        fr: 'Workflow IA',
        ja: 'AI ワークフロー',
        ko: 'AI 워크플로우',
        'zh-Hant': 'AI 工作流',
      }),
      documents: t({
        en: 'Documents / KB',
        'zh-Hans': '文档 / 知识库',
        fr: 'Documents / Base de connaissances',
        ja: 'ドキュメント / ナレッジベース',
        ko: '문서 / 지식베이스',
        'zh-Hant': '文件 / 知識庫',
      }),
      dashboards: t({
        en: 'Dashboards',
        'zh-Hans': '仪表板',
        fr: 'Tableaux de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      admin: t({
        en: 'Admin',
        'zh-Hans': '管理',
        fr: 'Admin',
        ja: '管理',
        ko: '관리',
        'zh-Hant': '管理',
      }),
      adminPanel: t({
        en: 'Admin Panel',
        'zh-Hans': '管理面板',
        fr: 'Panneau admin',
        ja: '管理パネル',
        ko: '관리 패널',
        'zh-Hant': '管理面板',
      }),
    },
    userMenu: {
      workspace: t({
        en: 'Workspace',
        'zh-Hans': '工作空间',
        fr: 'Espace de travail',
        ja: 'ワークスペース',
        ko: '작업 공간',
        'zh-Hant': '工作空間',
      }),
      account: t({
        en: 'Account',
        'zh-Hans': '账户',
        fr: 'Compte',
        ja: 'アカウント',
        ko: '계정',
        'zh-Hant': '帳戶',
      }),
      organization: t({
        en: 'Organization',
        'zh-Hans': '组织',
        fr: 'Organisation',
        ja: '組織',
        ko: '조직',
        'zh-Hant': '組織',
      }),
      preferences: t({
        en: 'Preferences',
        'zh-Hans': '偏好设置',
        fr: 'Préférences',
        ja: '設定',
        ko: '환경설정',
        'zh-Hant': '偏好設定',
      }),
      billing: t({
        en: 'Billing',
        'zh-Hans': '计费',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '計費',
      }),
      plans: t({
        en: 'Plans & subscription',
        'zh-Hans': '方案与订阅',
        fr: 'Plans et abonnement',
        ja: 'プランとサブスクリプション',
        ko: '플랜 및 구독',
        'zh-Hant': '方案與訂閱',
      }),
      billingAndInvoices: t({
        en: 'Billing & invoices',
        'zh-Hans': '计费与发票',
        fr: 'Facturation et factures',
        ja: '請求と請求書',
        ko: '결제 및 청구서',
        'zh-Hant': '計費與發票',
      }),
      logout: t({
        en: 'Log out',
        'zh-Hans': '退出登录',
        fr: 'Déconnexion',
        ja: 'ログアウト',
        ko: '로그아웃',
        'zh-Hant': '登出',
      }),
    },
    titles: {
      documents: t({
        en: 'Documents / KB',
        'zh-Hans': '文档 / 知识库',
        fr: 'Documents / Base de connaissances',
        ja: 'ドキュメント / ナレッジベース',
        ko: '문서 / 지식베이스',
        'zh-Hant': '文件 / 知識庫',
      }),
      claudeChat: t({
        en: 'Claude Chat',
        'zh-Hans': 'Claude Chat',
        fr: 'Claude Chat',
        ja: 'Claude Chat',
        ko: 'Claude Chat',
        'zh-Hant': 'Claude Chat',
      }),
      aiChat: t({
        en: 'AI Chat',
        'zh-Hans': 'AI 聊天',
        fr: 'Chat IA',
        ja: 'AI チャット',
        ko: 'AI 채팅',
        'zh-Hant': 'AI 聊天',
      }),
      aiWorkflow: t({
        en: 'AI Workflow',
        'zh-Hans': 'AI 工作流',
        fr: 'Workflow IA',
        ja: 'AI ワークフロー',
        ko: 'AI 워크플로우',
        'zh-Hant': 'AI 工作流',
      }),
      chat: t({
        en: 'Chat',
        'zh-Hans': '聊天',
        fr: 'Chat',
        ja: 'チャット',
        ko: '채팅',
        'zh-Hant': '聊天',
      }),
      imageChat: t({
        en: 'Image Chat',
        'zh-Hans': '图片聊天',
        fr: 'Chat image',
        ja: '画像チャット',
        ko: '이미지 채팅',
        'zh-Hant': '圖片聊天',
      }),
      workflow: t({
        en: 'Workflow',
        'zh-Hans': '工作流',
        fr: 'Workflow',
        ja: 'ワークフロー',
        ko: '워크플로우',
        'zh-Hant': '工作流',
      }),
      dashboard: t({
        en: 'Dashboard',
        'zh-Hans': '仪表板',
        fr: 'Tableau de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      skills: t({
        en: 'Skills',
        'zh-Hans': '技能',
        fr: 'Skills',
        ja: 'スキル',
        ko: '스킬',
        'zh-Hant': '技能',
      }),
      agent: t({
        en: 'Agent',
        'zh-Hans': '智能体',
        fr: 'Agent',
        ja: 'エージェント',
        ko: '에이전트',
        'zh-Hant': '智能體',
      }),
      billing: t({
        en: 'Billing',
        'zh-Hans': '计费',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '計費',
      }),
      billingSettings: t({
        en: 'Billing Settings',
        'zh-Hans': '计费设置',
        fr: 'Paramètres de facturation',
        ja: '請求設定',
        ko: '결제 설정',
        'zh-Hant': '計費設定',
      }),
    },
    buttons: {
      signIn: t({
        en: 'Sign In',
        'zh-Hans': '登录',
        fr: 'Connexion',
        ja: 'ログイン',
        ko: '로그인',
        'zh-Hant': '登入',
      }),
      agentChat: t({
        en: 'Agent Chat',
        'zh-Hans': '智能体聊天',
        fr: 'Chat Agent',
        ja: 'エージェントチャット',
        ko: '에이전트 채팅',
        'zh-Hant': '智能體聊天',
      }),
      signUp: t({
        en: 'Sign Up',
        'zh-Hans': '注册',
        fr: 'Créer un compte',
        ja: '新規登録',
        ko: '회원가입',
        'zh-Hant': '註冊',
      }),
      signOut: t({
        en: 'Sign Out',
        'zh-Hans': '退出登录',
        fr: 'Déconnexion',
        ja: 'ログアウト',
        ko: '로그아웃',
        'zh-Hant': '登出',
      }),
      save: t({
        en: 'Save',
        'zh-Hans': '保存',
        fr: 'Enregistrer',
        ja: '保存',
        ko: '저장',
        'zh-Hant': '儲存',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
      submit: t({
        en: 'Submit',
        'zh-Hans': '提交',
        fr: 'Envoyer',
        ja: '送信',
        ko: '제출',
        'zh-Hant': '提交',
      }),
      delete: t({
        en: 'Delete',
        'zh-Hans': '删除',
        fr: 'Supprimer',
        ja: '削除',
        ko: '삭제',
        'zh-Hant': '刪除',
      }),
      edit: t({
        en: 'Edit',
        'zh-Hans': '编辑',
        fr: 'Modifier',
        ja: '編集',
        ko: '편집',
        'zh-Hant': '編輯',
      }),
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
      back: t({
        en: 'Back',
        'zh-Hans': '返回',
        fr: 'Retour',
        ja: '戻る',
        ko: '뒤로',
        'zh-Hant': '返回',
      }),
      next: t({
        en: 'Next',
        'zh-Hans': '下一步',
        fr: 'Suivant',
        ja: '次へ',
        ko: '다음',
        'zh-Hant': '下一步',
      }),
      previous: t({
        en: 'Previous',
        'zh-Hans': '上一步',
        fr: 'Précédent',
        ja: '前へ',
        ko: '이전',
        'zh-Hant': '上一步',
      }),
      confirm: t({
        en: 'Confirm',
        'zh-Hans': '确认',
        fr: 'Confirmer',
        ja: '確認',
        ko: '확인',
        'zh-Hant': '確認',
      }),
      refresh: t({
        en: 'Refresh',
        'zh-Hans': '刷新',
        fr: 'Actualiser',
        ja: '更新',
        ko: '새로고침',
        'zh-Hant': '重新整理',
      }),
      loading: t({
        en: 'Loading...',
        'zh-Hans': '加载中...',
        fr: 'Chargement…',
        ja: '読み込み中…',
        ko: '로딩 중…',
        'zh-Hant': '載入中…',
      }),
    },
    meta: {
      title: t({
        en: 'DeeptoAI - AI Workspace',
        'zh-Hans': 'DeeptoAI - AI 工作台',
        fr: 'DeeptoAI - Espace IA',
        ja: 'DeeptoAI - AI ワークスペース',
        ko: 'DeeptoAI - AI 작업 공간',
        'zh-Hant': 'DeeptoAI - AI 工作台',
      }),
      description: t({
        en: 'AI workspace powered by Claude Agent SDK with streaming chat, skills management, artifacts, and sessions. Powered by Zhipu AI GLM-5.0',
        'zh-Hans': '基于 Claude Agent SDK 的 AI 工作台，支持流式对话、Skills 管理、Artifacts 展示和会话管理。Powered by Zhipu AI GLM-5.0',
        fr: 'Espace IA basé sur Claude Agent SDK : chat en flux, gestion des Skills, Artifacts et sessions. Powered by Zhipu AI GLM-5.0',
        ja: 'Claude Agent SDK による AI ワークスペース。ストリーミングチャット、Skills 管理、Artifacts、セッション。Powered by Zhipu AI GLM-5.0',
        ko: 'Claude Agent SDK 기반 AI 작업 공간. 스트리밍 채팅, Skills 관리, Artifacts, 세션. Powered by Zhipu AI GLM-5.0',
        'zh-Hant': '基於 Claude Agent SDK 的 AI 工作台，支援串流對話、Skills 管理、Artifacts 與會話管理。Powered by Zhipu AI GLM-5.0',
      }),
      keywords: t({
        en: 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
        'zh-Hans': 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
        fr: 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
        ja: 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
        ko: 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
        'zh-Hant': 'AI, Claude Agent, Zhipu AI, GLM-5.0, Chat, Skills, Artifacts, AI Workspace',
      }),
    },
    charts: {
      dashboard: t({
        en: 'Dashboard',
        'zh-Hans': '仪表板',
        fr: 'Tableau de bord',
        ja: 'ダッシュボード',
        ko: '대시보드',
        'zh-Hant': '儀表板',
      }),
      dashboardDesc: t({
        en: 'Monitor your key metrics and performance indicators.',
        'zh-Hans': '监控关键指标与表现。',
        fr: 'Suivez vos indicateurs clés.',
        ja: '主要指標とパフォーマンスを確認。',
        ko: '주요 지표와 성과를 확인하세요.',
        'zh-Hant': '監控關鍵指標與表現。',
      }),
      totalRevenue: t({
        en: 'Total Revenue',
        'zh-Hans': '总收入',
        fr: 'Revenus totaux',
        ja: '総収益',
        ko: '총 수익',
        'zh-Hant': '總收入',
      }),
      totalUsers: t({
        en: 'Total Users',
        'zh-Hans': '总用户数',
        fr: 'Utilisateurs totaux',
        ja: '総ユーザー数',
        ko: '총 사용자',
        'zh-Hant': '總用戶數',
      }),
      activeNow: t({
        en: 'Active Now',
        'zh-Hans': '当前活跃',
        fr: 'En ligne maintenant',
        ja: '現在アクティブ',
        ko: '현재 접속 중',
        'zh-Hant': '目前活躍',
      }),
      growthRate: t({
        en: 'Growth Rate',
        'zh-Hans': '增长率',
        fr: 'Taux de croissance',
        ja: '成長率',
        ko: '성장률',
        'zh-Hant': '成長率',
      }),
      overview: t({
        en: 'Overview',
        'zh-Hans': '概览',
        fr: 'Aperçu',
        ja: '概要',
        ko: '개요',
        'zh-Hant': '概覽',
      }),
      overviewDesc: t({
        en: 'Your performance metrics for the current period',
        'zh-Hans': '当前周期表现指标',
        fr: 'Indicateurs de la période en cours',
        ja: '現在期間のパフォーマンス指標',
        ko: '현재 기간 성과 지표',
        'zh-Hant': '目前週期表現指標',
      }),
      recentActivity: t({
        en: 'Recent Activity',
        'zh-Hans': '最近动态',
        fr: 'Activité récente',
        ja: '最近のアクティビティ',
        ko: '최근 활동',
        'zh-Hant': '最近動態',
      }),
      recentActivityDesc: t({
        en: 'Latest updates and transactions',
        'zh-Hans': '最新动态与交易',
        fr: 'Dernières mises à jour et transactions',
        ja: '最新の更新と取引',
        ko: '최신 업데이트 및 거래',
        'zh-Hant': '最新動態與交易',
      }),
    },
    aiWorkflow: {
      checkingAuth: t({
        en: 'Checking sign-in status…',
        'zh-Hans': '正在检查登录状态…',
        fr: 'Vérification de la connexion…',
        ja: 'ログイン状態を確認中…',
        ko: '로그인 상태 확인 중…',
        'zh-Hant': '正在檢查登入狀態…',
      }),
      hubSubtitle: t({
        en: 'Choose a workflow to get started. Each workflow is a multi-step intelligent process.',
        'zh-Hans': '选择一个工作流开始创作。每个工作流都是一个多步骤的智能流程。',
        fr: 'Choisissez un workflow pour commencer. Chaque workflow est un processus intelligent en plusieurs étapes.',
        ja: 'ワークフローを選んで開始。各ワークフローは複数ステップのインテリジェントなプロセスです。',
        ko: '시작할 워크플로우를 선택하세요. 각 워크플로우는 다단계 지능형 프로세스입니다.',
        'zh-Hant': '選擇一個工作流開始。每個工作流都是多步驟的智能流程。',
      }),
    },
    placeholders: {
      exampleCompany: t({
        en: 'e.g., TechCorp',
        'zh-Hans': '例如：TechCorp',
        fr: 'ex. TechCorp',
        ja: '例：TechCorp',
        ko: '예: TechCorp',
        'zh-Hant': '例如：TechCorp',
      }),
    },
    common: {
      appName: t({
        en: 'DeeptoAI',
        'zh-Hans': 'DeeptoAI',
        fr: 'DeeptoAI',
        ja: 'DeeptoAI',
        ko: 'DeeptoAI',
        'zh-Hant': 'DeeptoAI',
      }),
      welcome: t({
        en: 'Welcome',
        'zh-Hans': '欢迎',
        fr: 'Bienvenue',
        ja: 'ようこそ',
        ko: '환영합니다',
        'zh-Hant': '歡迎',
      }),
      welcomeTo: t({
        en: 'Welcome to {name}',
        'zh-Hans': '欢迎使用 {name}',
        fr: 'Bienvenue sur {name}',
        ja: '{name} へようこそ',
        ko: '{name}에 오신 것을 환영합니다',
        'zh-Hant': '歡迎使用 {name}',
      }),
      redirectingToAgentChat: t({
        en: 'Redirecting to Agent Chat...',
        'zh-Hans': '正在跳转到智能体聊天...',
        fr: 'Redirection vers le chat Agent…',
        ja: 'エージェントチャットへ移動中…',
        ko: '에이전트 채팅으로 이동 중…',
        'zh-Hant': '正在跳轉至智能體聊天…',
      }),
      error: t({
        en: 'Error',
        'zh-Hans': '错误',
        fr: 'Erreur',
        ja: 'エラー',
        ko: '오류',
        'zh-Hant': '錯誤',
      }),
      success: t({
        en: 'Success',
        'zh-Hans': '成功',
        fr: 'Succès',
        ja: '成功',
        ko: '성공',
        'zh-Hant': '成功',
      }),
      warning: t({
        en: 'Warning',
        'zh-Hans': '警告',
        fr: 'Attention',
        ja: '警告',
        ko: '경고',
        'zh-Hant': '警告',
      }),
      info: t({
        en: 'Info',
        'zh-Hans': '信息',
        fr: 'Info',
        ja: '情報',
        ko: '정보',
        'zh-Hant': '資訊',
      }),
    },
  },
  key: 'app',
} satisfies Dictionary;

export default appContent;
