import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Authentication-related content dictionary
 * Contains labels and messages for login, signup, and password recovery
 */
const authContent = {
  content: {
    signIn: {
      title: t({
        en: 'Sign In',
        'zh-Hans': '登录',
        fr: 'Connexion',
        ja: 'ログイン',
        ko: '로그인',
        'zh-Hant': '登入',
      }),
      subtitle: t({
        en: 'Enter your credentials to access your account',
        'zh-Hans': '输入您的凭证以访问您的账户',
        fr: 'Entrez vos identifiants pour accéder à votre compte',
        ja: 'アカウントにアクセスするには認証情報を入力してください',
        ko: '계정에 접속하려면 로그인 정보를 입력하세요',
        'zh-Hant': '輸入您的帳號密碼以存取帳戶',
      }),
      emailLabel: t({
        en: 'Email',
        'zh-Hans': '邮箱',
        fr: 'E-mail',
        ja: 'メール',
        ko: '이메일',
        'zh-Hant': '電子郵件',
      }),
      emailPlaceholder: t({
        en: 'Enter your email',
        'zh-Hans': '请输入邮箱',
        fr: 'Entrez votre e-mail',
        ja: 'メールアドレスを入力',
        ko: '이메일 입력',
        'zh-Hant': '請輸入電子郵件',
      }),
      passwordLabel: t({
        en: 'Password',
        'zh-Hans': '密码',
        fr: 'Mot de passe',
        ja: 'パスワード',
        ko: '비밀번호',
        'zh-Hant': '密碼',
      }),
      passwordPlaceholder: t({
        en: 'Enter your password',
        'zh-Hans': '请输入密码',
        fr: 'Entrez votre mot de passe',
        ja: 'パスワードを入力',
        ko: '비밀번호 입력',
        'zh-Hant': '請輸入密碼',
      }),
      rememberMe: t({
        en: 'Remember me',
        'zh-Hans': '记住我',
        fr: 'Se souvenir de moi',
        ja: 'ログイン状態を保持',
        ko: '로그인 유지',
        'zh-Hant': '記住我',
      }),
      forgotPassword: t({
        en: 'Forgot password?',
        'zh-Hans': '忘记密码？',
        fr: 'Mot de passe oublié ?',
        ja: 'パスワードをお忘れですか？',
        ko: '비밀번호를 잊으셨나요?',
        'zh-Hant': '忘記密碼？',
      }),
      noAccount: t({
        en: "Don't have an account?",
        'zh-Hans': '没有账户？',
        fr: "Pas encore de compte ?",
        ja: 'アカウントをお持ちでないですか？',
        ko: '계정이 없으신가요?',
        'zh-Hant': '還沒有帳戶？',
      }),
      signUpLink: t({
        en: 'Sign up',
        'zh-Hans': '注册',
        fr: 'Créer un compte',
        ja: '新規登録',
        ko: '회원가입',
        'zh-Hant': '註冊',
      }),
      submitButton: t({
        en: 'Sign In',
        'zh-Hans': '登录',
        fr: 'Connexion',
        ja: 'ログイン',
        ko: '로그인',
        'zh-Hant': '登入',
      }),
      orContinueWith: t({
        en: 'Or continue with',
        'zh-Hans': '或使用以下方式继续',
        fr: 'Ou continuer avec',
        ja: 'または以下で続行',
        ko: '또는 다음으로 계속',
        'zh-Hant': '或使用以下方式繼續',
      }),
    },
    signUp: {
      title: t({
        en: 'Sign Up',
        'zh-Hans': '注册',
        fr: 'Créer un compte',
        ja: '新規登録',
        ko: '회원가입',
        'zh-Hant': '註冊',
      }),
      subtitle: t({
        en: 'Create a new account to get started',
        'zh-Hans': '创建新账户以开始使用',
        fr: 'Créez un compte pour commencer',
        ja: '新規アカウントを作成して開始',
        ko: '새 계정을 만들어 시작하세요',
        'zh-Hant': '建立新帳戶以開始使用',
      }),
      nameLabel: t({
        en: 'Name',
        'zh-Hans': '姓名',
        fr: 'Nom',
        ja: '名前',
        ko: '이름',
        'zh-Hant': '姓名',
      }),
      namePlaceholder: t({
        en: 'Enter your name',
        'zh-Hans': '请输入姓名',
        fr: 'Entrez votre nom',
        ja: '名前を入力',
        ko: '이름 입력',
        'zh-Hant': '請輸入姓名',
      }),
      emailLabel: t({
        en: 'Email',
        'zh-Hans': '邮箱',
        fr: 'E-mail',
        ja: 'メール',
        ko: '이메일',
        'zh-Hant': '電子郵件',
      }),
      emailPlaceholder: t({
        en: 'Enter your email',
        'zh-Hans': '请输入邮箱',
        fr: 'Entrez votre e-mail',
        ja: 'メールアドレスを入力',
        ko: '이메일 입력',
        'zh-Hant': '請輸入電子郵件',
      }),
      passwordLabel: t({
        en: 'Password',
        'zh-Hans': '密码',
        fr: 'Mot de passe',
        ja: 'パスワード',
        ko: '비밀번호',
        'zh-Hant': '密碼',
      }),
      passwordPlaceholder: t({
        en: 'Create a password',
        'zh-Hans': '创建密码',
        fr: 'Créez un mot de passe',
        ja: 'パスワードを作成',
        ko: '비밀번호 생성',
        'zh-Hant': '建立密碼',
      }),
      confirmPasswordLabel: t({
        en: 'Confirm Password',
        'zh-Hans': '确认密码',
        fr: 'Confirmer le mot de passe',
        ja: 'パスワード確認',
        ko: '비밀번호 확인',
        'zh-Hant': '確認密碼',
      }),
      confirmPasswordPlaceholder: t({
        en: 'Confirm your password',
        'zh-Hans': '确认您的密码',
        fr: 'Confirmez votre mot de passe',
        ja: 'パスワードを再入力',
        ko: '비밀번호 확인 입력',
        'zh-Hant': '請再次輸入密碼',
      }),
      agreeToTerms: t({
        en: 'I agree to the',
        'zh-Hans': '我同意',
        fr: "J'accepte les",
        ja: '以下に同意します',
        ko: '다음에 동의합니다',
        'zh-Hant': '我同意',
      }),
      termsOfService: t({
        en: 'Terms of Service',
        'zh-Hans': '服务条款',
        fr: "Conditions d'utilisation",
        ja: '利用規約',
        ko: '이용약관',
        'zh-Hant': '服務條款',
      }),
      and: t({
        en: 'and',
        'zh-Hans': '和',
        fr: 'et',
        ja: 'および',
        ko: '및',
        'zh-Hant': '與',
      }),
      privacyPolicy: t({
        en: 'Privacy Policy',
        'zh-Hans': '隐私政策',
        fr: 'Politique de confidentialité',
        ja: 'プライバシーポリシー',
        ko: '개인정보 처리방침',
        'zh-Hant': '隱私權政策',
      }),
      hasAccount: t({
        en: 'Already have an account?',
        'zh-Hans': '已有账户？',
        fr: 'Déjà un compte ?',
        ja: 'すでにアカウントをお持ちですか？',
        ko: '이미 계정이 있으신가요?',
        'zh-Hant': '已有帳戶？',
      }),
      signInLink: t({
        en: 'Sign in',
        'zh-Hans': '登录',
        fr: 'Connexion',
        ja: 'ログイン',
        ko: '로그인',
        'zh-Hant': '登入',
      }),
      submitButton: t({
        en: 'Create Account',
        'zh-Hans': '创建账户',
        fr: 'Créer le compte',
        ja: 'アカウント作成',
        ko: '계정 만들기',
        'zh-Hant': '建立帳戶',
      }),
    },
    forgotPassword: {
      title: t({
        en: 'Forgot Password',
        'zh-Hans': '忘记密码',
        fr: 'Mot de passe oublié',
        ja: 'パスワードを忘れた',
        ko: '비밀번호 찾기',
        'zh-Hant': '忘記密碼',
      }),
      subtitle: t({
        en: 'Enter your email to receive a password reset link',
        'zh-Hans': '输入您的邮箱以接收密码重置链接',
        fr: 'E-mail pour recevoir le lien de réinitialisation',
        ja: 'パスワード再設定リンクを受け取るメールを入力',
        ko: '비밀번호 재설정 링크를 받을 이메일 입력',
        'zh-Hant': '輸入您的電子郵件以接收密碼重設連結',
      }),
      emailLabel: t({
        en: 'Email',
        'zh-Hans': '邮箱',
        fr: 'E-mail',
        ja: 'メール',
        ko: '이메일',
        'zh-Hant': '電子郵件',
      }),
      emailPlaceholder: t({
        en: 'Enter your email',
        'zh-Hans': '请输入邮箱',
        fr: 'Entrez votre e-mail',
        ja: 'メールアドレスを入力',
        ko: '이메일 입력',
        'zh-Hant': '請輸入電子郵件',
      }),
      submitButton: t({
        en: 'Send Reset Link',
        'zh-Hans': '发送重置链接',
        fr: 'Envoyer le lien',
        ja: 'リンクを送信',
        ko: '재설정 링크 보내기',
        'zh-Hant': '傳送重設連結',
      }),
      backToSignIn: t({
        en: 'Back to Sign In',
        'zh-Hans': '返回登录',
        fr: 'Retour à la connexion',
        ja: 'ログインに戻る',
        ko: '로그인으로 돌아가기',
        'zh-Hant': '返回登入',
      }),
    },
    resetPassword: {
      title: t({
        en: 'Reset Password',
        'zh-Hans': '重置密码',
        fr: 'Réinitialiser le mot de passe',
        ja: 'パスワードをリセット',
        ko: '비밀번호 재설정',
        'zh-Hant': '重設密碼',
      }),
      subtitle: t({
        en: 'Enter your new password below',
        'zh-Hans': '在下方输入您的新密码',
        fr: 'Entrez votre nouveau mot de passe ci-dessous',
        ja: '新しいパスワードを入力してください',
        ko: '아래에 새 비밀번호를 입력하세요',
        'zh-Hant': '請在下方輸入您的新密碼',
      }),
      newPasswordLabel: t({
        en: 'New Password',
        'zh-Hans': '新密码',
        fr: 'Nouveau mot de passe',
        ja: '新しいパスワード',
        ko: '새 비밀번호',
        'zh-Hant': '新密碼',
      }),
      newPasswordPlaceholder: t({
        en: 'Enter new password',
        'zh-Hans': '输入新密码',
        fr: 'Entrez le nouveau mot de passe',
        ja: '新しいパスワードを入力',
        ko: '새 비밀번호 입력',
        'zh-Hant': '請輸入新密碼',
      }),
      confirmPasswordLabel: t({
        en: 'Confirm Password',
        'zh-Hans': '确认密码',
        fr: 'Confirmer le mot de passe',
        ja: 'パスワード確認',
        ko: '비밀번호 확인',
        'zh-Hant': '確認密碼',
      }),
      confirmPasswordPlaceholder: t({
        en: 'Confirm new password',
        'zh-Hans': '确认新密码',
        fr: 'Confirmez le nouveau mot de passe',
        ja: '新しいパスワードを再入力',
        ko: '새 비밀번호 확인 입력',
        'zh-Hant': '請再次輸入新密碼',
      }),
      submitButton: t({
        en: 'Reset Password',
        'zh-Hans': '重置密码',
        fr: 'Réinitialiser',
        ja: 'リセット',
        ko: '재설정',
        'zh-Hant': '重設密碼',
      }),
    },
    verification: {
      title: t({
        en: 'Verify Your Email',
        'zh-Hans': '验证您的邮箱',
        fr: 'Vérifiez votre e-mail',
        ja: 'メールを確認してください',
        ko: '이메일을 확인하세요',
        'zh-Hant': '驗證您的電子郵件',
      }),
      subtitle: t({
        en: 'We sent a verification code to your email',
        'zh-Hans': '我们向您的邮箱发送了验证码',
        fr: 'Un code de vérification a été envoyé à votre e-mail',
        ja: '確認コードをメールで送信しました',
        ko: '이메일로 인증 코드를 보냈습니다',
        'zh-Hant': '我們已向您的電子郵件寄送驗證碼',
      }),
      codeLabel: t({
        en: 'Verification Code',
        'zh-Hans': '验证码',
        fr: 'Code de vérification',
        ja: '確認コード',
        ko: '인증 코드',
        'zh-Hant': '驗證碼',
      }),
      codePlaceholder: t({
        en: 'Enter 6-digit code',
        'zh-Hans': '输入 6 位验证码',
        fr: 'Code à 6 chiffres',
        ja: '6桁のコードを入力',
        ko: '6자리 코드 입력',
        'zh-Hant': '請輸入 6 位驗證碼',
      }),
      resendCode: t({
        en: "Didn't receive the code? Resend",
        'zh-Hans': '没有收到验证码？重新发送',
        fr: "Pas reçu ? Renvoyer",
        ja: '届いていませんか？再送信',
        ko: '코드를 받지 못했나요? 다시 보내기',
        'zh-Hant': '沒收到驗證碼？重新傳送',
      }),
      submitButton: t({
        en: 'Verify',
        'zh-Hans': '验证',
        fr: 'Vérifier',
        ja: '確認',
        ko: '확인',
        'zh-Hant': '驗證',
      }),
    },
    errors: {
      invalidCredentials: t({
        en: 'Invalid email or password',
        'zh-Hans': '邮箱或密码无效',
        fr: 'E-mail ou mot de passe incorrect',
        ja: 'メールまたはパスワードが正しくありません',
        ko: '이메일 또는 비밀번호가 올바르지 않습니다',
        'zh-Hant': '電子郵件或密碼無效',
      }),
      emailAlreadyExists: t({
        en: 'An account with this email already exists',
        'zh-Hans': '此邮箱的账户已存在',
        fr: 'Un compte existe déjà avec cet e-mail',
        ja: 'このメールのアカウントは既に存在します',
        ko: '이 이메일로 가입된 계정이 이미 있습니다',
        'zh-Hant': '此電子郵件的帳戶已存在',
      }),
      weakPassword: t({
        en: 'Password is too weak. Please use a stronger password.',
        'zh-Hans': '密码太弱。请使用更强的密码。',
        fr: 'Mot de passe trop faible. Utilisez un mot de passe plus fort.',
        ja: 'パスワードが弱すぎます。より強力なパスワードをご利用ください。',
        ko: '비밀번호가 너무 약합니다. 더 강한 비밀번호를 사용하세요.',
        'zh-Hant': '密碼強度不足，請使用更強的密碼。',
      }),
      passwordsDoNotMatch: t({
        en: 'Passwords do not match',
        'zh-Hans': '密码不匹配',
        fr: 'Les mots de passe ne correspondent pas',
        ja: 'パスワードが一致しません',
        ko: '비밀번호가 일치하지 않습니다',
        'zh-Hant': '密碼不一致',
      }),
      invalidVerificationCode: t({
        en: 'Invalid verification code',
        'zh-Hans': '验证码无效',
        fr: 'Code de vérification invalide',
        ja: '確認コードが無効です',
        ko: '인증 코드가 올바르지 않습니다',
        'zh-Hant': '驗證碼無效',
      }),
      expiredCode: t({
        en: 'Verification code has expired. Please request a new one.',
        'zh-Hans': '验证码已过期。请请求新的验证码。',
        fr: 'Le code a expiré. Demandez-en un nouveau.',
        ja: '確認コードの有効期限が切れました。新しいコードをリクエストしてください。',
        ko: '인증 코드가 만료되었습니다. 새 코드를 요청하세요.',
        'zh-Hant': '驗證碼已過期，請重新取得驗證碼。',
      }),
    },
    success: {
      passwordResetSent: t({
        en: 'Password reset link has been sent to your email',
        'zh-Hans': '密码重置链接已发送到您的邮箱',
        fr: 'Lien de réinitialisation envoyé à votre e-mail',
        ja: 'パスワード再設定リンクをメールで送信しました',
        ko: '비밀번호 재설정 링크를 이메일로 보냈습니다',
        'zh-Hant': '密碼重設連結已寄至您的電子郵件',
      }),
      passwordResetSuccess: t({
        en: 'Password has been reset successfully',
        'zh-Hans': '密码已成功重置',
        fr: 'Mot de passe réinitialisé avec succès',
        ja: 'パスワードをリセットしました',
        ko: '비밀번호가 성공적으로 재설정되었습니다',
        'zh-Hant': '密碼已成功重設',
      }),
      accountCreated: t({
        en: 'Account created successfully',
        'zh-Hans': '账户创建成功',
        fr: 'Compte créé avec succès',
        ja: 'アカウントを作成しました',
        ko: '계정이 성공적으로 생성되었습니다',
        'zh-Hant': '帳戶建立成功',
      }),
      emailVerified: t({
        en: 'Email verified successfully',
        'zh-Hans': '邮箱验证成功',
        fr: 'E-mail vérifié avec succès',
        ja: 'メールを確認しました',
        ko: '이메일이 성공적으로 인증되었습니다',
        'zh-Hant': '電子郵件驗證成功',
      }),
    },
    emailVerificationBanner: {
      title: t({
        en: 'Verify your email address',
        'zh-Hans': '请验证您的邮箱',
        fr: 'Vérifiez votre adresse e-mail',
        ja: 'メールアドレスを確認してください',
        ko: '이메일 주소를 확인하세요',
        'zh-Hant': '請驗證您的電子郵件',
      }),
      message: t({
        en: 'We sent a verification link to {email}. You need to verify your email before you can access all features.',
        'zh-Hans': '我们已向 {email} 发送验证链接。请先验证邮箱以使用全部功能。',
        fr: 'Un lien de vérification a été envoyé à {email}. Vérifiez votre e-mail pour accéder à toutes les fonctionnalités.',
        ja: '確認リンクを {email} に送信しました。全機能をご利用になるにはメールの確認が必要です。',
        ko: '{email}(으)로 인증 링크를 보냈습니다. 모든 기능을 사용하려면 이메일 인증이 필요합니다.',
        'zh-Hant': '我們已向 {email} 寄送驗證連結。請先驗證電子郵件以使用全部功能。',
      }),
      sentMessage: t({
        en: 'Verification email sent. Check your inbox for the latest link.',
        'zh-Hans': '验证邮件已发送，请查收收件箱中的最新链接。',
        fr: 'E-mail de vérification envoyé. Consultez votre boîte de réception.',
        ja: '確認メールを送信しました。受信トレイをご確認ください。',
        ko: '인증 이메일을 보냈습니다. 받은편지함에서 링크를 확인하세요.',
        'zh-Hant': '驗證郵件已寄出，請至收件匣查看最新連結。',
      }),
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
    },
  },
  key: 'auth',
} satisfies Dictionary;

export default authContent;
