import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Billing and payment page content dictionary
 * Contains labels and messages for subscription management and payment processing
 */
const billingContent = {
  content: {
    page: {
      title: t({
        en: 'Billing',
        'zh-Hans': '计费',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '計費',
      }),
      subtitle: t({
        en: 'Manage your subscription and payment methods',
        'zh-Hans': '管理您的订阅和付款方式',
        fr: 'Gérer abonnement et moyens de paiement',
        ja: 'サブスクリプションと支払い方法を管理',
        ko: '구독 및 결제 수단 관리',
        'zh-Hant': '管理您的訂閱與付款方式',
      }),
    },
    credits: {
      label: t({
        en: 'Credits',
        'zh-Hans': '积分',
        fr: 'Crédits',
        ja: 'クレジット',
        ko: '크레딧',
        'zh-Hant': '積分',
      }),
      refillsDaily: t({
        en: 'Refills daily while below monthly cap.',
        'zh-Hans': '低于月度上限时每日补充。',
        fr: 'Rechargés quotidiennement sous le plafond mensuel.',
        ja: '月間上限未満の間、毎日補充されます。',
        ko: '월간 한도 미만일 때 매일 충전됩니다.',
        'zh-Hant': '低於月度上限時每日補充。',
      }),
    },
    currentPlanBadge: t({
      en: 'Current plan',
      'zh-Hans': '当前计划',
      fr: 'Plan actuel',
      ja: '現在のプラン',
      ko: '현재 플랜',
      'zh-Hant': '目前方案',
    }),
    currentPlan: {
      title: t({
        en: 'Current Plan',
        'zh-Hans': '当前计划',
        fr: 'Plan actuel',
        ja: '現在のプラン',
        ko: '현재 플랜',
        'zh-Hant': '目前方案',
      }),
      planName: t({
        en: 'Plan Name',
        'zh-Hans': '计划名称',
        fr: 'Nom du plan',
        ja: 'プラン名',
        ko: '플랜 이름',
        'zh-Hant': '方案名稱',
      }),
      status: t({
        en: 'Status',
        'zh-Hans': '状态',
        fr: 'Statut',
        ja: 'ステータス',
        ko: '상태',
        'zh-Hant': '狀態',
      }),
      active: t({
        en: 'Active',
        'zh-Hans': '活跃',
        fr: 'Actif',
        ja: '有効',
        ko: '활성',
        'zh-Hant': '有效',
      }),
      canceled: t({
        en: 'Canceled',
        'zh-Hans': '已取消',
        fr: 'Annulé',
        ja: 'キャンセル済み',
        ko: '취소됨',
        'zh-Hant': '已取消',
      }),
      pastDue: t({
        en: 'Past Due',
        'zh-Hans': '逾期',
        fr: 'En retard',
        ja: '期限超過',
        ko: '연체',
        'zh-Hant': '逾期',
      }),
      trial: t({
        en: 'Trial',
        'zh-Hans': '试用',
        fr: 'Essai',
        ja: 'トライアル',
        ko: '체험',
        'zh-Hant': '試用',
      }),
      renewsOn: t({
        en: 'Renews on',
        'zh-Hans': '续费日期',
        fr: 'Renouvellement le',
        ja: '更新日',
        ko: '갱신일',
        'zh-Hant': '續訂日',
      }),
      expiresOn: t({
        en: 'Expires on',
        'zh-Hans': '到期日期',
        fr: 'Expire le',
        ja: '有効期限',
        ko: '만료일',
        'zh-Hant': '到期日',
      }),
      usage: {
        title: t({
          en: 'Usage This Month',
          'zh-Hans': '本月使用量',
          fr: 'Utilisation ce mois',
          ja: '今月の使用量',
          ko: '이번 달 사용량',
          'zh-Hant': '本月使用量',
        }),
        messages: t({
          en: 'Messages',
          'zh-Hans': '消息',
          fr: 'Messages',
          ja: 'メッセージ',
          ko: '메시지',
          'zh-Hant': '訊息',
        }),
        of: t({
          en: 'of',
          'zh-Hans': '/',
          fr: 'sur',
          ja: '/',
          ko: '/',
          'zh-Hant': '/',
        }),
        resetOn: t({
          en: 'Resets on',
          'zh-Hans': '重置日期',
          fr: 'Réinitialisation le',
          ja: 'リセット日',
          ko: '리셋일',
          'zh-Hant': '重置日',
        }),
      },
    },
    plans: {
      title: t({
        en: 'Available Plans',
        'zh-Hans': '可用计划',
        fr: 'Plans disponibles',
        ja: '利用可能なプラン',
        ko: '이용 가능한 플랜',
        'zh-Hant': '可用方案',
      }),
      subtitle: t({
        en: 'Upgrade or downgrade your subscription',
        'zh-Hans': '升级或降级您的订阅',
        fr: 'Changer de plan',
        ja: 'プランのアップグレードまたはダウングレード',
        ko: '구독 업그레이드 또는 다운그레이드',
        'zh-Hant': '升級或降級您的訂閱',
      }),
      current: t({
        en: 'Current Plan',
        'zh-Hans': '当前计划',
        fr: 'Plan actuel',
        ja: '現在のプラン',
        ko: '현재 플랜',
        'zh-Hant': '目前方案',
      }),
      upgrade: t({
        en: 'Upgrade',
        'zh-Hans': '升级',
        fr: 'Mettre à niveau',
        ja: 'アップグレード',
        ko: '업그레이드',
        'zh-Hant': '升級',
      }),
      downgrade: t({
        en: 'Downgrade',
        'zh-Hans': '降级',
        fr: 'Rétrograder',
        ja: 'ダウングレード',
        ko: '다운그레이드',
        'zh-Hant': '降級',
      }),
      mostPopular: t({
        en: 'Most Popular',
        'zh-Hans': '最受欢迎',
        fr: 'Le plus populaire',
        ja: '人気No.1',
        ko: '인기',
        'zh-Hant': '最受歡迎',
      }),
    },
    paymentMethods: {
      title: t({
        en: 'Payment Methods',
        'zh-Hans': '付款方式',
        fr: 'Moyens de paiement',
        ja: '支払い方法',
        ko: '결제 수단',
        'zh-Hant': '付款方式',
      }),
      addNew: t({
        en: 'Add Payment Method',
        'zh-Hans': '添加付款方式',
        fr: 'Ajouter un moyen de paiement',
        ja: '支払い方法を追加',
        ko: '결제 수단 추가',
        'zh-Hant': '新增付款方式',
      }),
      default: t({
        en: 'Default',
        'zh-Hans': '默认',
        fr: 'Par défaut',
        ja: 'デフォルト',
        ko: '기본',
        'zh-Hant': '預設',
      }),
      cardEndingIn: t({
        en: 'Card ending in',
        'zh-Hans': '卡号末四位',
        fr: 'Carte se terminant par',
        ja: '下4桁',
        ko: '끝 4자리',
        'zh-Hant': '卡號末四碼',
      }),
      expires: t({
        en: 'Expires',
        'zh-Hans': '到期',
        fr: 'Expire',
        ja: '有効期限',
        ko: '만료',
        'zh-Hant': '到期',
      }),
      setAsDefault: t({
        en: 'Set as Default',
        'zh-Hans': '设为默认',
        fr: 'Définir par défaut',
        ja: 'デフォルトに設定',
        ko: '기본으로 설정',
        'zh-Hant': '設為預設',
      }),
      remove: t({
        en: 'Remove',
        'zh-Hans': '移除',
        fr: 'Supprimer',
        ja: '削除',
        ko: '제거',
        'zh-Hant': '移除',
      }),
    },
    billingHistory: {
      title: t({
        en: 'Billing History',
        'zh-Hans': '账单历史',
        fr: 'Historique de facturation',
        ja: '請求履歴',
        ko: '결제 내역',
        'zh-Hant': '帳單歷史',
      }),
      invoice: t({
        en: 'Invoice',
        'zh-Hans': '发票',
        fr: 'Facture',
        ja: '請求書',
        ko: '청구서',
        'zh-Hant': '發票',
      }),
      date: t({
        en: 'Date',
        'zh-Hans': '日期',
        fr: 'Date',
        ja: '日付',
        ko: '날짜',
        'zh-Hant': '日期',
      }),
      amount: t({
        en: 'Amount',
        'zh-Hans': '金额',
        fr: 'Montant',
        ja: '金額',
        ko: '금액',
        'zh-Hant': '金額',
      }),
      status: t({
        en: 'Status',
        'zh-Hans': '状态',
        fr: 'Statut',
        ja: 'ステータス',
        ko: '상태',
        'zh-Hant': '狀態',
      }),
      paid: t({
        en: 'Paid',
        'zh-Hans': '已支付',
        fr: 'Payé',
        ja: '支払済み',
        ko: '결제 완료',
        'zh-Hant': '已付款',
      }),
      pending: t({
        en: 'Pending',
        'zh-Hans': '待处理',
        fr: 'En attente',
        ja: '保留中',
        ko: '대기 중',
        'zh-Hant': '待處理',
      }),
      failed: t({
        en: 'Failed',
        'zh-Hans': '失败',
        fr: 'Échoué',
        ja: '失敗',
        ko: '실패',
        'zh-Hant': '失敗',
      }),
      download: t({
        en: 'Download',
        'zh-Hans': '下载',
        fr: 'Télécharger',
        ja: 'ダウンロード',
        ko: '다운로드',
        'zh-Hant': '下載',
      }),
    },
    invoices: {
      title: t({
        en: 'Invoices',
        'zh-Hans': '发票',
        fr: 'Factures',
        ja: '請求書',
        ko: '청구서',
        'zh-Hant': '發票',
      }),
      noInvoices: t({
        en: 'No invoices yet',
        'zh-Hans': '暂无发票',
        fr: 'Aucune facture',
        ja: '請求書はまだありません',
        ko: '청구서가 없습니다',
        'zh-Hant': '尚無發票',
      }),
      downloadPdf: t({
        en: 'Download PDF',
        'zh-Hans': '下载 PDF',
        fr: 'Télécharger PDF',
        ja: 'PDFをダウンロード',
        ko: 'PDF 다운로드',
        'zh-Hant': '下載 PDF',
      }),
    },
    manageSubscription: {
      title: t({
        en: 'Manage Subscription',
        'zh-Hans': '管理订阅',
        fr: 'Gérer l\'abonnement',
        ja: 'サブスクリプション管理',
        ko: '구독 관리',
        'zh-Hant': '管理訂閱',
      }),
      cancelSubscription: t({
        en: 'Cancel Subscription',
        'zh-Hans': '取消订阅',
        fr: 'Annuler l\'abonnement',
        ja: 'サブスクリプションをキャンセル',
        ko: '구독 취소',
        'zh-Hant': '取消訂閱',
      }),
      reactivateSubscription: t({
        en: 'Reactivate Subscription',
        'zh-Hans': '重新激活订阅',
        fr: 'Réactiver l\'abonnement',
        ja: 'サブスクリプションを再開',
        ko: '구독 재활성화',
        'zh-Hant': '重新啟用訂閱',
      }),
    },
    cancelFlow: {
      title: t({
        en: 'Cancel Subscription',
        'zh-Hans': '取消订阅',
        fr: 'Annuler l\'abonnement',
        ja: 'サブスクリプションをキャンセル',
        ko: '구독 취소',
        'zh-Hant': '取消訂閱',
      }),
      subtitle: t({
        en: 'We are sorry to see you go',
        'zh-Hans': '很遗憾您要离开',
        fr: 'Nous sommes désolés de vous voir partir',
        ja: 'ご利用ありがとうございました',
        ko: '이용해 주셔서 감사합니다',
        'zh-Hant': '很遺憾您要離開',
      }),
      reason: {
        title: t({
          en: 'Reason for cancellation',
          'zh-Hans': '取消原因',
          fr: 'Raison de l\'annulation',
          ja: 'キャンセル理由',
          ko: '취소 사유',
          'zh-Hant': '取消原因',
        }),
        required: t({
          en: 'Please select a reason',
          'zh-Hans': '请选择原因',
          fr: 'Veuillez choisir une raison',
          ja: '理由を選択してください',
          ko: '사유를 선택하세요',
          'zh-Hant': '請選擇原因',
        }),
        tooExpensive: t({
          en: 'Too expensive',
          'zh-Hans': '太贵了',
          fr: 'Trop cher',
          ja: '料金が高い',
          ko: '비용이 높음',
          'zh-Hant': '太貴',
        }),
        notNeeded: t({
          en: 'No longer needed',
          'zh-Hans': '不再需要',
          fr: 'Plus besoin',
          ja: '不要になった',
          ko: '더 이상 필요 없음',
          'zh-Hant': '不再需要',
        }),
        missingFeatures: t({
          en: 'Missing features',
          'zh-Hans': '缺少功能',
          fr: 'Fonctionnalités manquantes',
          ja: '機能が足りない',
          ko: '기능 부족',
          'zh-Hant': '缺少功能',
        }),
        foundAlternative: t({
          en: 'Found an alternative',
          'zh-Hans': '找到了替代方案',
          fr: 'J\'ai trouvé une alternative',
          ja: '代替案を見つけた',
          ko: '대안을 찾음',
          'zh-Hant': '找到替代方案',
        }),
        technicalIssues: t({
          en: 'Technical issues',
          'zh-Hans': '技术问题',
          fr: 'Problèmes techniques',
          ja: '技術的な問題',
          ko: '기술적 문제',
          'zh-Hant': '技術問題',
        }),
        other: t({
          en: 'Other',
          'zh-Hans': '其他',
          fr: 'Autre',
          ja: 'その他',
          ko: '기타',
          'zh-Hant': '其他',
        }),
      },
      feedback: {
        title: t({
          en: 'Additional feedback (optional)',
          'zh-Hans': '额外反馈（可选）',
          fr: 'Commentaires (optionnel)',
          ja: '追加のフィードバック（任意）',
          ko: '추가 의견 (선택)',
          'zh-Hant': '額外回饋（選填）',
        }),
        placeholder: t({
          en: 'Tell us how we can improve',
          'zh-Hans': '告诉我们如何改进',
          fr: 'Dites-nous comment nous améliorer',
          ja: '改善点をお聞かせください',
          ko: '개선 사항을 알려주세요',
          'zh-Hant': '告訴我們如何改進',
        }),
      },
      offer: {
        title: t({
          en: 'Wait! Before you go...',
          'zh-Hans': '等等！在您离开之前...',
          fr: 'Attendez ! Avant de partir…',
          ja: 'お待ちください！キャンセル前に…',
          ko: '잠깐만요! 취소 전에…',
          'zh-Hant': '等等！在您離開之前…',
        }),
        description: t({
          en: 'Get 50% off your next 3 months',
          'zh-Hans': '享受接下来 3 个月 5 折优惠',
          fr: '50 % de réduction sur les 3 prochains mois',
          ja: '次の3ヶ月間50%オフ',
          ko: '다음 3개월 50% 할인',
          'zh-Hant': '接下來 3 個月享 5 折',
        }),
        acceptOffer: t({
          en: 'Keep my subscription',
          'zh-Hans': '保留我的订阅',
          fr: 'Garder mon abonnement',
          ja: 'サブスクリプションを継続',
          ko: '구독 유지',
          'zh-Hant': '保留我的訂閱',
        }),
        confirmCancel: t({
          en: 'Yes, cancel my subscription',
          'zh-Hans': '是的，取消我的订阅',
          fr: 'Oui, annuler mon abonnement',
          ja: 'はい、キャンセルします',
          ko: '예, 구독을 취소합니다',
          'zh-Hant': '是的，取消我的訂閱',
        }),
      },
    },
    success: {
      paymentAdded: t({
        en: 'Payment method added successfully',
        'zh-Hans': '付款方式添加成功',
        fr: 'Moyen de paiement ajouté',
        ja: '支払い方法を追加しました',
        ko: '결제 수단이 추가되었습니다',
        'zh-Hant': '付款方式新增成功',
      }),
      paymentRemoved: t({
        en: 'Payment method removed successfully',
        'zh-Hans': '付款方式移除成功',
        fr: 'Moyen de paiement supprimé',
        ja: '支払い方法を削除しました',
        ko: '결제 수단이 제거되었습니다',
        'zh-Hant': '付款方式已移除',
      }),
      subscriptionUpdated: t({
        en: 'Subscription updated successfully',
        'zh-Hans': '订阅更新成功',
        fr: 'Abonnement mis à jour',
        ja: 'サブスクリプションを更新しました',
        ko: '구독이 업데이트되었습니다',
        'zh-Hant': '訂閱已更新',
      }),
      subscriptionCanceled: t({
        en: 'Subscription canceled successfully',
        'zh-Hans': '订阅取消成功',
        fr: 'Abonnement annulé',
        ja: 'サブスクリプションをキャンセルしました',
        ko: '구독이 취소되었습니다',
        'zh-Hant': '訂閱已取消',
      }),
      subscriptionReactivated: t({
        en: 'Subscription reactivated successfully',
        'zh-Hans': '订阅重新激活成功',
        fr: 'Abonnement réactivé',
        ja: 'サブスクリプションを再開しました',
        ko: '구독이 재활성화되었습니다',
        'zh-Hant': '訂閱已重新啟用',
      }),
    },
    errors: {
      paymentFailed: t({
        en: 'Payment failed. Please try again.',
        'zh-Hans': '付款失败。请重试。',
        fr: 'Paiement échoué. Réessayez.',
        ja: '支払いに失敗しました。もう一度お試しください。',
        ko: '결제에 실패했습니다. 다시 시도하세요.',
        'zh-Hant': '付款失敗，請重試。',
      }),
      updateFailed: t({
        en: 'Failed to update subscription. Please contact support.',
        'zh-Hans': '订阅更新失败。请联系客服。',
        fr: 'Échec de la mise à jour. Contactez le support.',
        ja: 'サブスクリプションの更新に失敗しました。サポートにお問い合わせください。',
        ko: '구독 업데이트에 실패했습니다. 고객 지원에 문의하세요.',
        'zh-Hant': '訂閱更新失敗，請聯絡客服。',
      }),
      cancelFailed: t({
        en: 'Failed to cancel subscription. Please contact support.',
        'zh-Hans': '取消订阅失败。请联系客服。',
        fr: 'Échec de l\'annulation. Contactez le support.',
        ja: 'キャンセルに失敗しました。サポートにお問い合わせください。',
        ko: '구독 취소에 실패했습니다. 고객 지원에 문의하세요.',
        'zh-Hant': '取消訂閱失敗，請聯絡客服。',
      }),
    },
    modals: {
      addPaymentMethod: {
        title: t({
          en: 'Add Payment Method',
          'zh-Hans': '添加付款方式',
          fr: 'Ajouter un moyen de paiement',
          ja: '支払い方法を追加',
          ko: '결제 수단 추가',
          'zh-Hant': '新增付款方式',
        }),
        cardDetails: t({
          en: 'Card Details',
          'zh-Hans': '卡详情',
          fr: 'Détails de la carte',
          ja: 'カード情報',
          ko: '카드 정보',
          'zh-Hant': '卡片詳情',
        }),
        cardholderName: t({
          en: 'Cardholder Name',
          'zh-Hans': '持卡人姓名',
          fr: 'Nom du titulaire',
          ja: 'カード名義人',
          ko: '카드 소유자',
          'zh-Hant': '持卡人姓名',
        }),
        cardNumber: t({
          en: 'Card Number',
          'zh-Hans': '卡号',
          fr: 'Numéro de carte',
          ja: 'カード番号',
          ko: '카드 번호',
          'zh-Hant': '卡號',
        }),
        expiryDate: t({
          en: 'Expiry Date',
          'zh-Hans': '到期日期',
          fr: 'Date d\'expiration',
          ja: '有効期限',
          ko: '만료일',
          'zh-Hant': '到期日',
        }),
        cvv: t({
          en: 'CVV',
          'zh-Hans': 'CVV',
          fr: 'CVV',
          ja: 'CVV',
          ko: 'CVV',
          'zh-Hant': 'CVV',
        }),
        saveButton: t({
          en: 'Add Card',
          'zh-Hans': '添加卡',
          fr: 'Ajouter la carte',
          ja: 'カードを追加',
          ko: '카드 추가',
          'zh-Hant': '新增卡片',
        }),
      },
    },
  },
  key: 'billing',
} satisfies Dictionary;

export default billingContent;
