import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Kin interface content dictionary
 * Contains all text labels for the Kin Agent Chat interface
 */
const claudeChatContent = {
  content: {
    header: {
      title: t({
        en: 'Kin',
        'zh-Hans': 'Kin',
        fr: 'Kin',
        ja: 'Kin',
        ko: 'Kin',
        'zh-Hant': 'Kin',
      }),
      newChat: t({
        en: 'New Chat',
        'zh-Hans': '新建聊天',
        fr: 'Nouveau chat',
        ja: '新規チャット',
        ko: '새 채팅',
        'zh-Hant': '新建聊天',
      }),
      clearHistory: t({
        en: 'Clear History',
        'zh-Hans': '清除历史',
        fr: 'Effacer l\'historique',
        ja: '履歴をクリア',
        ko: '기록 지우기',
        'zh-Hant': '清除歷史',
      }),
    },
    sidebar: {
      sessions: t({
        en: 'Sessions',
        'zh-Hans': '会话',
        fr: 'Sessions',
        ja: 'セッション',
        ko: '세션',
        'zh-Hant': '會話',
      }),
      today: t({
        en: 'Today',
        'zh-Hans': '今天',
        fr: 'Aujourd\'hui',
        ja: '今日',
        ko: '오늘',
        'zh-Hant': '今天',
      }),
      yesterday: t({
        en: 'Yesterday',
        'zh-Hans': '昨天',
        fr: 'Hier',
        ja: '昨日',
        ko: '어제',
        'zh-Hant': '昨天',
      }),
      lastWeek: t({
        en: 'Last 7 Days',
        'zh-Hans': '过去 7 天',
        fr: '7 derniers jours',
        ja: '過去7日間',
        ko: '최근 7일',
        'zh-Hant': '過去 7 天',
      }),
      lastMonth: t({
        en: 'Last 30 Days',
        'zh-Hans': '过去 30 天',
        fr: '30 derniers jours',
        ja: '過去30日間',
        ko: '최근 30일',
        'zh-Hant': '過去 30 天',
      }),
      noSessions: t({
        en: 'No sessions yet',
        'zh-Hans': '暂无会话',
        fr: 'Aucune session',
        ja: 'セッションはまだありません',
        ko: '아직 세션이 없습니다',
        'zh-Hant': '暫無會話',
      }),
      expand: t({
        en: 'Expand session list',
        'zh-Hans': '展开会话列表',
        fr: 'Développer la liste',
        ja: 'セッション一覧を展開',
        ko: '세션 목록 펼치기',
        'zh-Hant': '展開會話列表',
      }),
      collapse: t({
        en: 'Collapse session list',
        'zh-Hans': '收起会话列表',
        fr: 'Réduire la liste',
        ja: 'セッション一覧を折りたたむ',
        ko: '세션 목록 접기',
        'zh-Hant': '收起會話列表',
      }),
    },
    chatInput: {
      placeholder: t({
        en: 'Send a message to Kin...',
        'zh-Hans': '向 Kin 发送消息...',
        fr: 'Envoyer un message à Kin...',
        ja: 'Kin にメッセージを送信...',
        ko: 'Kin에게 메시지 보내기...',
        'zh-Hant': '向 Kin 傳送訊息...',
      }),
      placeholderGreeting: t({
        en: 'How can I help you today?',
        'zh-Hans': '今天我能帮你什么？',
        fr: 'Comment puis-je vous aider ?',
        ja: '今日は何をお手伝いしましょうか？',
        ko: '오늘 무엇을 도와드릴까요?',
        'zh-Hant': '今天我能幫您什麼？',
      }),
      attachFile: t({
        en: 'Attach file',
        'zh-Hans': '附件',
        fr: 'Joindre un fichier',
        ja: 'ファイルを添付',
        ko: '파일 첨부',
        'zh-Hant': '附件',
      }),
      send: t({
        en: 'Send',
        'zh-Hans': '发送',
        fr: 'Envoyer',
        ja: '送信',
        ko: '보내기',
        'zh-Hant': '傳送',
      }),
      stop: t({
        en: 'Stop',
        'zh-Hans': '停止',
        fr: 'Arrêter',
        ja: '停止',
        ko: '중지',
        'zh-Hant': '停止',
      }),
    },
    message: {
      user: t({
        en: 'You',
        'zh-Hans': '你',
        fr: 'Vous',
        ja: 'あなた',
        ko: '사용자',
        'zh-Hant': '您',
      }),
      assistant: t({
        en: 'Kin',
        'zh-Hans': 'Kin',
        fr: 'Kin',
        ja: 'Kin',
        ko: 'Kin',
        'zh-Hant': 'Kin',
      }),
      copy: t({
        en: 'Copy',
        'zh-Hans': '复制',
        fr: 'Copier',
        ja: 'コピー',
        ko: '복사',
        'zh-Hant': '複製',
      }),
      copied: t({
        en: 'Copied!',
        'zh-Hans': '已复制！',
        fr: 'Copié !',
        ja: 'コピーしました！',
        ko: '복사됨!',
        'zh-Hant': '已複製！',
      }),
      regenerate: t({
        en: 'Regenerate',
        'zh-Hans': '重新生成',
        fr: 'Régénérer',
        ja: '再生成',
        ko: '다시 생성',
        'zh-Hant': '重新產生',
      }),
      delete: t({
        en: 'Delete',
        'zh-Hans': '删除',
        fr: 'Supprimer',
        ja: '削除',
        ko: '삭제',
        'zh-Hant': '刪除',
      }),
      copyCode: t({
        en: 'Copy code',
        'zh-Hans': '复制代码',
        fr: 'Copier le code',
        ja: 'コードをコピー',
        ko: '코드 복사',
        'zh-Hant': '複製程式碼',
      }),
      copyNew: t({
        en: 'Copy New',
        'zh-Hans': '复制新内容',
        fr: 'Copier le nouveau',
        ja: '新規をコピー',
        ko: '새 내용 복사',
        'zh-Hant': '複製新內容',
      }),
    },
    overlay: {
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
      copied: t({
        en: 'Copied',
        'zh-Hans': '已复制',
        fr: 'Copié',
        ja: 'コピーしました',
        ko: '복사됨',
        'zh-Hant': '已複製',
      }),
      copy: t({
        en: 'Copy',
        'zh-Hans': '复制',
        fr: 'Copier',
        ja: 'コピー',
        ko: '복사',
        'zh-Hant': '複製',
      }),
      command: t({
        en: 'Command',
        'zh-Hans': '命令',
        fr: 'Commande',
        ja: 'コマンド',
        ko: '명령',
        'zh-Hant': '命令',
      }),
      output: t({
        en: 'Output',
        'zh-Hans': '输出',
        fr: 'Sortie',
        ja: '出力',
        ko: '출력',
        'zh-Hant': '輸出',
      }),
    },
    workspacePanel: {
      title: t({
        en: 'Workspace',
        'zh-Hans': '工作区',
        fr: 'Espace de travail',
        ja: 'ワークスペース',
        ko: '작업 공간',
        'zh-Hant': '工作區',
      }),
      filesLabel: t({
        en: 'FILES',
        'zh-Hans': '文件',
        fr: 'FICHIERS',
        ja: 'ファイル',
        ko: '파일',
        'zh-Hant': '檔案',
      }),
      filesCount: t({
        en: '{count} files',
        'zh-Hans': '{count} 个文件',
        fr: '{count} fichier(s)',
        ja: '{count} ファイル',
        ko: '파일 {count}개',
        'zh-Hant': '{count} 個檔案',
      }),
      workspaceSkills: t({
        en: 'Workspace Skills',
        'zh-Hans': '工作区技能',
        fr: 'Skills de l\'espace',
        ja: 'ワークスペース Skills',
        ko: '작업 공간 Skills',
        'zh-Hant': '工作區技能',
      }),
      noSkillFound: t({
        en: 'No SKILL.md found',
        'zh-Hans': '未找到 SKILL.md',
        fr: 'SKILL.md introuvable',
        ja: 'SKILL.md が見つかりません',
        ko: 'SKILL.md를 찾을 수 없습니다',
        'zh-Hant': '未找到 SKILL.md',
      }),
      downloadWorkspace: t({
        en: 'Download workspace',
        'zh-Hans': '下载工作区',
        fr: 'Télécharger l\'espace',
        ja: 'ワークスペースをダウンロード',
        ko: '작업 공간 다운로드',
        'zh-Hant': '下載工作區',
      }),
      loadingWorkspace: t({
        en: 'Loading workspace...',
        'zh-Hans': '正在加载工作区...',
        fr: 'Chargement de l\'espace...',
        ja: 'ワークスペースを読み込み中...',
        ko: '작업 공간 로딩 중...',
        'zh-Hant': '正在載入工作區...',
      }),
      noFilesYet: t({
        en: 'No files in workspace yet. Start chatting to create files!',
        'zh-Hans': '工作区暂无文件，开始对话以创建文件！',
        fr: 'Aucun fichier. Commencez à discuter pour en créer.',
        ja: 'ワークスペースにファイルはまだありません。チャットでファイルを作成しましょう。',
        ko: '작업 공간에 아직 파일이 없습니다. 채팅을 시작해 파일을 만드세요.',
        'zh-Hant': '工作區暫無檔案，開始對話以建立檔案！',
      }),
    },
    contextBadges: {
      viewSkillsExample: t({
        en: 'View Skills examples',
        'zh-Hans': '查看 Skills 示例',
        fr: 'Voir les exemples Skills',
        ja: 'Skills の例を見る',
        ko: 'Skills 예제 보기',
        'zh-Hant': '查看 Skills 範例',
      }),
      openSkillsStore: t({
        en: 'Open Skills Store',
        'zh-Hans': '打开 Skills Store',
        fr: 'Ouvrir Skills Store',
        ja: 'Skills Store を開く',
        ko: 'Skills Store 열기',
        'zh-Hant': '開啟 Skills Store',
      }),
      currentSessionSkills: t({
        en: 'Skills available in this session',
        'zh-Hans': '当前会话可用 Skills',
        fr: 'Skills disponibles dans cette session',
        ja: 'このセッションで利用可能な Skills',
        ko: '이 세션에서 사용 가능한 Skills',
        'zh-Hant': '目前會話可用 Skills',
      }),
      moreSkills: t({
        en: 'More Skills',
        'zh-Hans': '更多 Skills',
        fr: 'Plus de Skills',
        ja: 'その他の Skills',
        ko: '더 많은 Skills',
        'zh-Hant': '更多 Skills',
      }),
      loadingExamples: t({
        en: 'Loading examples...',
        'zh-Hans': '正在加载示例...',
        fr: 'Chargement des exemples...',
        ja: '例を読み込み中...',
        ko: '예제 로딩 중...',
        'zh-Hant': '正在載入範例...',
      }),
      noSkillsEnabled: t({
        en: 'No Skills enabled',
        'zh-Hans': '暂无启用的 Skills',
        fr: 'Aucun Skill activé',
        ja: '有効な Skills はありません',
        ko: '활성화된 Skills 없음',
        'zh-Hant': '暫無啟用的 Skills',
      }),
      exampleIndex: t({
        en: 'Example {n}',
        'zh-Hans': '示例 {n}',
        fr: 'Exemple {n}',
        ja: '例 {n}',
        ko: '예제 {n}',
        'zh-Hant': '範例 {n}',
      }),
      noExamples: t({
        en: 'No examples',
        'zh-Hans': '暂无示例',
        fr: 'Aucun exemple',
        ja: '例はありません',
        ko: '예제 없음',
        'zh-Hant': '暫無範例',
      }),
    },
    sessionMenu: {
      rename: t({
        en: 'Rename',
        'zh-Hans': '重命名',
        fr: 'Renommer',
        ja: '名前を変更',
        ko: '이름 변경',
        'zh-Hant': '重新命名',
      }),
      delete: t({
        en: 'Delete',
        'zh-Hans': '删除',
        fr: 'Supprimer',
        ja: '削除',
        ko: '삭제',
        'zh-Hant': '刪除',
      }),
      export: t({
        en: 'Export',
        'zh-Hans': '导出',
        fr: 'Exporter',
        ja: 'エクスポート',
        ko: '내보내기',
        'zh-Hant': '匯出',
      }),
      share: t({
        en: 'Share',
        'zh-Hans': '分享',
        fr: 'Partager',
        ja: '共有',
        ko: '공유',
        'zh-Hant': '分享',
      }),
    },
    sessionSwitch: {
      title: t({
        en: 'Session In Progress',
        'zh-Hans': '会话进行中',
        fr: 'Session en cours',
        ja: 'セッション実行中',
        ko: '세션 진행 중',
        'zh-Hant': '會話進行中',
      }),
      message: t({
        en: 'A query is currently running. You can interrupt it to switch sessions, or cancel.',
        'zh-Hans': '当前有查询正在运行。你可以中断并切换，或取消。',
        fr: 'Une requête est en cours. Vous pouvez l’interrompre pour changer de session, ou annuler.',
        ja: 'クエリ実行中です。中断して切り替えるか、キャンセルできます。',
        ko: '쿼리가 실행 중입니다. 중단 후 전환하거나 취소할 수 있습니다.',
        'zh-Hant': '目前有查詢正在執行。你可以中斷並切換，或取消。',
      }),
      interrupt: t({
        en: 'Interrupt & Switch',
        'zh-Hans': '中断当前任务并切换',
        fr: 'Interrompre et changer',
        ja: '中断して切り替える',
        ko: '중단 후 전환',
        'zh-Hant': '中斷並切換',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
    },
    artifacts: {
      title: t({
        en: 'Artifacts',
        'zh-Hans': '成果物',
        fr: 'Artifacts',
        ja: 'Artifacts',
        ko: 'Artifacts',
        'zh-Hant': '成果物',
      }),
      noArtifacts: t({
        en: 'No artifacts generated yet',
        'zh-Hans': '尚未生成成果物',
        fr: 'Aucun artifact généré',
        ja: 'まだ Artifact は生成されていません',
        ko: '아직 생성된 artifact 없음',
        'zh-Hant': '尚未產生成果物',
      }),
      openPreview: t({
        en: 'Open Preview',
        'zh-Hans': '打开预览',
        fr: 'Ouvrir l\'aperçu',
        ja: 'プレビューを開く',
        ko: '미리보기 열기',
        'zh-Hant': '開啟預覽',
      }),
      openInNewTab: t({
        en: 'Open in New Tab',
        'zh-Hans': '在新标签页中打开',
        fr: 'Ouvrir dans un nouvel onglet',
        ja: '新しいタブで開く',
        ko: '새 탭에서 열기',
        'zh-Hant': '在新分頁中開啟',
      }),
      openArtifact: t({
        en: 'Open Artifact',
        'zh-Hans': '打开成果物',
        fr: 'Ouvrir l\'artifact',
        ja: '成果物を開く',
        ko: '아티팩트 열기',
        'zh-Hant': '開啟成果物',
      }),
      previewBadge: t({
        en: 'preview',
        'zh-Hans': '预览',
        fr: 'aperçu',
        ja: 'プレビュー',
        ko: '미리보기',
        'zh-Hant': '預覽',
      }),
      fallbackName: t({
        en: '{type} Artifact',
        'zh-Hans': '{type} 成果物',
        fr: 'Artifact {type}',
        ja: '{type} 成果物',
        ko: '{type} 아티팩트',
        'zh-Hant': '{type} 成果物',
      }),
      typeLabels: {
        html: t({
          en: 'HTML',
          'zh-Hans': 'HTML',
          fr: 'HTML',
          ja: 'HTML',
          ko: 'HTML',
          'zh-Hant': 'HTML',
        }),
        svg: t({
          en: 'SVG',
          'zh-Hans': 'SVG',
          fr: 'SVG',
          ja: 'SVG',
          ko: 'SVG',
          'zh-Hant': 'SVG',
        }),
        markdown: t({
          en: 'Markdown',
          'zh-Hans': 'Markdown',
          fr: 'Markdown',
          ja: 'Markdown',
          ko: 'Markdown',
          'zh-Hant': 'Markdown',
        }),
        react: t({
          en: 'React',
          'zh-Hans': 'React',
          fr: 'React',
          ja: 'React',
          ko: 'React',
          'zh-Hant': 'React',
        }),
        image: t({
          en: 'Image',
          'zh-Hans': '图片',
          fr: 'Image',
          ja: '画像',
          ko: '이미지',
          'zh-Hant': '圖片',
        }),
        json: t({
          en: 'JSON',
          'zh-Hans': 'JSON',
          fr: 'JSON',
          ja: 'JSON',
          ko: 'JSON',
          'zh-Hant': 'JSON',
        }),
        csv: t({
          en: 'CSV',
          'zh-Hans': 'CSV',
          fr: 'CSV',
          ja: 'CSV',
          ko: 'CSV',
          'zh-Hant': 'CSV',
        }),
      },
    },
    tools: {
      title: t({
        en: 'Tools',
        'zh-Hans': '工具',
        fr: 'Outils',
        ja: 'ツール',
        ko: '도구',
        'zh-Hant': '工具',
      }),
      running: t({
        en: 'Running',
        'zh-Hans': '运行中',
        fr: 'En cours',
        ja: '実行中',
        ko: '실행 중',
        'zh-Hant': '執行中',
      }),
      completed: t({
        en: 'Completed',
        'zh-Hans': '已完成',
        fr: 'Terminé',
        ja: '完了',
        ko: '완료',
        'zh-Hant': '已完成',
      }),
      failed: t({
        en: 'Failed',
        'zh-Hans': '失败',
        fr: 'Échec',
        ja: '失敗',
        ko: '실패',
        'zh-Hant': '失敗',
      }),
      viewDetails: t({
        en: 'View Details',
        'zh-Hans': '查看详情',
        fr: 'Voir les détails',
        ja: '詳細を見る',
        ko: '상세 보기',
        'zh-Hant': '查看詳情',
      }),
    },
    buttons: {
      loading: t({
        en: 'Creating...',
        'zh-Hans': '创建中...',
        fr: 'Création...',
        ja: '作成中...',
        ko: '생성 중...',
        'zh-Hant': '建立中...',
      }),
    },
    actions: {
      viewStats: t({
        en: 'View statistics',
        'zh-Hans': '查看统计信息',
        fr: 'Voir les statistiques',
        ja: '統計を見る',
        ko: '통계 보기',
        'zh-Hant': '查看統計資訊',
      }),
      helpful: t({
        en: 'Helpful',
        'zh-Hans': '有帮助',
        fr: 'Utile',
        ja: '役に立った',
        ko: '도움이 됨',
        'zh-Hant': '有幫助',
      }),
      notHelpful: t({
        en: 'Not helpful',
        'zh-Hans': '没帮助',
        fr: 'Pas utile',
        ja: '役に立たなかった',
        ko: '도움이 안 됨',
        'zh-Hant': '沒幫助',
      }),
      viewFileChanges: t({
        en: 'View all {count} file changes',
        'zh-Hans': '查看全部 {count} 个文件变更',
        fr: 'Voir les {count} modifications',
        ja: '{count} 件のファイル変更を見る',
        ko: '{count}개 파일 변경 보기',
        'zh-Hant': '查看全部 {count} 個檔案變更',
      }),
    },
    status: {
      connecting: t({
        en: 'Connecting to Kin...',
        'zh-Hans': '正在连接 Kin...',
        fr: 'Connexion à Kin...',
        ja: 'Kin に接続中...',
        ko: 'Kin 연결 중...',
        'zh-Hant': '正在連線 Kin...',
      }),
      connected: t({
        en: 'Connected',
        'zh-Hans': '已连接',
        fr: 'Connecté',
        ja: '接続済み',
        ko: '연결됨',
        'zh-Hant': '已連線',
      }),
      disconnected: t({
        en: 'Disconnected',
        'zh-Hans': '已断开',
        fr: 'Déconnecté',
        ja: '切断されました',
        ko: '연결 끊김',
        'zh-Hant': '已斷線',
      }),
      reconnecting: t({
        en: 'Reconnecting...',
        'zh-Hans': '正在重新连接...',
        fr: 'Reconnexion...',
        ja: '再接続中...',
        ko: '재연결 중...',
        'zh-Hant': '正在重新連線...',
      }),
      error: t({
        en: 'Connection Error',
        'zh-Hans': '连接错误',
        fr: 'Erreur de connexion',
        ja: '接続エラー',
        ko: '연결 오류',
        'zh-Hant': '連線錯誤',
      }),
      initializing: t({
        en: 'Initializing session',
        'zh-Hans': '正在初始化会话',
        fr: 'Initialisation de la session',
        ja: 'セッションを初期化中',
        ko: '세션 초기화 중',
        'zh-Hant': '正在初始化會話',
      }),
      pleaseWait: t({
        en: 'Setting up your Kin environment...',
        'zh-Hans': '正在配置 Kin 环境...',
        fr: 'Configuration de l\'environnement Kin...',
        ja: 'Kin 環境を設定中...',
        ko: 'Kin 환경 설정 중...',
        'zh-Hant': '正在設定 Kin 環境...',
      }),
      escInterrupt: t({
        en: 'Press Esc again to interrupt Kin',
        'zh-Hans': '再次按 Esc 键中断 Kin',
        fr: 'Appuyez à nouveau sur Échap pour interrompre',
        ja: 'Esc をもう一度押して Kin を中断',
        ko: 'Esc를 다시 눌러 Kin 중단',
        'zh-Hant': '再次按 Esc 鍵中斷 Kin',
      }),
      stopEsc: t({
        en: 'Stop (Esc)',
        'zh-Hans': '停止生成 (Esc)',
        fr: 'Arrêter (Échap)',
        ja: '停止 (Esc)',
        ko: '중지 (Esc)',
        'zh-Hant': '停止產生 (Esc)',
      }),
      stop: t({
        en: 'Stop',
        'zh-Hans': '停止',
        fr: 'Arrêter',
        ja: '停止',
        ko: '중지',
        'zh-Hant': '停止',
      }),
    },
    errors: {
      notConnected: t({
        en: 'Not connected to Kin. Please wait or refresh.',
        'zh-Hans': '未连接到 Kin。请等待或刷新页面。',
        fr: 'Non connecté à Kin. Veuillez patienter ou actualiser.',
        ja: 'Kin に接続されていません。待つかページを更新してください。',
        ko: 'Kin에 연결되지 않았습니다. 잠시 기다리거나 새로고침하세요.',
        'zh-Hant': '未連線至 Kin。請等待或重新整理頁面。',
      }),
      messageFailed: t({
        en: 'Failed to send message. Please try again.',
        'zh-Hans': '发送消息失败。请重试。',
        fr: 'Échec de l\'envoi. Veuillez réessayer.',
        ja: 'メッセージ送信に失敗しました。再試行してください。',
        ko: '메시지 전송 실패. 다시 시도해 주세요.',
        'zh-Hant': '傳送訊息失敗。請重試。',
      }),
      sessionNotFound: t({
        en: 'Session not found. It may have been deleted.',
        'zh-Hans': '未找到会话。可能已被删除。',
        fr: 'Session introuvable. Elle a peut-être été supprimée.',
        ja: 'セッションが見つかりません。削除された可能性があります。',
        ko: '세션을 찾을 수 없습니다. 삭제되었을 수 있습니다.',
        'zh-Hant': '未找到會話。可能已被刪除。',
      }),
      quotaExceeded: t({
        en: 'Quota exceeded. Please upgrade your plan.',
        'zh-Hans': '配额已用完。请升级您的计划。',
        fr: 'Quota dépassé. Veuillez upgrader votre plan.',
        ja: 'クォータ超過です。プランのアップグレードをご検討ください。',
        ko: '할당량 초과. 플랜 업그레이드를 고려해 주세요.',
        'zh-Hant': '配額已用完。請升級您的方案。',
      }),
      noSession: t({
        en: 'Please create a session first to view files',
        'zh-Hans': '请先创建会话后再查看文件',
        fr: 'Créez d\'abord une session pour voir les fichiers',
        ja: 'ファイルを見るには先にセッションを作成してください',
        ko: '파일을 보려면 먼저 세션을 생성해 주세요',
        'zh-Hant': '請先建立會話後再查看檔案',
      }),
      fileNotFound: t({
        en: 'File not found: {path}',
        'zh-Hans': '文件未找到：{path}',
        fr: 'Fichier introuvable : {path}',
        ja: 'ファイルが見つかりません：{path}',
        ko: '파일을 찾을 수 없습니다: {path}',
        'zh-Hant': '檔案未找到：{path}',
      }),
      readFailed: t({
        en: 'Failed to read file',
        'zh-Hans': '读取文件失败',
        fr: 'Échec de lecture du fichier',
        ja: 'ファイルの読み込みに失敗しました',
        ko: '파일 읽기 실패',
        'zh-Hant': '讀取檔案失敗',
      }),
    },
    auth: {
      checkingSession: t({
        en: 'Checking your session...',
        'zh-Hans': '正在验证会话...',
        fr: 'Vérification de votre session...',
        ja: 'セッションを確認中...',
        ko: '세션 확인 중...',
        'zh-Hant': '正在驗證會話...',
      }),
    },
    disclaimer: t({
      en: 'Kin can make mistakes. Please double-check responses.',
      'zh-Hans': 'Kin 可能会出错，请仔细核对回复内容。',
      fr: 'Kin peut se tromper. Vérifiez les réponses.',
      ja: 'Kin は誤りを犯すことがあります。回答はご確認ください。',
      ko: 'Kin가 실수할 수 있습니다. 응답을 꼭 확인하세요.',
      'zh-Hant': 'Kin 可能會出錯，請仔細核對回覆內容。',
    }),
    emptyState: {
      title: t({
        en: 'Start a conversation with Kin',
        'zh-Hans': '开始与 Kin 对话',
        fr: 'Commencez une conversation avec Kin',
        ja: 'Kin と会話を始めましょう',
        ko: 'Kin와 대화를 시작하세요',
        'zh-Hant': '開始與 Kin 對話',
      }),
      subtitle: t({
        en: 'Kin can help you with coding, writing, analysis, and more.',
        'zh-Hans': 'Kin 可以帮助您进行编码、写作、分析等。',
        fr: 'Kin vous aide pour le code, l\'écriture, l\'analyse et plus.',
        ja: 'Kin はコーディング、執筆、分析などでお手伝いします。',
        ko: 'Kin가 코딩, 글쓰기, 분석 등으로 도와드립니다.',
        'zh-Hant': 'Kin 可以協助您編碼、寫作、分析等。',
      }),
      startChat: t({
        en: 'Start New Session',
        'zh-Hans': '新建会话',
        fr: 'Nouvelle session',
        ja: '新規セッション',
        ko: '새 세션 시작',
        'zh-Hant': '新建會話',
      }),
      suggestions: {
        coding: t({
          en: 'Help me write a function to',
          'zh-Hans': '帮我写一个函数来',
          fr: 'Aide-moi à écrire une fonction pour',
          ja: '〜の関数を書くのを手伝って',
          ko: '다음 기능을 하는 함수 작성 도와줘',
          'zh-Hant': '幫我寫一個函式來',
        }),
        writing: t({
          en: 'Draft an email about',
          'zh-Hans': '起草一封关于...的邮件',
          fr: 'Rédige un e-mail sur',
          ja: '〜についてメールの下書きを',
          ko: '~에 대한 이메일 초안 작성',
          'zh-Hant': '起草一封關於...的郵件',
        }),
        analysis: t({
          en: 'Analyze this data and',
          'zh-Hans': '分析这些数据并',
          fr: 'Analyse ces données et',
          ja: 'このデータを分析して',
          ko: '이 데이터를 분석하고',
          'zh-Hant': '分析這些資料並',
        }),
        creative: t({
          en: 'Brainstorm ideas for',
          'zh-Hans': '为...进行头脑风暴',
          fr: 'Brainstorm des idées pour',
          ja: '〜のアイデアをブレインストーム',
          ko: '~에 대한 아이디어 브레인스토밍',
          'zh-Hant': '為...進行腦力激盪',
        }),
      },
    },

    // Session List Component
    sessionList: {
      newChat: t({
        en: 'New Chat',
        'zh-Hans': '新建聊天',
        fr: 'Nouveau chat',
        ja: '新規チャット',
        ko: '새 채팅',
        'zh-Hant': '新建聊天',
      }),
      loading: t({
        en: 'Loading sessions...',
        'zh-Hans': '加载会话中...',
        fr: 'Chargement des sessions...',
        ja: 'セッションを読み込み中...',
        ko: '세션 로딩 중...',
        'zh-Hant': '載入會話中...',
      }),
      loadError: t({
        en: 'Failed to load sessions',
        'zh-Hans': '加载会话失败',
        fr: 'Échec du chargement des sessions',
        ja: 'セッションの読み込みに失敗しました',
        ko: '세션 로드 실패',
        'zh-Hant': '載入會話失敗',
      }),
      noConversations: t({
        en: 'No conversations yet',
        'zh-Hans': '暂无对话',
        fr: 'Aucune conversation',
        ja: 'まだ会話はありません',
        ko: '아직 대화가 없습니다',
        'zh-Hant': '暫無對話',
      }),
      startNewChat: t({
        en: 'Start a new chat to begin',
        'zh-Hans': '点击上方按钮开始新对话',
        fr: 'Cliquez ci-dessus pour commencer',
        ja: '上のボタンで新規会話を開始',
        ko: '위 버튼을 눌러 새 대화 시작',
        'zh-Hant': '點擊上方按鈕開始新對話',
      }),
      conversations: t({
        en: '{count} conversation',
        'zh-Hans': '{count} 个对话',
        fr: '{count} conversation(s)',
        ja: '{count} 件の会話',
        ko: '대화 {count}개',
        'zh-Hant': '{count} 個對話',
      }),
    },

    sessionItem: {
      editTitle: t({
        en: 'Edit title',
        'zh-Hans': '编辑标题',
        fr: 'Modifier le titre',
        ja: 'タイトルを編集',
        ko: '제목 편집',
        'zh-Hant': '編輯標題',
      }),
      deleteConversation: t({
        en: 'Delete conversation',
        'zh-Hans': '删除对话',
        fr: 'Supprimer la conversation',
        ja: '会話を削除',
        ko: '대화 삭제',
        'zh-Hant': '刪除對話',
      }),
      newChat: t({
        en: 'New Chat',
        'zh-Hans': '新建聊天',
        fr: 'Nouveau chat',
        ja: '新規チャット',
        ko: '새 채팅',
        'zh-Hant': '新建聊天',
      }),
    },

    // Artifacts Panel Component
    artifactsPanel: {
      title: t({
        en: 'Artifact',
        'zh-Hans': '成果物',
        fr: 'Artifact',
        ja: 'Artifact',
        ko: 'Artifact',
        'zh-Hant': '成果物',
      }),
      preview: t({
        en: '(preview)',
        'zh-Hans': '(预览)',
        fr: '(aperçu)',
        ja: '(プレビュー)',
        ko: '(미리보기)',
        'zh-Hant': '(預覽)',
      }),
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
      skillActions: t({
        en: 'Skill actions',
        'zh-Hans': '技能操作',
        fr: 'Actions Skill',
        ja: 'スキル操作',
        ko: '스킬 작업',
        'zh-Hant': '技能操作',
      }),
      downloadSkill: t({
        en: 'Download .skill',
        'zh-Hans': '下载 .skill',
        fr: 'Télécharger .skill',
        ja: '.skill をダウンロード',
        ko: '.skill 다운로드',
        'zh-Hant': '下載 .skill',
      }),
      importToSkills: t({
        en: 'Import to Skills',
        'zh-Hans': '导入到技能',
        fr: 'Importer vers Skills',
        ja: 'Skills にインポート',
        ko: 'Skills로 가져오기',
        'zh-Hant': '匯入到技能',
      }),
      downloadArtifact: t({
        en: 'Download artifact',
        'zh-Hans': '下载成果物',
        fr: 'Télécharger l\'artifact',
        ja: 'Artifact をダウンロード',
        ko: 'artifact 다운로드',
        'zh-Hant': '下載成果物',
      }),
      downloadHtml: t({
        en: 'Download HTML',
        'zh-Hans': '下载 HTML',
        fr: 'Télécharger HTML',
        ja: 'HTML をダウンロード',
        ko: 'HTML 다운로드',
        'zh-Hant': '下載 HTML',
      }),
      exportPng: t({
        en: 'Export PNG',
        'zh-Hans': '导出 PNG',
        fr: 'Exporter PNG',
        ja: 'PNG をエクスポート',
        ko: 'PNG 내보내기',
        'zh-Hant': '匯出 PNG',
      }),
      source: t({
        en: 'Source: {tool}',
        'zh-Hans': '来源：{tool}',
        fr: 'Source : {tool}',
        ja: 'ソース：{tool}',
        ko: '출처: {tool}',
        'zh-Hant': '來源：{tool}',
      }),
      updated: t({
        en: 'Updated: {time}',
        'zh-Hans': '更新：{time}',
        fr: 'Mis à jour : {time}',
        ja: '更新：{time}',
        ko: '업데이트: {time}',
        'zh-Hant': '更新：{time}',
      }),
      file: t({
        en: 'File: {name}',
        'zh-Hans': '文件：{name}',
        fr: 'Fichier : {name}',
        ja: 'ファイル：{name}',
        ko: '파일: {name}',
        'zh-Hant': '檔案：{name}',
      }),
      type: t({
        en: 'Type: {type}',
        'zh-Hans': '类型：{type}',
        fr: 'Type : {type}',
        ja: 'タイプ：{type}',
        ko: '유형: {type}',
        'zh-Hant': '類型：{type}',
      }),
      typeLabel: {
        html: t({
          en: 'HTML',
          'zh-Hans': 'HTML',
          fr: 'HTML',
          ja: 'HTML',
          ko: 'HTML',
          'zh-Hant': 'HTML',
        }),
        svg: t({
          en: 'SVG',
          'zh-Hans': 'SVG',
          fr: 'SVG',
          ja: 'SVG',
          ko: 'SVG',
          'zh-Hant': 'SVG',
        }),
        markdown: t({
          en: 'Markdown',
          'zh-Hans': 'Markdown',
          fr: 'Markdown',
          ja: 'Markdown',
          ko: 'Markdown',
          'zh-Hant': 'Markdown',
        }),
        react: t({
          en: 'React',
          'zh-Hans': 'React',
          fr: 'React',
          ja: 'React',
          ko: 'React',
          'zh-Hant': 'React',
        }),
        image: t({
          en: 'Image',
          'zh-Hans': '图片',
          fr: 'Image',
          ja: '画像',
          ko: '이미지',
          'zh-Hant': '圖片',
        }),
        json: t({
          en: 'JSON',
          'zh-Hans': 'JSON',
          fr: 'JSON',
          ja: 'JSON',
          ko: 'JSON',
          'zh-Hant': 'JSON',
        }),
        csv: t({
          en: 'CSV',
          'zh-Hans': 'CSV',
          fr: 'CSV',
          ja: 'CSV',
          ko: 'CSV',
          'zh-Hant': 'CSV',
        }),
      },
      typeTitle: {
        html: t({
          en: 'HTML Preview',
          'zh-Hans': 'HTML 预览',
          fr: 'Aperçu HTML',
          ja: 'HTML プレビュー',
          ko: 'HTML 미리보기',
          'zh-Hant': 'HTML 預覽',
        }),
        svg: t({
          en: 'SVG Graphic',
          'zh-Hans': 'SVG 图形',
          fr: 'Graphique SVG',
          ja: 'SVG グラフィック',
          ko: 'SVG 그래픽',
          'zh-Hant': 'SVG 圖形',
        }),
        markdown: t({
          en: 'Markdown Document',
          'zh-Hans': 'Markdown 文档',
          fr: 'Document Markdown',
          ja: 'Markdown ドキュメント',
          ko: 'Markdown 문서',
          'zh-Hant': 'Markdown 文件',
        }),
        react: t({
          en: 'React Component',
          'zh-Hans': 'React 组件',
          fr: 'Composant React',
          ja: 'React コンポーネント',
          ko: 'React 컴포넌트',
          'zh-Hant': 'React 元件',
        }),
        image: t({
          en: 'Image',
          'zh-Hans': '图片',
          fr: 'Image',
          ja: '画像',
          ko: '이미지',
          'zh-Hant': '圖片',
        }),
        json: t({
          en: 'JSON Data',
          'zh-Hans': 'JSON 数据',
          fr: 'Données JSON',
          ja: 'JSON データ',
          ko: 'JSON 데이터',
          'zh-Hant': 'JSON 資料',
        }),
        csv: t({
          en: 'CSV Table',
          'zh-Hans': 'CSV 表格',
          fr: 'Tableau CSV',
          ja: 'CSV 表',
          ko: 'CSV 표',
          'zh-Hant': 'CSV 表格',
        }),
      },
      toast: {
        sessionUnavailable: t({
          en: 'Current session unavailable, cannot read skill files',
          'zh-Hans': '当前会话不可用，无法读取技能文件',
          fr: 'Session indisponible, impossible de lire les fichiers skill',
          ja: '現在のセッションは利用不可、スキルファイルを読み込めません',
          ko: '현재 세션을 사용할 수 없어 스킬 파일을 읽을 수 없습니다',
          'zh-Hant': '目前會話不可用，無法讀取技能檔案',
        }),
        pngExportUnavailable: t({
          en: 'Artifact preview not ready, please retry',
          'zh-Hans': '预览未就绪，请稍后重试',
          fr: 'Aperçu indisponible, réessayez',
          ja: 'プレビューが未準備です。再試行してください',
          ko: '미리보기가 준비되지 않았습니다. 다시 시도하세요',
          'zh-Hant': '預覽未就緒，請稍後重試',
        }),
        pngExportSuccess: t({
          en: 'PNG exported',
          'zh-Hans': 'PNG 导出成功',
          fr: 'PNG exporté',
          ja: 'PNG をエクスポートしました',
          ko: 'PNG 내보내기 완료',
          'zh-Hant': 'PNG 匯出成功',
        }),
        pngExportFailed: t({
          en: 'PNG export failed',
          'zh-Hans': 'PNG 导出失败',
          fr: 'Échec de l’export PNG',
          ja: 'PNG のエクスポートに失敗しました',
          ko: 'PNG 내보내기 실패',
          'zh-Hant': 'PNG 匯出失敗',
        }),
        workspaceUnavailable: t({
          en: 'Workspace unavailable, only SKILL.md packaged',
          'zh-Hans': '工作区不可用，已仅打包 SKILL.md',
          fr: 'Espace indisponible, seul SKILL.md a été empaqueté',
          ja: 'ワークスペース利用不可、SKILL.md のみパッケージ済み',
          ko: '작업 공간 사용 불가, SKILL.md만 패키징됨',
          'zh-Hant': '工作區不可用，已僅打包 SKILL.md',
        }),
        noFilesFound: t({
          en: 'No workspace files found, only SKILL.md packaged',
          'zh-Hans': '未找到工作区文件，已仅打包 SKILL.md',
          fr: 'Aucun fichier trouvé, seul SKILL.md empaqueté',
          ja: 'ワークスペースにファイルなし、SKILL.md のみパッケージ済み',
          ko: '작업 공간 파일 없음, SKILL.md만 패키징됨',
          'zh-Hant': '未找到工作區檔案，已僅打包 SKILL.md',
        }),
        noSkillFiles: t({
          en: 'No skill files found to package',
          'zh-Hans': '未找到可打包的技能文件',
          fr: 'Aucun fichier skill à empaqueter',
          ja: 'パッケージするスキルファイルが見つかりません',
          ko: '패키징할 스킬 파일 없음',
          'zh-Hant': '未找到可打包的技能檔案',
        }),
        tooManyFiles: t({
          en: 'File count exceeds limit (max 100 files)',
          'zh-Hans': '文件数量超过限制（最多 100 个文件）',
          fr: 'Nombre de fichiers dépassé (max 100)',
          ja: 'ファイル数が上限超過（最大100件）',
          ko: '파일 수 제한 초과(최대 100개)',
          'zh-Hant': '檔案數量超過限制（最多 100 個檔案）',
        }),
        sizeLimitExceeded: t({
          en: 'Skill package size exceeds 10 MB limit',
          'zh-Hans': '技能包大小超过 10 MB 限制',
          fr: 'Taille du package skill > 10 Mo',
          ja: 'スキルパッケージが 10 MB 制限を超過',
          ko: '스킬 패키지 크기가 10 MB 제한 초과',
          'zh-Hant': '技能包大小超過 10 MB 限制',
        }),
        exportSuccess: t({
          en: 'Exported {name}.skill',
          'zh-Hans': '已导出 {name}.skill',
          fr: 'Exporté {name}.skill',
          ja: '{name}.skill をエクスポートしました',
          ko: '{name}.skill 내보냄',
          'zh-Hant': '已匯出 {name}.skill',
        }),
        exportFailed: t({
          en: 'Failed to package skill',
          'zh-Hans': '技能打包失败',
          fr: 'Échec du packaging du skill',
          ja: 'スキルのパッケージに失敗しました',
          ko: '스킬 패키징 실패',
          'zh-Hant': '技能打包失敗',
        }),
        importSuccess: t({
          en: 'Imported skill: {name}',
          'zh-Hans': '已导入技能：{name}',
          fr: 'Skill importé : {name}',
          ja: 'スキルをインポートしました：{name}',
          ko: '스킬 가져옴: {name}',
          'zh-Hant': '已匯入技能：{name}',
        }),
        importFailed: t({
          en: 'Failed to import skill',
          'zh-Hans': '技能导入失败',
          fr: 'Échec de l\'import du skill',
          ja: 'スキルのインポートに失敗しました',
          ko: '스킬 가져오기 실패',
          'zh-Hant': '技能匯入失敗',
        }),
      },
    },

    // Knowledge Base Panel Component
    knowledgeBase: {
      description: t({
        en: 'Select documents from the library to add to the current session. Kin can use grep/read tools to search and reference these documents.',
        'zh-Hans': '从文档库中选择文档添加到当前会话，Kin 可以使用 grep/read 工具搜索和引用这些文档。',
        fr: 'Sélectionnez des documents de la bibliothèque pour les ajouter à la session. Kin peut les rechercher et les référencer via grep/read.',
        ja: 'ライブラリからドキュメントを選んで現在のセッションに追加。Kin は grep/read で検索・参照できます。',
        ko: '라이브러리에서 문서를 선택해 현재 세션에 추가하세요. Kin가 grep/read로 검색·참조할 수 있습니다.',
        'zh-Hant': '從文件庫選擇文件加入目前會話，Kin 可使用 grep/read 工具搜尋與引用這些文件。',
      }),
      addDocuments: t({
        en: 'Add Documents',
        'zh-Hans': '添加文档',
        fr: 'Ajouter des documents',
        ja: 'ドキュメントを追加',
        ko: '문서 추가',
        'zh-Hant': '新增文件',
      }),
      addKb: t({
        en: 'Add KB',
        'zh-Hans': '添加 KB',
        fr: 'Ajouter KB',
        ja: 'KB を追加',
        ko: 'KB 추가',
        'zh-Hant': '新增 KB',
      }),
      loading: t({
        en: 'Loading documents...',
        'zh-Hans': '加载文档中...',
        fr: 'Chargement des documents...',
        ja: 'ドキュメントを読み込み中...',
        ko: '문서 로딩 중...',
        'zh-Hant': '載入文件中...',
      }),
      loadFailed: t({
        en: 'Failed to load',
        'zh-Hans': '加载失败',
        fr: 'Échec du chargement',
        ja: '読み込みに失敗しました',
        ko: '로드 실패',
        'zh-Hant': '載入失敗',
      }),
      noDocuments: t({
        en: 'No documents yet',
        'zh-Hans': '暂无文档',
        fr: 'Aucun document',
        ja: 'まだドキュメントはありません',
        ko: '아직 문서 없음',
        'zh-Hant': '暫無文件',
      }),
      clickToAdd: t({
        en: 'Click buttons above to add documents',
        'zh-Hans': '点击上方按钮添加文档',
        fr: 'Cliquez ci-dessus pour ajouter des documents',
        ja: '上のボタンでドキュメントを追加',
        ko: '위 버튼을 눌러 문서 추가',
        'zh-Hant': '點擊上方按鈕新增文件',
      }),
      added: t({
        en: '{count} documents added',
        'zh-Hans': '已添加 {count} 个文档',
        fr: '{count} document(s) ajouté(s)',
        ja: '{count} 件のドキュメントを追加しました',
        ko: '문서 {count}개 추가됨',
        'zh-Hant': '已新增 {count} 個文件',
      }),
      sync: t({
        en: 'Resync',
        'zh-Hans': '重新同步',
        fr: 'Resynchroniser',
        ja: '再同期',
        ko: '다시 동기화',
        'zh-Hant': '重新同步',
      }),
      remove: t({
        en: 'Remove',
        'zh-Hans': '移除',
        fr: 'Retirer',
        ja: '削除',
        ko: '제거',
        'zh-Hant': '移除',
      }),
      syncedAt: t({
        en: 'Synced {time}',
        'zh-Hans': '同步于 {time}',
        fr: 'Synchronisé {time}',
        ja: '同期：{time}',
        ko: '동기화: {time}',
        'zh-Hant': '同步於 {time}',
      }),
      timeJustNow: t({
        en: 'Just now',
        'zh-Hans': '刚刚',
        fr: 'À l\'instant',
        ja: 'たった今',
        ko: '방금',
        'zh-Hant': '剛剛',
      }),
      timeMinutesAgo: t({
        en: '{count}m ago',
        'zh-Hans': '{count}分钟前',
        fr: 'Il y a {count} min',
        ja: '{count}分前',
        ko: '{count}분 전',
        'zh-Hant': '{count} 分鐘前',
      }),
      timeHoursAgo: t({
        en: '{count}h ago',
        'zh-Hans': '{count}小时前',
        fr: 'Il y a {count} h',
        ja: '{count}時間前',
        ko: '{count}시간 전',
        'zh-Hant': '{count} 小時前',
      }),
      timeYesterday: t({
        en: 'Yesterday',
        'zh-Hans': '昨天',
        fr: 'Hier',
        ja: '昨日',
        ko: '어제',
        'zh-Hant': '昨天',
      }),
      timeDaysAgo: t({
        en: '{count}d ago',
        'zh-Hans': '{count}天前',
        fr: 'Il y a {count} j',
        ja: '{count}日前',
        ko: '{count}일 전',
        'zh-Hant': '{count} 天前',
      }),
      syncUnchanged: t({
        en: '"{name}" file unchanged, no need to sync',
        'zh-Hans': '"{name}" 文件未修改，无需同步',
        fr: '"{name}" inchangé, pas besoin de sync',
        ja: '"{name}" は変更なし、同期不要',
        ko: '"{name}" 변경 없음, 동기화 불필요',
        'zh-Hant': '"{name}" 檔案未修改，無需同步',
      }),
      syncSuccess: t({
        en: '"{name}" synced successfully!',
        'zh-Hans': '"{name}" 同步成功！',
        fr: '"{name}" synchronisé avec succès !',
        ja: '"{name}" の同期に成功しました！',
        ko: '"{name}" 동기화 성공!',
        'zh-Hant': '"{name}" 同步成功！',
      }),
      syncFailed: t({
        en: 'Sync failed, please try again',
        'zh-Hans': '同步失败，请重试',
        fr: 'Échec de la synchronisation, réessayez',
        ja: '同期に失敗しました。再試行してください',
        ko: '동기화 실패, 다시 시도해 주세요',
        'zh-Hant': '同步失敗，請重試',
      }),
      removeConfirm: t({
        en: 'Are you sure you want to remove "{name}" from the knowledge base?\n\nThe file will not be deleted from the library.',
        'zh-Hans': '确定要从知识库中移除 "{name}"？\n\n文件不会从文档库中删除。',
        fr: 'Retirer "{name}" de la base de connaissances ?\n\nLe fichier ne sera pas supprimé de la bibliothèque.',
        ja: 'ナレッジベースから "{name}" を削除しますか？\n\nライブラリからは削除されません。',
        ko: '"{name}"을(를) 지식베이스에서 제거할까요?\n\n라이브러리에서는 삭제되지 않습니다.',
        'zh-Hant': '確定要從知識庫中移除 "{name}"？\n\n檔案不會從文件庫中刪除。',
      }),
      removeFailed: t({
        en: 'Failed to remove, please try again',
        'zh-Hans': '移除失败，请重试',
        fr: 'Échec de la suppression, réessayez',
        ja: '削除に失敗しました。再試行してください',
        ko: '제거 실패, 다시 시도해 주세요',
        'zh-Hant': '移除失敗，請重試',
      }),
      addKbTitle: t({
        en: 'Add Knowledge Base',
        'zh-Hans': '添加 Knowledge Base',
        fr: 'Ajouter une base de connaissances',
        ja: 'Knowledge Base を追加',
        ko: 'Knowledge Base 추가',
        'zh-Hant': '新增 Knowledge Base',
      }),
      addKbDescription: t({
        en: 'Select a Knowledge Base, all documents will be automatically added to the current session.',
        'zh-Hans': '选择一个 Knowledge Base，所有文档将自动添加到当前会话。',
        fr: 'Choisissez une base de connaissances, tous les documents seront ajoutés à la session.',
        ja: 'Knowledge Base を選択すると、全ドキュメントが現在のセッションに自動追加されます。',
        ko: 'Knowledge Base를 선택하면 모든 문서가 현재 세션에 자동 추가됩니다.',
        'zh-Hant': '選擇一個 Knowledge Base，所有文件將自動加入目前會話。',
      }),
      noKb: t({
        en: 'No Knowledge Base yet',
        'zh-Hans': '暂无 Knowledge Base',
        fr: 'Aucune base de connaissances',
        ja: 'まだ Knowledge Base はありません',
        ko: '아직 Knowledge Base 없음',
        'zh-Hant': '暫無 Knowledge Base',
      }),
      createKbFirst: t({
        en: 'Please create a Knowledge Base in the Documents page first',
        'zh-Hans': '请先在 Documents 页面创建 Knowledge Base',
        fr: 'Créez d\'abord une base de connaissances dans la page Documents',
        ja: '先に Documents ページで Knowledge Base を作成してください',
        ko: '먼저 Documents 페이지에서 Knowledge Base를 생성해 주세요',
        'zh-Hant': '請先在 Documents 頁面建立 Knowledge Base',
      }),
      kbDocuments: t({
        en: '{count} documents',
        'zh-Hans': '{count} 个文档',
        fr: '{count} document(s)',
        ja: '{count} 件のドキュメント',
        ko: '문서 {count}개',
        'zh-Hant': '{count} 個文件',
      }),
      addSuccess: t({
        en: 'Successfully added Knowledge Base "{name}", {count} documents in total',
        'zh-Hans': '成功添加 Knowledge Base "{name}"，共 {count} 个文档',
        fr: 'Base "{name}" ajoutée, {count} document(s) au total',
        ja: 'Knowledge Base "{name}" を追加しました、合計 {count} 件',
        ko: 'Knowledge Base "{name}" 추가됨, 총 {count}개 문서',
        'zh-Hant': '成功新增 Knowledge Base "{name}"，共 {count} 個文件',
      }),
      addKbFailed: t({
        en: 'Failed to add Knowledge Base, please try again',
        'zh-Hans': '添加 Knowledge Base 失败，请重试',
        fr: 'Échec de l\'ajout de la base, réessayez',
        ja: 'Knowledge Base の追加に失敗しました。再試行してください',
        ko: 'Knowledge Base 추가 실패, 다시 시도해 주세요',
        'zh-Hant': '新增 Knowledge Base 失敗，請重試',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
    },

    // Skills Manager Panel Component
    skillsManager: {
      title: t({
        en: '🔧 Skills Manager',
        'zh-Hans': '🔧 Skills 管理',
        fr: '🔧 Gestionnaire Skills',
        ja: '🔧 Skills 管理',
        ko: '🔧 Skills 관리',
        'zh-Hant': '🔧 Skills 管理',
      }),
      close: t({
        en: 'Close',
        'zh-Hans': '关闭',
        fr: 'Fermer',
        ja: '閉じる',
        ko: '닫기',
        'zh-Hant': '關閉',
      }),
      loading: t({
        en: 'Loading...',
        'zh-Hans': '加载中...',
        fr: 'Chargement...',
        ja: '読み込み中...',
        ko: '로딩 중...',
        'zh-Hant': '載入中...',
      }),
      noSkills: t({
        en: 'No Skills available',
        'zh-Hans': '暂无可用的 Skills',
        fr: 'Aucun Skill disponible',
        ja: '利用可能な Skills はありません',
        ko: '사용 가능한 Skills 없음',
        'zh-Hant': '暫無可用的 Skills',
      }),
      enabled: t({
        en: 'Enabled: {count} / {total}',
        'zh-Hans': '已启用：{count} / {total}',
        fr: 'Activés : {count} / {total}',
        ja: '有効：{count} / {total}',
        ko: '활성화: {count} / {total}',
        'zh-Hant': '已啟用：{count} / {total}',
      }),
      hint: t({
        en: 'Note: Restart conversation after enabling new Skills for them to take effect',
        'zh-Hans': '提示：开启后需重新发起对话才能使用新 Skills',
        fr: 'Après activation, relancez la conversation pour que les nouveaux Skills prennent effet.',
        ja: '有効化後は会話を再開すると新しい Skills が反映されます。',
        ko: '활성화 후 대화를 다시 시작하면 새 Skills가 적용됩니다.',
        'zh-Hant': '提示：開啟後需重新發起對話才能使用新 Skills',
      }),
      enable: t({
        en: 'Enable',
        'zh-Hans': '开启',
        fr: 'Activer',
        ja: '有効にする',
        ko: '활성화',
        'zh-Hant': '開啟',
      }),
      disable: t({
        en: 'Disable',
        'zh-Hans': '关闭',
        fr: 'Désactiver',
        ja: '無効にする',
        ko: '비활성화',
        'zh-Hant': '關閉',
      }),
      toast: {
        enableFailed: t({
          en: 'Failed to enable skill',
          'zh-Hans': '启用技能失败',
          fr: 'Échec de l\'activation du skill',
          ja: 'スキルの有効化に失敗しました',
          ko: '스킬 활성화 실패',
          'zh-Hant': '啟用技能失敗',
        }),
        notSynced: t({
          en: 'Skill not synced to runtime directory: {slug}. Current enable will not take effect.',
          'zh-Hans': '技能未同步到运行时目录：{slug}。当前启用不会生效。',
          fr: 'Skill non synchronisé : {slug}. L\'activation actuelle ne prendra pas effet.',
          ja: 'スキルがランタイムに同期されていません：{slug}。現在の有効化は反映されません。',
          ko: '스킬이 런타임 디렉터리에 동기화되지 않음: {slug}. 현재 활성화는 적용되지 않습니다.',
          'zh-Hant': '技能未同步至執行時目錄：{slug}。目前啟用不會生效。',
        }),
        globalEnabled: t({
          en: 'This skill has been globally enabled by admin and cannot be disabled.',
          'zh-Hans': '该技能已被管理员全局启用，无法关闭。',
          fr: 'Ce skill a été activé globalement par l\'admin et ne peut pas être désactivé.',
          ja: 'このスキルは管理者によりグローバルに有効化されており、無効にできません。',
          ko: '이 스킬은 관리자가 전역 활성화하여 비활성화할 수 없습니다.',
          'zh-Hant': '該技能已被管理員全域啟用，無法關閉。',
        }),
      },
    },

    // Chat Composer Component
    composer: {
      placeholder: t({
        en: 'How can I help you today?',
        'zh-Hans': 'How can I help you today?',
        fr: 'Comment puis-je vous aider ?',
        ja: '今日は何をお手伝いしましょうか？',
        ko: '오늘 무엇을 도와드릴까요?',
        'zh-Hant': '今天我能幫您什麼？',
      }),
      uploadFile: t({
        en: 'Upload file',
        'zh-Hans': '上传文件',
        fr: 'Télécharger un fichier',
        ja: 'ファイルをアップロード',
        ko: '파일 업로드',
        'zh-Hant': '上傳檔案',
      }),
      clearInput: t({
        en: 'Clear input',
        'zh-Hans': '清空输入',
        fr: 'Effacer la saisie',
        ja: '入力をクリア',
        ko: '입력 지우기',
        'zh-Hant': '清空輸入',
      }),
      currentModel: t({
        en: 'Current model',
        'zh-Hans': '当前模型',
        fr: 'Modèle actuel',
        ja: '現在のモデル',
        ko: '현재 모델',
        'zh-Hant': '目前模型',
      }),
      toggleWorkspace: t({
        en: 'Toggle workspace',
        'zh-Hans': '切换工作空间',
        fr: 'Basculer l\'espace de travail',
        ja: 'ワークスペースの切り替え',
        ko: '작업 공간 전환',
        'zh-Hant': '切換工作空間',
      }),
      workspaceTitle: t({
        en: 'Knowledge Base / Workspace',
        'zh-Hans': '知识库 / 工作区',
        fr: 'Base de connaissances / Espace',
        ja: 'ナレッジベース / ワークスペース',
        ko: '지식베이스 / 작업 공간',
        'zh-Hant': '知識庫 / 工作區',
      }),
      sessionFiles: t({
        en: 'Session files',
        'zh-Hans': '会话文件',
        fr: 'Fichiers de session',
        ja: 'セッションファイル',
        ko: '세션 파일',
        'zh-Hant': '會話檔案',
      }),
      sessionFilesTitle: t({
        en: 'Session Files',
        'zh-Hans': '会话文件',
        fr: 'Fichiers de session',
        ja: 'セッションファイル',
        ko: '세션 파일',
        'zh-Hant': '會話檔案',
      }),
      sessionInfo: t({
        en: 'View session info',
        'zh-Hans': '查看会话信息',
        fr: 'Voir les infos de session',
        ja: 'セッション情報を見る',
        ko: '세션 정보 보기',
        'zh-Hant': '查看會話資訊',
      }),
      sessionInfoTitle: t({
        en: 'Session Info',
        'zh-Hans': '会话信息',
        fr: 'Infos session',
        ja: 'セッション情報',
        ko: '세션 정보',
        'zh-Hant': '會話資訊',
      }),
      sendMessage: t({
        en: 'Send message',
        'zh-Hans': '发送消息',
        fr: 'Envoyer le message',
        ja: 'メッセージを送信',
        ko: '메시지 보내기',
        'zh-Hant': '傳送訊息',
      }),
      generating: t({
        en: 'Generating, stop or wait',
        'zh-Hans': '正在生成，先停止或等待',
        fr: 'Génération en cours, arrêter ou attendre',
        ja: '生成中、停止するかお待ちください',
        ko: '생성 중, 중지하거나 기다려 주세요',
        'zh-Hant': '正在產生，先停止或等待',
      }),
      uploading: t({
        en: 'Uploading files...',
        'zh-Hans': '正在上传文件...',
        fr: 'Téléchargement des fichiers...',
        ja: 'ファイルをアップロード中...',
        ko: '파일 업로드 중...',
        'zh-Hant': '正在上傳檔案...',
      }),
      errors: {
        noSession: t({
          en: 'Please send a message to create a session first, then upload files.',
          'zh-Hans': '请先发送一条消息以创建会话，再上传文件。',
          fr: 'Envoyez d\'abord un message pour créer une session, puis uploadez les fichiers.',
          ja: '先にメッセージを送信してセッションを作成してから、ファイルをアップロードしてください。',
          ko: '먼저 메시지를 보내 세션을 만든 후 파일을 업로드해 주세요.',
          'zh-Hant': '請先傳送一則訊息以建立會話，再上傳檔案。',
        }),
        uploadFailed: t({
          en: 'Upload failed',
          'zh-Hans': '上传失败',
          fr: 'Échec du téléchargement',
          ja: 'アップロードに失敗しました',
          ko: '업로드 실패',
          'zh-Hant': '上傳失敗',
        }),
        noInput: t({
          en: 'Please enter content before sending.',
          'zh-Hans': '请先输入内容再发送。',
          fr: 'Veuillez saisir du contenu avant d\'envoyer.',
          ja: '送信前に内容を入力してください。',
          ko: '보내기 전에 내용을 입력해 주세요.',
          'zh-Hant': '請先輸入內容再傳送。',
        }),
        createSessionFirst: t({
          en: 'Please create a session first to upload files',
          'zh-Hans': '请先创建会话再上传文件',
          fr: 'Créez d\'abord une session pour uploader des fichiers',
          ja: 'ファイルをアップロードするには先にセッションを作成してください',
          ko: '파일을 업로드하려면 먼저 세션을 생성해 주세요',
          'zh-Hant': '請先建立會話再上傳檔案',
        }),
      },
      ariaLabels: {
        uploadButton: t({
          en: 'Upload file',
          'zh-Hans': '上传文件',
          fr: 'Télécharger un fichier',
          ja: 'ファイルをアップロード',
          ko: '파일 업로드',
          'zh-Hant': '上傳檔案',
        }),
        uploadButtonDisabled: t({
          en: 'Create a session first before uploading files',
          'zh-Hans': '请先创建会话再上传文件',
          fr: 'Créez une session avant d\'uploader des fichiers',
          ja: 'ファイルをアップロードする前にセッションを作成してください',
          ko: '파일 업로드 전에 세션을 먼저 생성해 주세요',
          'zh-Hant': '請先建立會話再上傳檔案',
        }),
        uploadButtonTitle: t({
          en: 'Upload file to workspace',
          'zh-Hans': '上传文件到工作区',
          fr: 'Télécharger un fichier vers l\'espace',
          ja: 'ワークスペースにファイルをアップロード',
          ko: '작업 공간에 파일 업로드',
          'zh-Hant': '上傳檔案到工作區',
        }),
        clearButton: t({
          en: 'Clear input',
          'zh-Hans': '清空输入',
          fr: 'Effacer la saisie',
          ja: '入力をクリア',
          ko: '입력 지우기',
          'zh-Hant': '清空輸入',
        }),
        closeButton: t({
          en: 'Close',
          'zh-Hans': '关闭',
          fr: 'Fermer',
          ja: '閉じる',
          ko: '닫기',
          'zh-Hant': '關閉',
        }),
        removeAttachment: t({
          en: 'Remove attachment',
          'zh-Hans': '移除附件',
          fr: 'Retirer la pièce jointe',
          ja: '添付を削除',
          ko: '첨부 제거',
          'zh-Hant': '移除附件',
        }),
      },
    },

    // Session Files Panel Component
    sessionFiles: {
      title: t({
        en: 'Session Files',
        'zh-Hans': '会话文件',
        fr: 'Fichiers de session',
        ja: 'セッションファイル',
        ko: '세션 파일',
        'zh-Hant': '會話檔案',
      }),
      loading: t({
        en: 'Loading files...',
        'zh-Hans': '加载文件中...',
        fr: 'Chargement des fichiers...',
        ja: 'ファイルを読み込み中...',
        ko: '파일 로딩 중...',
        'zh-Hant': '載入檔案中...',
      }),
      loadError: t({
        en: 'Failed to load files',
        'zh-Hans': '加载文件失败',
        fr: 'Échec du chargement des fichiers',
        ja: 'ファイルの読み込みに失敗しました',
        ko: '파일 로드 실패',
        'zh-Hant': '載入檔案失敗',
      }),
      noFiles: t({
        en: 'No files in this session yet',
        'zh-Hans': '此会话中暂无文件',
        fr: 'Aucun fichier dans cette session',
        ja: 'このセッションにはまだファイルがありません',
        ko: '이 세션에는 아직 파일이 없습니다',
        'zh-Hant': '此會話中暫無檔案',
      }),
      writeFile: t({
        en: 'Write file',
        'zh-Hans': '写入文件',
        fr: 'Écrire un fichier',
        ja: 'ファイルを書き込む',
        ko: '파일 쓰기',
        'zh-Hant': '寫入檔案',
      }),
      refresh: t({
        en: 'Refresh',
        'zh-Hans': '刷新',
        fr: 'Actualiser',
        ja: '更新',
        ko: '새로고침',
        'zh-Hant': '重新整理',
      }),
    },

    // Session Info Panel Component
    sessionInfo: {
      title: t({
        en: 'Session Information',
        'zh-Hans': '会话信息',
        fr: 'Informations de session',
        ja: 'セッション情報',
        ko: '세션 정보',
        'zh-Hant': '會話資訊',
      }),
      sessionId: t({
        en: 'Session ID',
        'zh-Hans': '会话 ID',
        fr: 'ID de session',
        ja: 'セッション ID',
        ko: '세션 ID',
        'zh-Hant': '會話 ID',
      }),
      copySessionId: t({
        en: 'Copy Session ID',
        'zh-Hans': '复制 Session ID',
        fr: 'Copier l\'ID de session',
        ja: 'Session ID をコピー',
        ko: 'Session ID 복사',
        'zh-Hant': '複製 Session ID',
      }),
      createdAt: t({
        en: 'Created',
        'zh-Hans': '创建时间',
        fr: 'Créé le',
        ja: '作成日時',
        ko: '생성일',
        'zh-Hant': '建立時間',
      }),
      lastActivity: t({
        en: 'Last Activity',
        'zh-Hans': '最后活动',
        fr: 'Dernière activité',
        ja: '最終アクティビティ',
        ko: '마지막 활동',
        'zh-Hant': '最後活動',
      }),
      messageCount: t({
        en: 'Messages',
        'zh-Hans': '消息数',
        fr: 'Messages',
        ja: 'メッセージ数',
        ko: '메시지 수',
        'zh-Hant': '訊息數',
      }),
      skills: t({
        en: 'Active Skills',
        'zh-Hans': '启用的技能',
        fr: 'Skills actifs',
        ja: '有効なスキル',
        ko: '활성 Skills',
        'zh-Hant': '啟用的技能',
      }),
      mcpServers: t({
        en: 'MCP Servers',
        'zh-Hans': 'MCP 服务器',
        fr: 'Serveurs MCP',
        ja: 'MCP サーバー',
        ko: 'MCP 서버',
        'zh-Hant': 'MCP 伺服器',
      }),
      permissions: t({
        en: 'Permissions',
        'zh-Hans': '权限',
        fr: 'Permissions',
        ja: '権限',
        ko: '권한',
        'zh-Hant': '權限',
      }),
      noSkills: t({
        en: 'No skills enabled',
        'zh-Hans': '未启用技能',
        fr: 'Aucun skill activé',
        ja: '有効なスキルはありません',
        ko: '활성화된 스킬 없음',
        'zh-Hant': '未啟用技能',
      }),
      noMcpServers: t({
        en: 'No MCP servers configured',
        'zh-Hans': '未配置 MCP 服务器',
        fr: 'Aucun serveur MCP configuré',
        ja: 'MCP サーバーは設定されていません',
        ko: '설정된 MCP 서버 없음',
        'zh-Hant': '未設定 MCP 伺服器',
      }),
    },

    // Permission Badge Component
    permission: {
      full: t({
        en: 'Full Access',
        'zh-Hans': '完全访问',
        fr: 'Accès complet',
        ja: 'フルアクセス',
        ko: '전체 액세스',
        'zh-Hant': '完全存取',
      }),
      restricted: t({
        en: 'Restricted',
        'zh-Hans': '受限',
        fr: 'Restreint',
        ja: '制限あり',
        ko: '제한됨',
        'zh-Hant': '受限',
      }),
      bashDisabled: t({
        en: 'Bash tool disabled',
        'zh-Hans': 'Bash 工具已禁用',
        fr: 'Outil Bash désactivé',
        ja: 'Bash ツールは無効です',
        ko: 'Bash 도구 비활성화됨',
        'zh-Hant': 'Bash 工具已停用',
      }),
      title: t({
        en: 'Session Permissions',
        'zh-Hans': '会话权限',
        fr: 'Permissions de session',
        ja: 'セッション権限',
        ko: '세션 권한',
        'zh-Hant': '會話權限',
      }),
    },

    // MCP Status Indicator Component
    mcpStatus: {
      connected: t({
        en: 'MCP Connected',
        'zh-Hans': 'MCP 已连接',
        fr: 'MCP connecté',
        ja: 'MCP 接続済み',
        ko: 'MCP 연결됨',
        'zh-Hant': 'MCP 已連線',
      }),
      disconnected: t({
        en: 'MCP Disconnected',
        'zh-Hans': 'MCP 未连接',
        fr: 'MCP déconnecté',
        ja: 'MCP 未接続',
        ko: 'MCP 연결 끊김',
        'zh-Hant': 'MCP 未連線',
      }),
      servers: t({
        en: '{count} server(s)',
        'zh-Hans': '{count} 个服务器',
        fr: '{count} serveur(s)',
        ja: '{count} サーバー',
        ko: '서버 {count}개',
        'zh-Hant': '{count} 個伺服器',
      }),
    },
  },
  key: 'claude-chat',
} satisfies Dictionary;

export default claudeChatContent;
