import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Kin homepage content (JumpX V4 rebuild).
 *
 * All 6 configured locales are required (intlayer requiredLocales = configured
 * locales). Mono / terminal / eyebrow / model-id strings are authored directly
 * in the route — per the design system, Latin stays mono-English.
 *
 * NOTE on spacing: where a heading accent directly follows the lead in JSX
 * (no literal space), the lead string carries a trailing space for space-
 * delimited locales (en/fr/ko) and none for CJK (zh/ja). Keep them.
 */
const homeContent = {
  content: {
    hero: {
      titleSoft: t({
        en: 'Your data. Your models. ',
        fr: 'Vos données. Vos modèles. ',
        ja: 'あなたのデータ、あなたのモデル、',
        ko: '당신의 데이터, 당신의 모델, ',
        'zh-Hans': '你的数据，你的模型，',
        'zh-Hant': '你的資料，你的模型，',
      }),
      titleMain: t({
        en: '',
        fr: '',
        ja: '',
        ko: '',
        'zh-Hans': '',
        'zh-Hant': '',
      }),
      titleAccent: t({
        en: 'Your servers.',
        fr: 'Vos serveurs.',
        ja: 'あなたのサーバー。',
        ko: '당신의 서버.',
        'zh-Hans': '你的服务器。',
        'zh-Hant': '你的伺服器。',
      }),
      subtitleStrong: t({
        en: 'Kin is a private, self-hosted AI-Agent workspace for small teams.',
        fr: 'Kin est un espace de travail AI-Agent privé et auto-hébergé pour les petites équipes.',
        ja: 'Kin は、小さなチーム向けのプライベートなセルフホスト型 AI-Agent ワークスペースです。',
        ko: 'Kin는 소규모 팀을 위한 프라이빗 셀프호스팅 AI-Agent 워크스페이스입니다.',
        'zh-Hans': 'Kin 是面向小团队的私有化 AI-Agent 工作台。',
        'zh-Hant': 'Kin 是面向小團隊的私有化 AI-Agent 工作台。',
      }),
      subtitle: t({
        en: 'Self-hosted, single-org, multi-user, fully sandboxed — your team runs real, capable agents on its own machines: code execution, internal tools, live preview, all inside sandbox guardrails.',
        fr: 'Auto-hébergé, mono-organisation, multi-utilisateurs, entièrement isolé — votre équipe exécute de vrais agents capables sur ses propres machines : exécution de code, outils internes, aperçu en direct, le tout dans des garde-fous de bac à sable.',
        ja: 'セルフホスト・単一組織・マルチユーザー・完全サンドボックス——チームは自分のマシン上で、本当に役立つエージェントを安全に動かせます：コード実行、社内ツール接続、ライブプレビュー、すべてサンドボックスのガードレール内で。',
        ko: '셀프호스팅·단일 조직·멀티 유저·완전 샌드박스——팀이 자체 머신에서 실제로 일하는 에이전트를 안전하게 실행합니다: 코드 실행, 내부 도구 연결, 라이브 프리뷰까지 모두 샌드박스 가드레일 안에서.',
        'zh-Hans': '自托管、单组织、多用户、全沙盒——团队在自己的机器上，安全地跑起真正能干活的 Agent：代码执行、连内网工具、真预览，全在沙盒护栏内。',
        'zh-Hant': '自託管、單組織、多使用者、全沙盒——團隊在自己的機器上，安全地跑起真正能幹活的 Agent：程式碼執行、連內網工具、真預覽，全在沙盒護欄內。',
      }),
      ctaPrimary: t({
        en: 'Open workspace',
        fr: "Ouvrir l'espace",
        ja: 'ワークスペースを開く',
        ko: '워크스페이스 열기',
        'zh-Hans': '进入工作台',
        'zh-Hant': '進入工作台',
      }),
      ctaSecondary: t({
        en: 'View source · GitHub',
        fr: 'Voir le code · GitHub',
        ja: 'ソースを見る · GitHub',
        ko: '소스 보기 · GitHub',
        'zh-Hans': '查看源码 · GitHub',
        'zh-Hant': '查看原始碼 · GitHub',
      }),
      metaDeploy: t({
        en: 'one-command deploy',
        fr: 'déploiement en une commande',
        ja: 'ワンコマンド配備',
        ko: '원커맨드 배포',
        'zh-Hans': '一键部署',
        'zh-Hant': '一鍵部署',
      }),
      metaModels: t({
        en: 'any model, no lock-in',
        fr: 'tout modèle, sans verrou',
        ja: '任意のモデル、固定なし',
        ko: '어떤 모델이든, 종속 없음',
        'zh-Hans': '不锁模型，随你切',
        'zh-Hant': '不鎖模型，隨你切',
      }),
      metaSandbox: t({
        en: 'per-session isolation',
        fr: 'isolation par session',
        ja: 'セッション単位の隔離',
        ko: '세션별 격리',
        'zh-Hans': '沙盒隔离',
        'zh-Hant': '沙盒隔離',
      }),
    },
    concept: {
      h2Soft: t({
        en: 'Not one more cloud AI assistant —',
        fr: 'Pas un assistant IA cloud de plus —',
        ja: 'もう一つのクラウド AI アシスタントではなく、',
        ko: '또 하나의 클라우드 AI 어시스턴트가 아니라,',
        'zh-Hans': '不是又一个云端 AI 助手，',
        'zh-Hant': '不是又一個雲端 AI 助手，',
      }),
      h2Lead: t({
        en: 'but an',
        fr: 'mais un',
        ja: 'あなたのサーバールームで動く',
        ko: '당신의 서버룸에서 돌아가는',
        'zh-Hans': '而是一台跑在你机房里的',
        'zh-Hant': '而是一台跑在你機房裡的',
      }),
      h2Accent: t({
        en: 'Agent workspace that runs in your own server room.',
        fr: 'espace de travail Agent qui tourne dans votre propre salle serveur.',
        ja: 'Agent ワークスペース。',
        ko: 'Agent 워크스페이스.',
        'zh-Hans': 'Agent 工作台',
        'zh-Hant': 'Agent 工作台',
      }),
      bodyP1: t({
        en: 'Public SaaS hands your data, keys and code to someone else. Kin flips it: your documents, knowledge, sessions and audit live on your own server — and model calls go only to the endpoint you choose, including your own. Your system of record never leaves.',
        fr: "Le SaaS public confie vos données, clés et code à un tiers. Kin inverse la logique : vos documents, connaissances, sessions et journaux vivent sur votre propre serveur — et les appels modèle ne vont qu'au endpoint de votre choix, y compris le vôtre. Votre référentiel ne sort jamais.",
        ja: 'パブリック SaaS は、データ・鍵・コードを他人に預けます。Kin は逆です：ドキュメント・ナレッジ・セッション・監査は自分のサーバーに置かれ、モデル呼び出しは自分を含め選んだエンドポイントにのみ送られます。記録の本体は外に出ません。',
        ko: '퍼블릭 SaaS는 데이터·키·코드를 남에게 맡깁니다. Kin는 그 반대입니다: 문서·지식·세션·감사는 당신의 서버에 있고, 모델 호출은 자신을 포함해 고른 엔드포인트로만 갑니다. 기록 원본은 절대 나가지 않습니다.',
        'zh-Hans': '公网 SaaS 把你的数据、密钥、代码交到别人手里。Kin 反过来：文档、知识、会话、审计都留在你自己的服务器上，模型调用只发往你选定的端点（也可以是你自己的）。系统记录一步不出门。',
        'zh-Hant': '公網 SaaS 把你的資料、密鑰、程式碼交到別人手裡。Kin 反過來：文件、知識、會話、稽核都留在你自己的伺服器上，模型呼叫只發往你選定的端點（也可以是你自己的）。系統記錄一步不出門。',
      }),
      bodyP2: t({
        en: 'The threat model is semi-trusted colleagues, not anonymous attackers — so powerful features (stdio MCP, internal access, code execution) are core, legitimate uses, held by sandbox + warning guardrails rather than banned outright.',
        fr: "Le modèle de menace, ce sont des collègues semi-fiables, pas des attaquants anonymes — les fonctions puissantes (MCP stdio, accès interne, exécution de code) sont donc des usages centraux et légitimes, encadrés par un bac à sable et des avertissements plutôt qu'interdits.",
        ja: '脅威モデルは「半分信頼できる同僚」であって、匿名の攻撃者ではありません——だから強力な機能（stdio MCP、社内アクセス、コード実行）は正当なコア用途であり、禁止ではなくサンドボックス＋警告のガードレールで守ります。',
        ko: '위협 모델은 익명의 공격자가 아니라 ‘반쯤 신뢰할 수 있는 동료’입니다——그래서 강력한 기능(stdio MCP, 내부 접근, 코드 실행)은 정당한 핵심 용도이며, 금지가 아니라 샌드박스 + 경고 가드레일로 지킵니다.',
        'zh-Hans': '威胁模型是半可信的同事，不是匿名攻击者——所以强力功能（stdio MCP、连内网、代码执行）是合法核心用途，用沙盒 + 警示护栏守住，而不是一禁了之。',
        'zh-Hant': '威脅模型是半可信的同事，不是匿名攻擊者——所以強力功能（stdio MCP、連內網、程式碼執行）是合法核心用途，用沙盒 + 警示護欄守住，而不是一禁了之。',
      }),
      p1Title: t({
        en: 'Private by deployment',
        fr: 'Privé par déploiement',
        ja: 'デプロイで私有化',
        ko: '배포로 프라이빗하게',
        'zh-Hans': '私有部署，资料留你服务器',
        'zh-Hant': '私有部署，資料留你伺服器',
      }),
      p1Desc: t({
        en: 'One-command Docker. Single org, multiple trusted users. The image runs on the machine you choose — works out of the box.',
        fr: "Docker en une commande. Une organisation, plusieurs utilisateurs de confiance. L'image tourne sur la machine de votre choix — prête à l'emploi.",
        ja: 'Docker ワンコマンド。単一組織・複数の信頼できるユーザー。イメージは選んだマシンで動き、すぐに使えます。',
        ko: 'Docker 원커맨드. 단일 조직, 여러 신뢰된 사용자. 이미지는 선택한 머신에서 돌아가며 바로 사용할 수 있습니다.',
        'zh-Hans': 'Docker 一键起跑，单组织、组织内多个可信用户。镜像跑在你选的机器上，开箱即用。',
        'zh-Hant': 'Docker 一鍵起跑，單組織、組織內多個可信使用者。鏡像跑在你選的機器上，開箱即用。',
      }),
      p2Title: t({
        en: 'Any model, no lock-in',
        fr: 'Tout modèle, sans verrou',
        ja: '任意のモデル、固定なし',
        ko: '어떤 모델이든, 종속 없이',
        'zh-Hans': '不锁模型，随你切',
        'zh-Hant': '不鎖模型，隨你切',
      }),
      p2Desc: t({
        en: 'Bring any model via API — GLM, DeepSeek, GPT, Qwen — or point Kin at your own endpoint. No vendor lock-in; the menu only shows models that probe healthy.',
        fr: "Tout modèle via API — GLM, DeepSeek, GPT, Qwen — ou pointez Kin vers votre propre endpoint. Aucun verrouillage ; le menu n'affiche que les modèles sains.",
        ja: 'API 経由で任意のモデルを——GLM / DeepSeek / GPT / Qwen——あるいは自分のエンドポイントを指定。ベンダー固定なし。メニューには健全なモデルだけ。',
        ko: 'API로 어떤 모델이든——GLM / DeepSeek / GPT / Qwen——또는 자체 엔드포인트 지정. 벤더 종속 없음; 메뉴에는 정상 모델만.',
        'zh-Hans': '经 API 接任意模型——GLM / DeepSeek / GPT / 通义千问——或指向你自己的端点。不锁定任何厂商，菜单只显示探活健康的模型。',
        'zh-Hant': '經 API 接任意模型——GLM / DeepSeek / GPT / 通義千問——或指向你自己的端點。不鎖定任何廠商，選單只顯示探活健康的模型。',
      }),
      p3Title: t({
        en: 'Per-session sandbox',
        fr: 'Bac à sable par session',
        ja: 'セッション単位のサンドボックス',
        ko: '세션별 샌드박스',
        'zh-Hans': '每会话独立沙盒',
        'zh-Hant': '每會話獨立沙盒',
      }),
      p3Desc: t({
        en: 'Per-session config dir + child-process isolation + live preview subdomains. Powerful capability stays inside the guardrails — defense in depth.',
        fr: "Répertoire de config par session + isolation par sous-processus + sous-domaines d'aperçu en direct. La puissance reste dans les garde-fous — défense en profondeur.",
        ja: 'セッションごとの設定ディレクトリ＋子プロセス隔離＋ライブプレビュー用サブドメイン。強力な機能はガードレールの内側に——多層防御です。',
        ko: '세션별 설정 디렉터리 + 자식 프로세스 격리 + 라이브 프리뷰 서브도메인. 강력한 기능은 가드레일 안에——심층 방어입니다.',
        'zh-Hans': 'per-session 配置目录 + 子进程隔离 + 真预览子域名。强力能力关在护栏里，纵深防御。',
        'zh-Hant': 'per-session 設定目錄 + 子行程隔離 + 真預覽子網域。強力能力關在護欄裡，縱深防禦。',
      }),
    },
    features: {
      heading: t({
        en: 'One workspace,',
        fr: 'Un espace de travail,',
        ja: '一つのワークスペースに、',
        ko: '하나의 워크스페이스에,',
        'zh-Hans': '一个工作台，',
        'zh-Hant': '一個工作台，',
      }),
      headingAccent: t({
        en: 'everything you need.',
        fr: "tout ce qu'il vous faut.",
        ja: '必要なものすべて。',
        ko: '필요한 모든 것.',
        'zh-Hans': '该有的都有',
        'zh-Hant': '該有的都有',
      }),
      f1Title: t({ en: 'Agent Chat', fr: 'Agent Chat', ja: 'Agent Chat', ko: 'Agent Chat', 'zh-Hans': 'Agent Chat', 'zh-Hant': 'Agent Chat' }),
      f1Desc: t({
        en: 'Persistent WebSocket, native session resume, live tool-call visualization — the full Agent experience.',
        fr: "WebSocket persistant, reprise de session native, visualisation des appels d'outils en direct — l'expérience Agent complète.",
        ja: '永続 WebSocket、ネイティブなセッション再開、ツール呼び出しのライブ可視化——Agent の体験をフルで。',
        ko: '지속 WebSocket, 네이티브 세션 재개, 실시간 도구 호출 시각화——완전한 Agent 경험.',
        'zh-Hans': '持久 WebSocket 连接、原生会话恢复、工具调用实时可视化——完整的 Agent 交互体验。',
        'zh-Hant': '持久 WebSocket 連線、原生會話恢復、工具呼叫即時視覺化——完整的 Agent 互動體驗。',
      }),
      f2Title: t({
        en: 'Curated Skills',
        fr: 'Skills sélectionnés',
        ja: 'キュレートされた Skills',
        ko: '큐레이션된 Skills',
        'zh-Hans': 'Skills 策展',
        'zh-Hant': 'Skills 策展',
      }),
      f2Desc: t({
        en: 'A team-curated skill set, toggled on the spot. A hand-picked set for your own team — not a public rated marketplace.',
        fr: "Un ensemble de skills sélectionné par l'équipe, activable à la volée. Une sélection pour votre équipe — pas une place de marché publique notée.",
        ja: 'チームが厳選したスキル集を、その場でオン/オフ。自分たちのための精選であって、評価付きの公開マーケットではありません。',
        ko: '팀이 엄선한 스킬 세트를 즉석에서 켜고 끄기. 평점 달린 공개 마켓이 아니라, 우리 팀을 위한 선별입니다.',
        'zh-Hans': '团队精选的技能集，启停即生效。给团队自己用的精选，不是公开评分市场。',
        'zh-Hant': '團隊精選的技能集，啟停即生效。給團隊自己用的精選，不是公開評分市場。',
      }),
      f3Title: t({
        en: 'Artifacts · live preview',
        fr: 'Artifacts · aperçu en direct',
        ja: 'Artifacts · ライブプレビュー',
        ko: 'Artifacts · 라이브 프리뷰',
        'zh-Hans': 'Artifacts · 真预览',
        'zh-Hant': 'Artifacts · 真預覽',
      }),
      f3Desc: t({
        en: 'Live preview for HTML / React / SVG on dedicated subdomains, spun up on demand and reaped automatically.',
        fr: "Aperçu en direct pour HTML / React / SVG sur des sous-domaines dédiés, créés à la demande et recyclés automatiquement.",
        ja: 'HTML / React / SVG を専用サブドメインでライブプレビュー。必要なときに起動し、自動で回収します。',
        ko: 'HTML / React / SVG를 전용 서브도메인에서 라이브 프리뷰. 필요할 때 띄우고 자동으로 회수합니다.',
        'zh-Hans': 'HTML / React / SVG 实时预览，独立预览子域名，按需起停、自动回收。',
        'zh-Hant': 'HTML / React / SVG 即時預覽，獨立預覽子網域，按需起停、自動回收。',
      }),
      f4Title: t({ en: 'Knowledge Base', fr: 'Knowledge Base', ja: 'Knowledge Base', ko: 'Knowledge Base', 'zh-Hans': 'Knowledge Base', 'zh-Hant': 'Knowledge Base' }),
      f4Desc: t({
        en: 'Upload and manage documents as the session knowledge base, so the agent understands your project.',
        fr: "Importez et gérez des documents comme base de connaissances de session, pour que l'agent comprenne votre projet.",
        ja: 'ドキュメントをアップロードしてセッションのナレッジベースとして管理。エージェントがあなたのプロジェクトを理解します。',
        ko: '문서를 업로드해 세션 지식베이스로 관리하면, 에이전트가 당신의 프로젝트를 이해합니다.',
        'zh-Hans': '上传与管理文档，作为会话的上下文知识库，让 Agent 读懂你的项目。',
        'zh-Hant': '上傳與管理文件，作為會話的上下文知識庫，讓 Agent 讀懂你的專案。',
      }),
      f5Title: t({
        en: 'Model switching',
        fr: 'Changement de modèle',
        ja: 'モデル切替',
        ko: '모델 전환',
        'zh-Hans': '多模型切换',
        'zh-Hant': '多模型切換',
      }),
      f5Desc: t({
        en: 'Pick a model per session, with a backend health board. Send to an unhealthy model and it errors — never a silent fallback.',
        fr: "Choisissez un modèle par session, avec un tableau de santé côté serveur. Envoyer vers un modèle en mauvaise santé déclenche une erreur — jamais de repli silencieux.",
        ja: 'セッションごとにモデルを選択。バックエンドのヘルスボード付き。不健全なモデルに送ると黙って代替せず、エラーになります。',
        ko: '세션마다 모델 선택, 백엔드 헬스 보드 제공. 비정상 모델로 보내면 조용히 대체하지 않고 오류를 냅니다.',
        'zh-Hans': '每会话独立选模型，后台健康看板，选了不健康的模型发送即报错——绝不静默兜底。',
        'zh-Hant': '每會話獨立選模型，後台健康看板，選了不健康的模型發送即報錯——絕不靜默兜底。',
      }),
      f6Title: t({ en: 'Session · Sandbox', fr: 'Session · Sandbox', ja: 'Session · Sandbox', ko: 'Session · Sandbox', 'zh-Hans': 'Session · Sandbox', 'zh-Hant': 'Session · Sandbox' }),
      f6Desc: t({
        en: 'Per-session working dir and config, child-process isolation — users within the org never cross-contaminate.',
        fr: "Répertoire de travail et config par session, isolation par sous-processus — les utilisateurs de l'organisation ne se contaminent jamais.",
        ja: 'セッションごとの作業ディレクトリと設定、子プロセス隔離——組織内のユーザー同士が干渉しません。',
        ko: '세션별 작업 디렉터리와 설정, 자식 프로세스 격리——조직 내 사용자끼리 서로 간섭하지 않습니다.',
        'zh-Hans': '每会话独立工作目录与配置，子进程隔离，组织内用户互不串扰。',
        'zh-Hant': '每會話獨立工作目錄與設定，子行程隔離，組織內使用者互不串擾。',
      }),
    },
    product: {
      heading: t({
        en: 'Sessions on the left,',
        fr: 'Les sessions à gauche,',
        ja: '左にセッション、',
        ko: '왼쪽엔 세션,',
        'zh-Hans': '会话在左，',
        'zh-Hant': '會話在左，',
      }),
      headingAccent: t({
        en: 'output on the right.',
        fr: 'la sortie à droite.',
        ja: '右に成果物。',
        ko: '오른쪽엔 산출물.',
        'zh-Hans': '产出在右',
        'zh-Hant': '產出在右',
      }),
    },
    models: {
      heading: t({
        en: 'Any model,',
        fr: 'Tout modèle,',
        ja: '任意のモデルを、',
        ko: '어떤 모델이든,',
        'zh-Hans': '任意模型，',
        'zh-Hant': '任意模型，',
      }),
      headingAccent: t({
        en: 'any provider',
        fr: 'tout fournisseur',
        ja: '任意のプロバイダ',
        ko: '어떤 제공자든',
        'zh-Hans': '任意供应商',
        'zh-Hant': '任意供應商',
      }),
      headingTail: t({
        en: ', switch at will.',
        fr: ', à la demande.',
        ja: '、自在に切替。',
        ko: ', 자유롭게 전환.',
        'zh-Hans': '，随你切。',
        'zh-Hant': '，隨你切。',
      }),
      lede: t({
        en: 'Any model — whatever account or gateway it comes from — is switchable as long as it works. The backend probes; the menu only lists the healthy ones.',
        fr: "N'importe quel modèle — quel que soit le compte ou la passerelle — est commutable dès lors qu'il fonctionne. Le backend sonde ; le menu ne liste que ceux en bonne santé.",
        ja: 'どのアカウント・ゲートウェイ由来のモデルでも、使えるかぎり切替可能。バックエンドが探活し、メニューには健全なものだけが並びます。',
        ko: '어떤 계정·게이트웨이에서 온 모델이든, 동작하기만 하면 전환 가능. 백엔드가 헬스 체크하고 메뉴에는 정상인 것만 표시됩니다.',
        'zh-Hans': '不管来自哪个账号或网关的模型，能用就能切。后台探活，菜单只放健康的。',
        'zh-Hant': '不管來自哪個帳號或網關的模型，能用就能切。後台探活，選單只放健康的。',
      }),
    },
    deploy: {
      heading: t({
        en: 'Clone, ',
        fr: 'Clonez, ',
        ja: 'クローンして、',
        ko: '클론하고, ',
        'zh-Hans': '克隆、',
        'zh-Hant': '克隆、',
      }),
      headingAccent: t({
        en: 'and go',
        fr: "et c'est parti",
        ja: '起動',
        ko: '실행',
        'zh-Hans': '起跑',
        'zh-Hant': '起跑',
      }),
      headingTail: t({
        en: ' — it really is that simple.',
        fr: " — c'est vraiment aussi simple.",
        ja: '。本当に、これだけ。',
        ko: '까지. 정말 이게 전부입니다.',
        'zh-Hans': '，就这么简单。',
        'zh-Hant': '，就這麼簡單。',
      }),
      body: t({
        en: 'Optimized for "one-command Docker, works out of the box for a team", not elastic public-SaaS scale. Open-source (AGPLv3), self-hosted — your documents, sessions and audit stay on your server, and model calls go only to the endpoint you choose.',
        fr: "Optimisé pour « Docker en une commande, prêt à l'emploi pour une équipe », pas pour l'échelle d'un SaaS public. Open-source (AGPLv3), auto-hébergé — vos documents, sessions et journaux restent sur votre serveur, et les appels modèle ne vont qu'au endpoint de votre choix.",
        ja: '「チームが Docker ワンコマンドで起動、すぐ使える」に最適化——公開 SaaS 規模のためではありません。オープンソース（AGPLv3）・セルフホスト——ドキュメント・セッション・監査は自分のサーバーに残り、モデル呼び出しは選んだエンドポイントにのみ送られます。',
        ko: '“팀이 Docker 원커맨드로 기동, 바로 사용”에 최적화——공개 SaaS 규모용이 아닙니다. 오픈소스(AGPLv3)·셀프호스팅——문서·세션·감사는 당신의 서버에 남고, 모델 호출은 고른 엔드포인트로만 갑니다.',
        'zh-Hans': '为「团队 Docker 一键起跑、开箱即用」而优化，而非弹性公网 SaaS 规模。开源（AGPLv3）、自托管——文档、会话、审计都留在你的服务器上，模型调用只发往你选定的端点。',
        'zh-Hant': '為「團隊 Docker 一鍵起跑、開箱即用」而最佳化，而非彈性公網 SaaS 規模。開源（AGPLv3）、自託管——文件、會話、稽核都留在你的伺服器上，模型呼叫只發往你選定的端點。',
      }),
      ctaPrimary: t({
        en: 'Deploy docs',
        fr: 'Docs de déploiement',
        ja: 'デプロイ手順',
        ko: '배포 문서',
        'zh-Hans': '部署文档',
        'zh-Hant': '部署文件',
      }),
      ctaSecondary: t({
        en: 'GitHub · deeptoai/kin',
        fr: 'GitHub · deeptoai/kin',
        ja: 'GitHub · deeptoai/kin',
        ko: 'GitHub · deeptoai/kin',
        'zh-Hans': 'GitHub · deeptoai/kin',
        'zh-Hant': 'GitHub · deeptoai/kin',
      }),
    },
    feat: {
      coworkTitle: t({
        en: 'Share a project with your team',
        fr: 'Partagez un projet avec votre équipe',
        ja: 'プロジェクトをチームで共有',
        ko: '팀과 프로젝트를 공유',
        'zh-Hans': '和团队共享一个 Project',
        'zh-Hant': '和團隊共享一個 Project',
      }),
      coworkDesc: t({
        en: "Like ChatGPT's Shared Projects — but self-hosted. Sessions, knowledge and output are shared across the team, with invites and access you control.",
        fr: "Comme les projets partagés de ChatGPT — mais auto-hébergé. Sessions, connaissances et résultats partagés dans l'équipe, avec un accès que vous contrôlez.",
        ja: 'ChatGPT の共有プロジェクトのように——ただしセルフホスト。セッション・ナレッジ・成果をチームで共有し、招待と権限はあなたが管理。',
        ko: 'ChatGPT 공유 프로젝트처럼——단, 셀프호스팅. 세션·지식·산출물을 팀이 공유하고, 초대와 권한은 당신이 관리.',
        'zh-Hans': '像 ChatGPT 的共享 Project，但自托管——会话、知识、产出在团队内共享，邀请与权限你说了算。',
        'zh-Hant': '像 ChatGPT 的共享 Project，但自託管——會話、知識、產出在團隊內共享，邀請與權限你說了算。',
      }),
      ragTitle: t({
        en: 'Built-in RAG · your own vector DB',
        fr: 'RAG intégré · votre propre base vectorielle',
        ja: '内蔵 RAG · 独自のベクトル DB',
        ko: '내장 RAG · 자체 벡터 DB',
        'zh-Hans': '内置 RAG · 独立向量库与文档库',
        'zh-Hant': '內建 RAG · 獨立向量庫與文件庫',
      }),
      ragDesc: t({
        en: "Upload documents into a knowledge base; the agent answers grounded in retrieval over your own vector database — something a desktop app simply can't give you.",
        fr: "Importez des documents dans une base de connaissances ; l'agent répond ancré sur votre propre base vectorielle — ce qu'une app de bureau ne peut pas offrir.",
        ja: 'ドキュメントをナレッジベースにアップロード。エージェントは自前のベクトル DB の検索に基づいて回答——デスクトップ版には出せない価値。',
        ko: '문서를 지식베이스에 업로드하면, 에이전트가 자체 벡터 DB 검색에 근거해 답합니다——데스크톱 앱이 줄 수 없는 것.',
        'zh-Hans': '上传文档建知识库，Agent 基于你自己的向量库检索作答——这正是桌面版替代不了的。',
        'zh-Hant': '上傳文件建知識庫，Agent 基於你自己的向量庫檢索作答——這正是桌面版替代不了的。',
      }),
      pluginTitle: t({
        en: 'Plugins · OCR for complex PDFs & tables',
        fr: 'Plugins · OCR pour PDF et tableaux complexes',
        ja: 'プラグイン · 複雑な PDF と表の OCR',
        ko: '플러그인 · 복잡한 PDF·표 OCR',
        'zh-Hans': '插件扩展 · OCR 识别复杂 PDF 与表格',
        'zh-Hant': '外掛擴充 · OCR 辨識複雜 PDF 與表格',
      }),
      pluginDesc: t({
        en: 'Extend Kin with plugins — like an OCR component that scans complex PDFs and extracts table structure.',
        fr: "Étendez Kin avec des plugins — comme un composant OCR qui scanne des PDF complexes et extrait la structure des tableaux.",
        ja: 'プラグインで Kin を拡張——複雑な PDF を読み取り表構造を抽出する OCR コンポーネントなど。',
        ko: '플러그인으로 Kin을 확장——복잡한 PDF를 스캔해 표 구조를 추출하는 OCR 컴포넌트 등.',
        'zh-Hans': '用插件扩展能力，比如 OCR 组件扫描复杂 PDF、识别表格结构。',
        'zh-Hant': '用外掛擴充能力，例如 OCR 元件掃描複雜 PDF、辨識表格結構。',
      }),
      previewTitle: t({
        en: 'Run a live server in a sandbox · share a public URL',
        fr: 'Lancez un serveur dans un bac à sable · partagez une URL publique',
        ja: 'サンドボックスでサーバー起動 · 公開 URL を共有',
        ko: '샌드박스에서 서버 실행 · 공개 URL 공유',
        'zh-Hans': '沙盒起服务 · 一键分享公网 URL',
        'zh-Hant': '沙盒起服務 · 一鍵分享公網 URL',
      }),
      previewDesc: t({
        en: 'Spin up a React + Vite app inside an isolated sandbox and share a real public link with anyone — scripts, routing and storage all actually work.',
        fr: "Démarrez une app React + Vite dans un bac à sable isolé et partagez un vrai lien public — scripts, routage et stockage fonctionnent réellement.",
        ja: '隔離サンドボックスで React + Vite アプリを起動し、本物の公開リンクを誰とでも共有——スクリプト・ルーティング・保存まで実際に動く。',
        ko: '격리 샌드박스에서 React + Vite 앱을 띄우고 진짜 공개 링크를 누구와도 공유——스크립트·라우팅·저장까지 실제로 동작.',
        'zh-Hans': '在隔离沙盒里跑起 React + Vite 应用，一键生成公网链接分享给任何人——脚本、路由、存储都真生效。',
        'zh-Hant': '在隔離沙盒裡跑起 React + Vite 應用，一鍵產生公網連結分享給任何人——指令稿、路由、儲存都真生效。',
      }),
    },
    icp: {
      heading: t({
        en: 'Built for teams that',
        fr: 'Conçu pour les équipes dont',
        ja: 'こんなチームのために',
        ko: '이런 팀을 위해',
        'zh-Hans': '为数据碰不得公网 AI 的',
        'zh-Hant': '為資料碰不得公網 AI 的',
      }),
      headingAccent: t({
        en: " can't trust public-cloud AI.",
        fr: ' ne peuvent pas confier au cloud public.',
        ja: 'クラウド AI に預けられない仕事。',
        ko: ' 클라우드 AI에 맡길 수 없는 팀.',
        'zh-Hans': '小团队而建',
        'zh-Hant': '小團隊而建',
      }),
      lede: t({
        en: 'Data-sensitive teams under ~30 people — heavy AI users with no platform-ops team and no room for a data leak.',
        fr: "Équipes sensibles aux données de moins de ~30 personnes — grands utilisateurs d'IA, sans équipe ops ni marge pour une fuite.",
        ja: '~30 名以下のデータ機密チーム——AI を多用するが運用チームはなく、漏洩の余地もない。',
        ko: '~30명 이하의 데이터 민감 팀——AI는 많이 쓰지만 운영팀도 없고 유출 여지도 없는 곳.',
        'zh-Hans': '人数 30 以内、重度用 AI、却没有专职运维、也容不得数据外泄的小团队。',
        'zh-Hant': '人數 30 以內、重度用 AI、卻沒有專職維運、也容不得資料外洩的小團隊。',
      }),
      c1Title: t({ en: 'Law firms', fr: "Cabinets d'avocats", ja: '法律事務所', ko: '로펌', 'zh-Hans': '律所', 'zh-Hant': '律所' }),
      c1Desc: t({
        en: 'Client confidentiality and privilege — work that public AI tools can break.',
        fr: 'Confidentialité client et secret professionnel.',
        ja: '依頼者の守秘と特権を守る。',
        ko: '의뢰인 비밀유지와 특권 보호.',
        'zh-Hans': '客户保密与律师特权，公网 AI 会破坏。',
        'zh-Hant': '客戶保密與律師特權，公網 AI 會破壞。',
      }),
      c2Title: t({ en: 'Funds', fr: 'Fonds', ja: 'ファンド', ko: '펀드', 'zh-Hans': '基金', 'zh-Hant': '基金' }),
      c2Desc: t({
        en: 'MNPI, deal and portfolio data that can never leak.',
        fr: 'Données MNPI, deals et portefeuille.',
        ja: '未公開情報・案件・ポートフォリオ。',
        ko: '미공개 정보·딜·포트폴리오.',
        'zh-Hans': '内幕信息、尽调与持仓数据，绝不外流。',
        'zh-Hant': '內幕資訊、盡調與持倉資料，絕不外流。',
      }),
      c3Title: t({ en: 'Family offices', fr: 'Family offices', ja: 'ファミリーオフィス', ko: '패밀리 오피스', 'zh-Hans': '家族办公室', 'zh-Hant': '家族辦公室' }),
      c3Desc: t({
        en: 'Family privacy and assets, with zero exposure.',
        fr: 'Vie privée et actifs de la famille.',
        ja: '一族のプライバシーと資産。',
        ko: '가문의 프라이버시와 자산.',
        'zh-Hans': '家族隐私与资产，零外泄。',
        'zh-Hant': '家族隱私與資產，零外洩。',
      }),
      c4Title: t({ en: 'Research teams', fr: 'Équipes de recherche', ja: '研究チーム', ko: '연구팀', 'zh-Hans': '科研团队', 'zh-Hant': '科研團隊' }),
      c4Desc: t({
        en: 'Unpublished IP and grant data, kept in your own lab.',
        fr: 'PI non publiée et données de subvention.',
        ja: '未発表の研究と助成データ。',
        ko: '미발표 연구와 과제 데이터.',
        'zh-Hans': '未发表研究与课题数据，留在自己实验室。',
        'zh-Hant': '未發表研究與課題資料，留在自己實驗室。',
      }),
    },
    footer: {
      bigPre: t({
        en: 'Time to ',
        fr: 'Il est temps de ',
        ja: 'さあ、',
        ko: '이제 ',
        'zh-Hans': '在你的服务器上，',
        'zh-Hant': '在你的伺服器上，',
      }),
      bigAccent: t({
        en: 'launch',
        fr: 'lancer',
        ja: '起動だ',
        ko: '띄울 시간',
        'zh-Hans': '起跑',
        'zh-Hant': '起跑',
      }),
    },
  },
  key: 'home',
} satisfies Dictionary;

export default homeContent;
