import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * OxyGenie homepage content (JumpX V4 rebuild).
 *
 * All 6 configured locales are required (intlayer requiredLocales = configured
 * locales). Mono / terminal / eyebrow / model-id strings are authored directly
 * in the route — per the design system, Latin stays mono-English.
 *
 * NOTE on spacing: where a heading accent directly follows the lead in JSX
 * (no literal space), the lead string carries a trailing space for space-
 * delimited locales (en/fr/ko) and none for CJK (zh/ja). Keep them.
 */
const homeContent = {
  content: {
    hero: {
      titleSoft: t({
        en: 'Put your Agent',
        fr: 'Mettez votre Agent',
        ja: 'Agent を、',
        ko: 'Agent를,',
        'zh-Hans': '把 Agent，',
        'zh-Hant': '把 Agent，',
      }),
      titleMain: t({
        en: 'inside ',
        fr: 'dans ',
        ja: '自分の',
        ko: '내 ',
        'zh-Hans': '装进',
        'zh-Hant': '裝進',
      }),
      titleAccent: t({
        en: 'your own server',
        fr: 'votre propre serveur',
        ja: 'サーバーへ',
        ko: '서버 안에',
        'zh-Hans': '自己的服务器',
        'zh-Hant': '自己的伺服器',
      }),
      subtitleStrong: t({
        en: 'OxyGenie is a private, self-hosted Claude-Agent workspace for small teams.',
        fr: 'OxyGenie est un espace de travail Claude-Agent privé et auto-hébergé pour les petites équipes.',
        ja: 'OxyGenie は、小さなチーム向けのプライベートなセルフホスト型 Claude-Agent ワークスペースです。',
        ko: 'OxyGenie는 소규모 팀을 위한 프라이빗 셀프호스팅 Claude-Agent 워크스페이스입니다.',
        'zh-Hans': 'OxyGenie 是面向小团队的私有化 Claude-Agent 工作台。',
        'zh-Hant': 'OxyGenie 是面向小團隊的私有化 Claude-Agent 工作台。',
      }),
      subtitle: t({
        en: 'Self-hosted, single-org, multi-user, fully sandboxed — your team runs real, capable agents on its own machines: code execution, internal tools, live preview, all inside sandbox guardrails.',
        fr: 'Auto-hébergé, mono-organisation, multi-utilisateurs, entièrement isolé — votre équipe exécute de vrais agents capables sur ses propres machines : exécution de code, outils internes, aperçu en direct, le tout dans des garde-fous de bac à sable.',
        ja: 'セルフホスト・単一組織・マルチユーザー・完全サンドボックス——チームは自分のマシン上で、本当に役立つエージェントを安全に動かせます：コード実行、社内ツール接続、ライブプレビュー、すべてサンドボックスのガードレール内で。',
        ko: '셀프호스팅·단일 조직·멀티 유저·완전 샌드박스——팀이 자체 머신에서 실제로 일하는 에이전트를 안전하게 실행합니다: 코드 실행, 내부 도구 연결, 라이브 프리뷰까지 모두 샌드박스 가드레일 안에서.',
        'zh-Hans': '自托管、单组织、多用户、全沙盒——团队在自己的机器上，安全地跑起真正能干活的 Agent：代码执行、连内网工具、真预览，全在沙盒护栏内。',
        'zh-Hant': '自託管、單組織、多使用者、全沙盒——團隊在自己的機器上，安全地跑起真正能幹活的 Agent：程式碼執行、連內網工具、真預覽，全在沙盒護欄內。',
      }),
      ctaPrimary: t({
        en: 'Open workspace',
        fr: "Ouvrir l'espace",
        ja: 'ワークスペースを開く',
        ko: '워크스페이스 열기',
        'zh-Hans': '进入工作台',
        'zh-Hant': '進入工作台',
      }),
      ctaSecondary: t({
        en: 'View source · GitHub',
        fr: 'Voir le code · GitHub',
        ja: 'ソースを見る · GitHub',
        ko: '소스 보기 · GitHub',
        'zh-Hans': '查看源码 · GitHub',
        'zh-Hant': '查看原始碼 · GitHub',
      }),
      metaDeploy: t({
        en: 'one-command deploy',
        fr: 'déploiement en une commande',
        ja: 'ワンコマンド配備',
        ko: '원커맨드 배포',
        'zh-Hans': '一键部署',
        'zh-Hant': '一鍵部署',
      }),
      metaModels: t({
        en: 'one gateway, many models',
        fr: 'une passerelle, plusieurs modèles',
        ja: 'ひとつのゲートウェイで複数モデル',
        ko: '하나의 게이트웨이, 여러 모델',
        'zh-Hans': '一个网关随切',
        'zh-Hant': '一個網關隨切',
      }),
      metaSandbox: t({
        en: 'per-session isolation',
        fr: 'isolation par session',
        ja: 'セッション単位の隔離',
        ko: '세션별 격리',
        'zh-Hans': '沙盒隔离',
        'zh-Hant': '沙盒隔離',
      }),
    },
    concept: {
      h2Soft: t({
        en: 'Not one more cloud AI assistant —',
        fr: 'Pas un assistant IA cloud de plus —',
        ja: 'もう一つのクラウド AI アシスタントではなく、',
        ko: '또 하나의 클라우드 AI 어시스턴트가 아니라,',
        'zh-Hans': '不是又一个云端 AI 助手，',
        'zh-Hant': '不是又一個雲端 AI 助手，',
      }),
      h2Lead: t({
        en: 'but an',
        fr: 'mais un',
        ja: 'あなたのサーバールームで動く',
        ko: '당신의 서버룸에서 돌아가는',
        'zh-Hans': '而是一台跑在你机房里的',
        'zh-Hant': '而是一台跑在你機房裡的',
      }),
      h2Accent: t({
        en: 'Agent workspace that runs in your own server room.',
        fr: 'espace de travail Agent qui tourne dans votre propre salle serveur.',
        ja: 'Agent ワークスペース。',
        ko: 'Agent 워크스페이스.',
        'zh-Hans': 'Agent 工作台',
        'zh-Hant': 'Agent 工作台',
      }),
      bodyP1: t({
        en: 'Public SaaS hands your data, keys and code to someone else. OxyGenie flips it: the image runs on your own server — data stays in, keys stay private, and capability stays full.',
        fr: "Le SaaS public confie vos données, vos clés et votre code à un tiers. OxyGenie inverse la logique : l'image tourne sur votre propre serveur — les données restent chez vous, les clés restent privées, et la puissance reste intacte.",
        ja: 'パブリック SaaS は、あなたのデータ・鍵・コードを他人に預けます。OxyGenie は逆です：イメージは自分のサーバーで動き、データは外に出ず、鍵も漏れず、それでいて機能は何ひとつ削られません。',
        ko: '퍼블릭 SaaS는 당신의 데이터·키·코드를 남에게 맡깁니다. OxyGenie는 그 반대입니다: 이미지가 당신의 서버에서 돌아가 데이터는 나가지 않고 키도 새지 않으며, 그러면서도 기능은 그대로입니다.',
        'zh-Hans': '公网 SaaS 把你的数据、密钥、代码都交到别人手里。OxyGenie 反过来：镜像在你自己的服务器上跑，数据不出门、密钥不外泄，能力却一点不少。',
        'zh-Hant': '公網 SaaS 把你的資料、密鑰、程式碼都交到別人手裡。OxyGenie 反過來：鏡像在你自己的伺服器上跑，資料不出門、密鑰不外洩，能力卻一點不少。',
      }),
      bodyP2: t({
        en: 'The threat model is semi-trusted colleagues, not anonymous attackers — so powerful features (stdio MCP, internal access, code execution) are core, legitimate uses, held by sandbox + warning guardrails rather than banned outright.',
        fr: "Le modèle de menace, ce sont des collègues semi-fiables, pas des attaquants anonymes — les fonctions puissantes (MCP stdio, accès interne, exécution de code) sont donc des usages centraux et légitimes, encadrés par un bac à sable et des avertissements plutôt qu'interdits.",
        ja: '脅威モデルは「半分信頼できる同僚」であって、匿名の攻撃者ではありません——だから強力な機能（stdio MCP、社内アクセス、コード実行）は正当なコア用途であり、禁止ではなくサンドボックス＋警告のガードレールで守ります。',
        ko: '위협 모델은 익명의 공격자가 아니라 ‘반쯤 신뢰할 수 있는 동료’입니다——그래서 강력한 기능(stdio MCP, 내부 접근, 코드 실행)은 정당한 핵심 용도이며, 금지가 아니라 샌드박스 + 경고 가드레일로 지킵니다.',
        'zh-Hans': '威胁模型是半可信的同事，不是匿名攻击者——所以强力功能（stdio MCP、连内网、代码执行）是合法核心用途，用沙盒 + 警示护栏守住，而不是一禁了之。',
        'zh-Hant': '威脅模型是半可信的同事，不是匿名攻擊者——所以強力功能（stdio MCP、連內網、程式碼執行）是合法核心用途，用沙盒 + 警示護欄守住，而不是一禁了之。',
      }),
      p1Title: t({
        en: 'Private by deployment',
        fr: 'Privé par déploiement',
        ja: 'デプロイで私有化',
        ko: '배포로 프라이빗하게',
        'zh-Hans': '私有部署，数据不出门',
        'zh-Hant': '私有部署，資料不出門',
      }),
      p1Desc: t({
        en: 'One-command Docker. Single org, multiple trusted users. The image runs on the machine you choose — works out of the box.',
        fr: "Docker en une commande. Une organisation, plusieurs utilisateurs de confiance. L'image tourne sur la machine de votre choix — prête à l'emploi.",
        ja: 'Docker ワンコマンド。単一組織・複数の信頼できるユーザー。イメージは選んだマシンで動き、すぐに使えます。',
        ko: 'Docker 원커맨드. 단일 조직, 여러 신뢰된 사용자. 이미지는 선택한 머신에서 돌아가며 바로 사용할 수 있습니다.',
        'zh-Hans': 'Docker 一键起跑，单组织、组织内多个可信用户。镜像跑在你选的机器上，开箱即用。',
        'zh-Hant': 'Docker 一鍵起跑，單組織、組織內多個可信使用者。鏡像跑在你選的機器上，開箱即用。',
      }),
      p2Title: t({
        en: 'One gateway, switch models',
        fr: 'Une passerelle, changez de modèle',
        ja: 'ひとつのゲートウェイでモデル切替',
        ko: '하나의 게이트웨이, 모델 전환',
        'zh-Hans': '一个网关，多模型随切',
        'zh-Hant': '一個網關，多模型隨切',
      }),
      p2Desc: t({
        en: 'Default ARK (Volcengine) gateway; switch GLM / Doubao / MiniMax in one click. The menu only shows models that probe healthy.',
        fr: "Passerelle ARK (Volcengine) par défaut ; basculez entre GLM / Doubao / MiniMax en un clic. Le menu n'affiche que les modèles dont la sonde est saine.",
        ja: '既定は ARK（火山）ゲートウェイ。GLM / Doubao / MiniMax をワンクリックで切替。メニューにはヘルスチェックを通過したモデルだけが並びます。',
        ko: '기본은 ARK(볼케이노) 게이트웨이. GLM / Doubao / MiniMax를 한 번에 전환. 메뉴에는 헬스 체크를 통과한 모델만 표시됩니다.',
        'zh-Hans': '默认 ARK（火山）网关，GLM / Doubao / MiniMax 一键切换。菜单只显示探活健康的模型。',
        'zh-Hant': '預設 ARK（火山）網關，GLM / Doubao / MiniMax 一鍵切換。選單只顯示探活健康的模型。',
      }),
      p3Title: t({
        en: 'Per-session sandbox',
        fr: 'Bac à sable par session',
        ja: 'セッション単位のサンドボックス',
        ko: '세션별 샌드박스',
        'zh-Hans': '每会话独立沙盒',
        'zh-Hant': '每會話獨立沙盒',
      }),
      p3Desc: t({
        en: 'Per-session config dir + child-process isolation + live preview subdomains. Powerful capability stays inside the guardrails — defense in depth.',
        fr: "Répertoire de config par session + isolation par sous-processus + sous-domaines d'aperçu en direct. La puissance reste dans les garde-fous — défense en profondeur.",
        ja: 'セッションごとの設定ディレクトリ＋子プロセス隔離＋ライブプレビュー用サブドメイン。強力な機能はガードレールの内側に——多層防御です。',
        ko: '세션별 설정 디렉터리 + 자식 프로세스 격리 + 라이브 프리뷰 서브도메인. 강력한 기능은 가드레일 안에——심층 방어입니다.',
        'zh-Hans': 'per-session 配置目录 + 子进程隔离 + 真预览子域名。强力能力关在护栏里，纵深防御。',
        'zh-Hant': 'per-session 設定目錄 + 子行程隔離 + 真預覽子網域。強力能力關在護欄裡，縱深防禦。',
      }),
    },
    features: {
      heading: t({
        en: 'One workspace,',
        fr: 'Un espace de travail,',
        ja: '一つのワークスペースに、',
        ko: '하나의 워크스페이스에,',
        'zh-Hans': '一个工作台，',
        'zh-Hant': '一個工作台，',
      }),
      headingAccent: t({
        en: 'everything you need.',
        fr: "tout ce qu'il vous faut.",
        ja: '必要なものすべて。',
        ko: '필요한 모든 것.',
        'zh-Hans': '该有的都有',
        'zh-Hant': '該有的都有',
      }),
      f1Title: t({ en: 'Agent Chat', fr: 'Agent Chat', ja: 'Agent Chat', ko: 'Agent Chat', 'zh-Hans': 'Agent Chat', 'zh-Hant': 'Agent Chat' }),
      f1Desc: t({
        en: 'Persistent WebSocket, native session resume, live tool-call visualization — the full Claude-Agent experience.',
        fr: "WebSocket persistant, reprise de session native, visualisation des appels d'outils en direct — l'expérience Claude-Agent complète.",
        ja: '永続 WebSocket、ネイティブなセッション再開、ツール呼び出しのライブ可視化——Claude-Agent の体験をフルで。',
        ko: '지속 WebSocket, 네이티브 세션 재개, 실시간 도구 호출 시각화——완전한 Claude-Agent 경험.',
        'zh-Hans': '持久 WebSocket 连接、原生会话恢复、工具调用实时可视化——完整的 Claude-Agent 交互体验。',
        'zh-Hant': '持久 WebSocket 連線、原生會話恢復、工具呼叫即時視覺化——完整的 Claude-Agent 互動體驗。',
      }),
      f2Title: t({
        en: 'Curated Skills',
        fr: 'Skills sélectionnés',
        ja: 'キュレートされた Skills',
        ko: '큐레이션된 Skills',
        'zh-Hans': 'Skills 策展',
        'zh-Hant': 'Skills 策展',
      }),
      f2Desc: t({
        en: 'A team-curated skill set, toggled on the spot. A hand-picked set for your own team — not a public rated marketplace.',
        fr: "Un ensemble de skills sélectionné par l'équipe, activable à la volée. Une sélection pour votre équipe — pas une place de marché publique notée.",
        ja: 'チームが厳選したスキル集を、その場でオン/オフ。自分たちのための精選であって、評価付きの公開マーケットではありません。',
        ko: '팀이 엄선한 스킬 세트를 즉석에서 켜고 끄기. 평점 달린 공개 마켓이 아니라, 우리 팀을 위한 선별입니다.',
        'zh-Hans': '团队精选的技能集，启停即生效。给团队自己用的精选，不是公开评分市场。',
        'zh-Hant': '團隊精選的技能集，啟停即生效。給團隊自己用的精選，不是公開評分市場。',
      }),
      f3Title: t({
        en: 'Artifacts · live preview',
        fr: 'Artifacts · aperçu en direct',
        ja: 'Artifacts · ライブプレビュー',
        ko: 'Artifacts · 라이브 프리뷰',
        'zh-Hans': 'Artifacts · 真预览',
        'zh-Hant': 'Artifacts · 真預覽',
      }),
      f3Desc: t({
        en: 'Live preview for HTML / React / SVG on dedicated subdomains, spun up on demand and reaped automatically.',
        fr: "Aperçu en direct pour HTML / React / SVG sur des sous-domaines dédiés, créés à la demande et recyclés automatiquement.",
        ja: 'HTML / React / SVG を専用サブドメインでライブプレビュー。必要なときに起動し、自動で回収します。',
        ko: 'HTML / React / SVG를 전용 서브도메인에서 라이브 프리뷰. 필요할 때 띄우고 자동으로 회수합니다.',
        'zh-Hans': 'HTML / React / SVG 实时预览，独立预览子域名，按需起停、自动回收。',
        'zh-Hant': 'HTML / React / SVG 即時預覽，獨立預覽子網域，按需起停、自動回收。',
      }),
      f4Title: t({ en: 'Knowledge Base', fr: 'Knowledge Base', ja: 'Knowledge Base', ko: 'Knowledge Base', 'zh-Hans': 'Knowledge Base', 'zh-Hant': 'Knowledge Base' }),
      f4Desc: t({
        en: 'Upload and manage documents as the session knowledge base, so the agent understands your project.',
        fr: "Importez et gérez des documents comme base de connaissances de session, pour que l'agent comprenne votre projet.",
        ja: 'ドキュメントをアップロードしてセッションのナレッジベースとして管理。エージェントがあなたのプロジェクトを理解します。',
        ko: '문서를 업로드해 세션 지식베이스로 관리하면, 에이전트가 당신의 프로젝트를 이해합니다.',
        'zh-Hans': '上传与管理文档，作为会话的上下文知识库，让 Agent 读懂你的项目。',
        'zh-Hant': '上傳與管理文件，作為會話的上下文知識庫，讓 Agent 讀懂你的專案。',
      }),
      f5Title: t({
        en: 'Model switching',
        fr: 'Changement de modèle',
        ja: 'モデル切替',
        ko: '모델 전환',
        'zh-Hans': '多模型切换',
        'zh-Hant': '多模型切換',
      }),
      f5Desc: t({
        en: 'Pick a model per session, with a backend health board. Send to an unhealthy model and it errors — never a silent fallback.',
        fr: "Choisissez un modèle par session, avec un tableau de santé côté serveur. Envoyer vers un modèle en mauvaise santé déclenche une erreur — jamais de repli silencieux.",
        ja: 'セッションごとにモデルを選択。バックエンドのヘルスボード付き。不健全なモデルに送ると黙って代替せず、エラーになります。',
        ko: '세션마다 모델 선택, 백엔드 헬스 보드 제공. 비정상 모델로 보내면 조용히 대체하지 않고 오류를 냅니다.',
        'zh-Hans': '每会话独立选模型，后台健康看板，选了不健康的模型发送即报错——绝不静默兜底。',
        'zh-Hant': '每會話獨立選模型，後台健康看板，選了不健康的模型發送即報錯——絕不靜默兜底。',
      }),
      f6Title: t({ en: 'Session · Sandbox', fr: 'Session · Sandbox', ja: 'Session · Sandbox', ko: 'Session · Sandbox', 'zh-Hans': 'Session · Sandbox', 'zh-Hant': 'Session · Sandbox' }),
      f6Desc: t({
        en: 'Per-session working dir and config, child-process isolation — users within the org never cross-contaminate.',
        fr: "Répertoire de travail et config par session, isolation par sous-processus — les utilisateurs de l'organisation ne se contaminent jamais.",
        ja: 'セッションごとの作業ディレクトリと設定、子プロセス隔離——組織内のユーザー同士が干渉しません。',
        ko: '세션별 작업 디렉터리와 설정, 자식 프로세스 격리——조직 내 사용자끼리 서로 간섭하지 않습니다.',
        'zh-Hans': '每会话独立工作目录与配置，子进程隔离，组织内用户互不串扰。',
        'zh-Hant': '每會話獨立工作目錄與設定，子行程隔離，組織內使用者互不串擾。',
      }),
    },
    product: {
      heading: t({
        en: 'Sessions on the left,',
        fr: 'Les sessions à gauche,',
        ja: '左にセッション、',
        ko: '왼쪽엔 세션,',
        'zh-Hans': '会话在左，',
        'zh-Hant': '會話在左，',
      }),
      headingAccent: t({
        en: 'output on the right.',
        fr: 'la sortie à droite.',
        ja: '右に成果物。',
        ko: '오른쪽엔 산출물.',
        'zh-Hans': '产出在右',
        'zh-Hant': '產出在右',
      }),
    },
    models: {
      heading: t({
        en: 'One gateway,',
        fr: 'Une passerelle,',
        ja: 'ひとつのゲートウェイで、',
        ko: '하나의 게이트웨이로,',
        'zh-Hans': '一个网关，',
        'zh-Hant': '一個網關，',
      }),
      headingAccent: t({
        en: 'many models',
        fr: 'plusieurs modèles',
        ja: '複数モデルを',
        ko: '여러 모델을',
        'zh-Hans': '多个模型',
        'zh-Hant': '多個模型',
      }),
      headingTail: t({
        en: ', switch at will.',
        fr: ', à la demande.',
        ja: '、自在に切替。',
        ko: ', 자유롭게 전환.',
        'zh-Hans': '，随你切。',
        'zh-Hant': '，隨你切。',
      }),
      lede: t({
        en: 'Any Anthropic-protocol model — whatever account or gateway it comes from — is switchable as long as it works. The backend probes; the menu only lists the healthy ones.',
        fr: "Tout modèle compatible protocole Anthropic — quel que soit le compte ou la passerelle — est commutable dès lors qu'il fonctionne. Le backend sonde ; le menu ne liste que ceux en bonne santé.",
        ja: 'Anthropic プロトコル対応のモデルなら、どのアカウント・ゲートウェイ由来でも、使えるかぎり切替可能。バックエンドが探活し、メニューには健全なものだけが並びます。',
        ko: 'Anthropic 프로토콜을 지원하는 모델이면 어떤 계정·게이트웨이에서 왔든, 동작하기만 하면 전환 가능. 백엔드가 헬스 체크하고 메뉴에는 정상인 것만 표시됩니다.',
        'zh-Hans': '只要是支持 Anthropic 协议的模型，不管来自哪个账号或网关，能用就能切。后台探活，菜单只放健康的。',
        'zh-Hant': '只要是支援 Anthropic 協議的模型，不管來自哪個帳號或網關，能用就能切。後台探活，選單只放健康的。',
      }),
    },
    deploy: {
      heading: t({
        en: 'Clone, ',
        fr: 'Clonez, ',
        ja: 'クローンして、',
        ko: '클론하고, ',
        'zh-Hans': '克隆、',
        'zh-Hant': '克隆、',
      }),
      headingAccent: t({
        en: 'and go',
        fr: "et c'est parti",
        ja: '起動',
        ko: '실행',
        'zh-Hans': '起跑',
        'zh-Hant': '起跑',
      }),
      headingTail: t({
        en: ' — it really is that simple.',
        fr: " — c'est vraiment aussi simple.",
        ja: '。本当に、これだけ。',
        ko: '까지. 정말 이게 전부입니다.',
        'zh-Hans': '，就这么简单。',
        'zh-Hant': '，就這麼簡單。',
      }),
      body: t({
        en: 'Optimized for "one-command Docker, works out of the box for a team", not elastic public-SaaS scale. Open-source, MIT, self-hosted — the image runs on your server, and your data and keys stay in your own hands.',
        fr: "Optimisé pour « Docker en une commande, prêt à l'emploi pour une équipe », pas pour l'échelle d'un SaaS public élastique. Open-source, MIT, auto-hébergé — l'image tourne sur votre serveur, et vos données comme vos clés restent entre vos mains.",
        ja: '「チームが Docker ワンコマンドで起動、すぐ使える」ことに最適化——弾力的な公開 SaaS 規模のためではありません。オープンソース・MIT・セルフホスト——イメージは自分のサーバーで動き、データも鍵も自分の手の中に。',
        ko: '“팀이 Docker 원커맨드로 기동, 바로 사용”에 최적화——탄력적인 공개 SaaS 규모를 위한 것이 아닙니다. 오픈소스·MIT·셀프호스팅——이미지는 당신의 서버에서 돌아가고, 데이터와 키는 모두 당신 손안에.',
        'zh-Hans': '为「团队 Docker 一键起跑、开箱即用」而优化，而非弹性公网 SaaS 规模。开源、MIT、自托管——镜像在你的服务器上跑，从此数据与密钥都在自己手里。',
        'zh-Hant': '為「團隊 Docker 一鍵起跑、開箱即用」而最佳化，而非彈性公網 SaaS 規模。開源、MIT、自託管——鏡像在你的伺服器上跑，從此資料與密鑰都在自己手裡。',
      }),
      ctaPrimary: t({
        en: 'Deploy docs',
        fr: 'Docs de déploiement',
        ja: 'デプロイ手順',
        ko: '배포 문서',
        'zh-Hans': '部署文档',
        'zh-Hant': '部署文件',
      }),
      ctaSecondary: t({
        en: 'GitHub · foreveryh/oxygenie',
        fr: 'GitHub · foreveryh/oxygenie',
        ja: 'GitHub · foreveryh/oxygenie',
        ko: 'GitHub · foreveryh/oxygenie',
        'zh-Hans': 'GitHub · foreveryh/oxygenie',
        'zh-Hant': 'GitHub · foreveryh/oxygenie',
      }),
    },
    footer: {
      bigPre: t({
        en: 'Time to ',
        fr: 'Il est temps de ',
        ja: 'さあ、',
        ko: '이제 ',
        'zh-Hans': '在你的服务器上，',
        'zh-Hant': '在你的伺服器上，',
      }),
      bigAccent: t({
        en: 'launch',
        fr: 'lancer',
        ja: '起動だ',
        ko: '띄울 시간',
        'zh-Hans': '起跑',
        'zh-Hant': '起跑',
      }),
    },
  },
  key: 'home',
} satisfies Dictionary;

export default homeContent;
