import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Marketing page content dictionary
 * Contains landing page, pricing, and promotional content
 */
const marketingContent = {
  content: {
    hero: {
      badge: t({
        en: 'Claude Agent SDK + Zhipu AI GLM-5.0',
        'zh-Hans': 'Claude Agent SDK + 智谱 AI GLM-5.0',
        fr: 'Claude Agent SDK + Zhipu AI GLM-5.0',
        ja: 'Claude Agent SDK + Zhipu AI GLM-5.0',
        ko: 'Claude Agent SDK + Zhipu AI GLM-5.0',
        'zh-Hant': 'Claude Agent SDK + 智譜 AI GLM-5.0',
      }),
      title: t({
        en: 'Claude Desktop-Style Agent Chat',
        'zh-Hans': 'Claude 桌面风格 Agent Chat',
        fr: 'Claude Chat type Desktop',
        ja: 'Claude デスクトップスタイル Agent Chat',
        ko: 'Claude 데스크톱 스타일 Agent Chat',
        'zh-Hant': 'Claude 桌面風格 Agent Chat',
      }),
      subtitle: t({
        en: 'A full-featured AI agent interface powered by Zhipu AI GLM-5.0. Features Skills Store, Artifacts, Knowledge Base, and Session Management via WebSocket.',
        'zh-Hans': '由智谱 AI GLM-5.0 驱动的全功能 AI Agent 界面。支持技能商店、成果物、知识库和基于 WebSocket 的会话管理。',
        fr: 'Interface agent IA complète propulsée par Zhipu AI GLM-5.0. Skills Store, Artifacts, base de connaissances et sessions via WebSocket.',
        ja: 'Zhipu AI GLM-5.0 搭載のフル機能 AI Agent インターフェース。Skills Store、Artifacts、ナレッジベース、WebSocket によるセッション管理。',
        ko: 'Zhipu AI GLM-5.0 기반 풀기능 AI Agent 인터페이스. Skills Store, Artifacts, 지식베이스, WebSocket 세션 관리.',
        'zh-Hant': '由智譜 AI GLM-5.0 驅動的全功能 AI Agent 介面。支援技能商店、成果物、知識庫與 WebSocket 會話管理。',
      }),
      primaryButton: t({
        en: 'Try DeeptoAI',
        'zh-Hans': '试用 DeeptoAI',
        fr: 'Essayer DeeptoAI',
        ja: 'DeeptoAI を試す',
        ko: 'DeeptoAI 체험',
        'zh-Hant': '試用 DeeptoAI',
      }),
      secondaryButton: t({
        en: 'View on GitHub',
        'zh-Hans': '在 GitHub 上查看',
        fr: 'Voir sur GitHub',
        ja: 'GitHub で見る',
        ko: 'GitHub에서 보기',
        'zh-Hant': '在 GitHub 上查看',
      }),
      poweredBy: t({
        en: 'Powered by',
        'zh-Hans': '由以下技术提供支持',
        fr: 'Propulsé par',
        ja: '提供',
        ko: '제공',
        'zh-Hant': '由以下技術提供支援',
      }),
      poweredByLine: t({
        en: 'Zhipu AI GLM 5.0',
        'zh-Hans': '智谱 AI GLM 5.0',
        fr: 'Zhipu AI GLM 5.0',
        ja: 'Zhipu AI GLM 5.0',
        ko: 'Zhipu AI GLM 5.0',
        'zh-Hant': '智譜 AI GLM 5.0',
      }),
    },
    features: {
      title: t({
        en: 'Full-Featured Claude Agent Experience',
        'zh-Hans': '全功能的 Claude Agent 体验',
        fr: 'Expérience Claude Agent complète',
        ja: 'フル機能 Claude Agent 体験',
        ko: '풀기능 Claude Agent 경험',
        'zh-Hant': '全功能的 Claude Agent 體驗',
      }),
      subtitle: t({
        en: 'Everything you need from Claude Desktop, plus Skills Store and more',
        'zh-Hans': '拥有 Claude Desktop 的一切，外加技能商店等更多功能',
        fr: 'Tout Claude Desktop, plus Skills Store et plus',
        ja: 'Claude Desktop のすべてに加え、Skills Store など',
        ko: 'Claude Desktop의 모든 기능 + Skills Store 등',
        'zh-Hant': '擁有 Claude Desktop 的一切，外加技能商店等更多功能',
      }),
      deeptoaiChat: {
        title: t({
          en: 'DeeptoAI Agent Chat',
          'zh-Hans': 'DeeptoAI Agent Chat',
          fr: 'DeeptoAI Agent Chat',
          ja: 'DeeptoAI Agent Chat',
          ko: 'DeeptoAI Agent Chat',
          'zh-Hant': 'DeeptoAI Agent Chat',
        }),
        description: t({
          en: 'Full Claude Desktop replica with Claude Agent SDK integration',
          'zh-Hans': '完全复刻 Claude Desktop，集成 Claude Agent SDK',
          fr: 'Réplique Claude Desktop avec Claude Agent SDK',
          ja: 'Claude Desktop 完全再現、Claude Agent SDK 統合',
          ko: 'Claude Desktop 완전 재현, Claude Agent SDK 통합',
          'zh-Hant': '完整復刻 Claude Desktop，整合 Claude Agent SDK',
        }),
      },
      skillsStore: {
        title: t({
          en: 'Skills Store',
          'zh-Hans': '技能商店',
          fr: 'Boutique Skills',
          ja: 'スキルストア',
          ko: '스킬 스토어',
          'zh-Hant': '技能商店',
        }),
        description: t({
          en: 'Enable/disable custom skills to extend agent capabilities dynamically',
          'zh-Hans': '启用/禁用自定义技能以动态扩展 Agent 能力',
          fr: 'Activer/désactiver des skills pour étendre l\'agent',
          ja: 'カスタムスキルの有効/無効でエージェント能力を拡張',
          ko: '커스텀 스킬로 에이전트 능력 동적 확장',
          'zh-Hant': '啟用/停用自訂技能以動態擴展 Agent 能力',
        }),
      },
      artifacts: {
        title: t({
          en: 'Artifacts System',
          'zh-Hans': '成果物系统',
          fr: 'Système Artifacts',
          ja: 'Artifacts システム',
          ko: 'Artifacts 시스템',
          'zh-Hant': '成果物系統',
        }),
        description: t({
          en: 'Support for HTML, Markdown, React, and SVG artifacts with live preview',
          'zh-Hans': '支持 HTML、Markdown、React 和 SVG 成果物，带实时预览',
          fr: 'HTML, Markdown, React, SVG avec aperçu en direct',
          ja: 'HTML、Markdown、React、SVG の Artifacts、ライブプレビュー対応',
          ko: 'HTML, Markdown, React, SVG Artifacts 및 실시간 미리보기',
          'zh-Hant': '支援 HTML、Markdown、React 與 SVG 成果物，即時預覽',
        }),
      },
      knowledgeBase: {
        title: t({
          en: 'Knowledge Base',
          'zh-Hans': '知识库',
          fr: 'Base de connaissances',
          ja: 'ナレッジベース',
          ko: '지식베이스',
          'zh-Hant': '知識庫',
        }),
        description: t({
          en: 'Upload and manage documents for context-aware conversations',
          'zh-Hans': '上传和管理文档以支持上下文感知对话',
          fr: 'Documents pour conversations contextuelles',
          ja: '文脈を考慮した会話のためのドキュメント管理',
          ko: '문맥 인식 대화를 위한 문서 업로드 및 관리',
          'zh-Hant': '上傳與管理文件以支援上下文感知對話',
        }),
      },
      sessionManagement: {
        title: t({
          en: 'Session Management',
          'zh-Hans': '会话管理',
          fr: 'Gestion des sessions',
          ja: 'セッション管理',
          ko: '세션 관리',
          'zh-Hant': '會話管理',
        }),
        description: t({
          en: 'Create, resume, and switch between multiple chat sessions with full history',
          'zh-Hans': '创建、恢复和切换多个聊天会话，保留完整历史',
          fr: 'Créer, reprendre et basculer entre sessions avec historique',
          ja: '複数チャットセッションの作成・再開・切り替え、履歴付き',
          ko: '여러 채팅 세션 생성·재개·전환, 전체 기록 유지',
          'zh-Hant': '建立、恢復與切換多個聊天會話，保留完整歷史',
        }),
      },
      toolVisualization: {
        title: t({
          en: 'Tool Visualization',
          'zh-Hans': '工具可视化',
          fr: 'Visualisation des outils',
          ja: 'ツールの可視化',
          ko: '도구 시각화',
          'zh-Hant': '工具視覺化',
        }),
        description: t({
          en: 'See tool calls, arguments, and results in real-time with detailed feedback',
          'zh-Hans': '实时查看工具调用、参数和结果，带详细反馈',
          fr: 'Appels, arguments et résultats en temps réel',
          ja: 'ツール呼び出し・引数・結果をリアルタイムで詳細表示',
          ko: '도구 호출, 인자, 결과 실시간 상세 피드백',
          'zh-Hant': '即時查看工具呼叫、參數與結果，詳細回饋',
        }),
      },
    },
    techStack: {
      title: t({
        en: 'Production-Ready Tech Stack',
        'zh-Hans': '生产就绪的技术栈',
        fr: 'Stack technique prête pour la prod',
        ja: '本番対応テックスタック',
        ko: '프로덕션 준비 기술 스택',
        'zh-Hant': '生產就緒的技術棧',
      }),
      subtitle: t({
        en: 'Built on proven technologies for reliability and scalability',
        'zh-Hans': '基于经过验证的技术构建，确保可靠性和可扩展性',
        fr: 'Technologies éprouvées pour fiabilité et scalabilité',
        ja: '実績ある技術で信頼性と拡張性を確保',
        ko: '검증된 기술로 안정성과 확장성 확보',
        'zh-Hant': '基於驗證過的技術，確保可靠性與可擴展性',
      }),
      claudeChat: {
        title: t({
          en: 'Claude Chat (Main Feature)',
          'zh-Hans': 'Claude Chat（主要功能）',
          fr: 'Claude Chat (fonctionnalité principale)',
          ja: 'Claude Chat（メイン機能）',
          ko: 'Claude Chat(주요 기능)',
          'zh-Hant': 'Claude Chat（主要功能）',
        }),
        claudeAgentSDK: t({
          en: 'Claude Agent SDK',
          'zh-Hans': 'Claude Agent SDK',
          fr: 'Claude Agent SDK',
          ja: 'Claude Agent SDK',
          ko: 'Claude Agent SDK',
          'zh-Hant': 'Claude Agent SDK',
        }),
        zhipuAi: t({
          en: 'Zhipu AI GLM-5.0',
          'zh-Hans': '智谱 AI GLM-5.0',
          fr: 'Zhipu AI GLM-5.0',
          ja: 'Zhipu AI GLM-5.0',
          ko: 'Zhipu AI GLM-5.0',
          'zh-Hant': '智譜 AI GLM-5.0',
        }),
        websocket: t({
          en: 'WebSocket (real-time)',
          'zh-Hans': 'WebSocket（实时）',
          fr: 'WebSocket (temps réel)',
          ja: 'WebSocket（リアルタイム）',
          ko: 'WebSocket(실시간)',
          'zh-Hant': 'WebSocket（即時）',
        }),
        assistantUi: t({
          en: 'Assistant UI components',
          'zh-Hans': 'Assistant UI 组件',
          fr: 'Composants Assistant UI',
          ja: 'Assistant UI コンポーネント',
          ko: 'Assistant UI 컴포넌트',
          'zh-Hant': 'Assistant UI 元件',
        }),
      },
      additionalFeatures: {
        title: t({
          en: 'Additional Features',
          'zh-Hans': '附加功能',
          fr: 'Fonctionnalités additionnelles',
          ja: '追加機能',
          ko: '추가 기능',
          'zh-Hant': '附加功能',
        }),
        mastraAiChat: t({
          en: 'Mastra AI Chat (SSE-based)',
          'zh-Hans': 'Mastra AI Chat（基于 SSE）',
          fr: 'Mastra AI Chat (SSE)',
          ja: 'Mastra AI Chat（SSEベース）',
          ko: 'Mastra AI Chat(SSE 기반)',
          'zh-Hant': 'Mastra AI Chat（基於 SSE）',
        }),
        betterAuth: t({
          en: 'Better Auth (OAuth + password)',
          'zh-Hans': 'Better Auth（OAuth + 密码）',
          fr: 'Better Auth (OAuth + mot de passe)',
          ja: 'Better Auth（OAuth + パスワード）',
          ko: 'Better Auth(OAuth + 비밀번호)',
          'zh-Hant': 'Better Auth（OAuth + 密碼）',
        }),
        postgresql: t({
          en: 'PostgreSQL + Drizzle ORM',
          'zh-Hans': 'PostgreSQL + Drizzle ORM',
          fr: 'PostgreSQL + Drizzle ORM',
          ja: 'PostgreSQL + Drizzle ORM',
          ko: 'PostgreSQL + Drizzle ORM',
          'zh-Hant': 'PostgreSQL + Drizzle ORM',
        }),
        shadcn: t({
          en: 'shadcn/ui + Tailwind CSS v4',
          'zh-Hans': 'shadcn/ui + Tailwind CSS v4',
          fr: 'shadcn/ui + Tailwind CSS v4',
          ja: 'shadcn/ui + Tailwind CSS v4',
          ko: 'shadcn/ui + Tailwind CSS v4',
          'zh-Hant': 'shadcn/ui + Tailwind CSS v4',
        }),
      },
    },
    architecture: {
      title: t({
        en: 'Two Independent Chat Systems',
        'zh-Hans': '两套独立的聊天系统',
        fr: 'Deux systèmes de chat indépendants',
        ja: '2つの独立したチャットシステム',
        ko: '두 개의 독립 채팅 시스템',
        'zh-Hant': '兩套獨立的聊天系統',
      }),
      subtitle: t({
        en: 'Built for different use cases with optimal architectures',
        'zh-Hans': '为不同用例构建，采用最优架构',
        fr: 'Conçus pour différents cas d\'usage',
        ja: '用途に最適化したアーキテクチャ',
        ko: '용도별 최적 아키텍처',
        'zh-Hant': '為不同用例建構，採用最優架構',
      }),
      deeptoai: {
        badge: t({
          en: 'Main Feature',
          'zh-Hans': '主要功能',
          fr: 'Fonctionnalité principale',
          ja: 'メイン機能',
          ko: '주요 기능',
          'zh-Hant': '主要功能',
        }),
        title: t({
          en: 'DeeptoAI Agent Chat',
          'zh-Hans': 'DeeptoAI Agent Chat',
          fr: 'DeeptoAI Agent Chat',
          ja: 'DeeptoAI Agent Chat',
          ko: 'DeeptoAI Agent Chat',
          'zh-Hant': 'DeeptoAI Agent Chat',
        }),
        description: t({
          en: 'Full-featured agent with WebSocket-based real-time communication',
          'zh-Hans': '全功能 Agent，支持基于 WebSocket 的实时通信',
          fr: 'Agent complet avec WebSocket temps réel',
          ja: 'WebSocket によるリアルタイム通信のフル機能エージェント',
          ko: 'WebSocket 기반 실시간 통신 풀기능 에이전트',
          'zh-Hant': '全功能 Agent，支援 WebSocket 即時通訊',
        }),
        feature1: t({
          en: 'Skills Store for dynamic capabilities',
          'zh-Hans': '技能商店支持动态能力',
          fr: 'Skills Store pour capacités dynamiques',
          ja: '動的機能のためのスキルストア',
          ko: '동적 능력을 위한 스킬 스토어',
          'zh-Hant': '技能商店支援動態能力',
        }),
        feature2: t({
          en: 'Artifacts panel with multiple formats',
          'zh-Hans': '成果物面板支持多种格式',
          fr: 'Panneau Artifacts multi-formats',
          ja: '複数形式対応の Artifacts パネル',
          ko: '다양한 형식의 Artifacts 패널',
          'zh-Hant': '成果物面板支援多種格式',
        }),
        feature3: t({
          en: 'Session management and history',
          'zh-Hans': '会话管理和历史记录',
          fr: 'Gestion des sessions et historique',
          ja: 'セッション管理と履歴',
          ko: '세션 관리 및 기록',
          'zh-Hant': '會話管理與歷史紀錄',
        }),
        feature4: t({
          en: 'Tool call visualization',
          'zh-Hans': '工具调用可视化',
          fr: 'Visualisation des appels outils',
          ja: 'ツール呼び出しの可視化',
          ko: '도구 호출 시각화',
          'zh-Hant': '工具呼叫視覺化',
        }),
        feature5: t({
          en: 'Knowledge Base integration',
          'zh-Hans': '知识库集成',
          fr: 'Intégration base de connaissances',
          ja: 'ナレッジベース連携',
          ko: '지식베이스 연동',
          'zh-Hant': '知識庫整合',
        }),
        feature6: t({
          en: 'Usage statistics tracking',
          'zh-Hans': '使用统计跟踪',
          fr: 'Suivi des statistiques d\'usage',
          ja: '利用統計のトラッキング',
          ko: '사용 통계 추적',
          'zh-Hant': '使用統計追蹤',
        }),
      },
      mastra: {
        badge: t({
          en: 'Secondary',
          'zh-Hans': '次要功能',
          fr: 'Secondaire',
          ja: 'サブ機能',
          ko: '부가 기능',
          'zh-Hant': '次要功能',
        }),
        title: t({
          en: 'Mastra AI Chat',
          'zh-Hans': 'Mastra AI Chat',
          fr: 'Mastra AI Chat',
          ja: 'Mastra AI Chat',
          ko: 'Mastra AI Chat',
          'zh-Hant': 'Mastra AI Chat',
        }),
        description: t({
          en: 'Simple chat interface using Mastra + SSE streaming',
          'zh-Hans': '使用 Mastra + SSE 流式的简单聊天界面',
          fr: 'Interface chat simple Mastra + SSE',
          ja: 'Mastra + SSE ストリーミングのシンプルチャット',
          ko: 'Mastra + SSE 스트리밍 간단 채팅',
          'zh-Hant': '使用 Mastra + SSE 串流的簡易聊天介面',
        }),
        feature1: t({
          en: 'Mastra Agent Framework',
          'zh-Hans': 'Mastra Agent 框架',
          fr: 'Framework Mastra Agent',
          ja: 'Mastra Agent フレームワーク',
          ko: 'Mastra Agent 프레임워크',
          'zh-Hant': 'Mastra Agent 框架',
        }),
        feature2: t({
          en: 'Zhipu AI GLM-5.0 model',
          'zh-Hans': '智谱 AI GLM-5.0 模型',
          fr: 'Modèle Zhipu AI GLM-5.0',
          ja: 'Zhipu AI GLM-5.0 モデル',
          ko: 'Zhipu AI GLM-5.0 모델',
          'zh-Hant': '智譜 AI GLM-5.0 模型',
        }),
        feature3: t({
          en: 'Vercel AI SDK integration',
          'zh-Hans': 'Vercel AI SDK 集成',
          fr: 'Intégration Vercel AI SDK',
          ja: 'Vercel AI SDK 統合',
          ko: 'Vercel AI SDK 연동',
          'zh-Hant': 'Vercel AI SDK 整合',
        }),
        feature4: t({
          en: 'SSE-based streaming',
          'zh-Hans': '基于 SSE 的流式',
          fr: 'Streaming SSE',
          ja: 'SSE ベースのストリーミング',
          ko: 'SSE 기반 스트리밍',
          'zh-Hant': '基於 SSE 的串流',
        }),
        feature5: t({
          en: 'Modern AI Elements UI',
          'zh-Hans': '现代 AI Elements UI',
          fr: 'UI AI Elements moderne',
          ja: 'モダン AI Elements UI',
          ko: '모던 AI Elements UI',
          'zh-Hant': '現代 AI Elements UI',
        }),
        feature6: t({
          en: 'File reading capability',
          'zh-Hans': '文件读取能力',
          fr: 'Lecture de fichiers',
          ja: 'ファイル読み取り機能',
          ko: '파일 읽기 기능',
          'zh-Hant': '檔案讀取能力',
        }),
      },
    },
    cta: {
      title: t({
        en: 'Ready to Try DeeptoAI?',
        'zh-Hans': '准备试用 DeeptoAI？',
        fr: 'Prêt à essayer DeeptoAI ?',
        ja: 'DeeptoAI を試してみませんか？',
        ko: 'DeeptoAI 체험할 준비가 되셨나요?',
        'zh-Hant': '準備試用 DeeptoAI？',
      }),
      subtitle: t({
        en: 'Start chatting with the AI agent powered by Claude Agent SDK and Skills Store',
        'zh-Hans': '开始与由 Claude Agent SDK 和技能商店驱动的 AI Agent 聊天',
        fr: 'Discutez avec l\'agent IA propulsé par Claude Agent SDK et Skills Store',
        ja: 'Claude Agent SDK とスキルストアで動く AI Agent とチャットを開始',
        ko: 'Claude Agent SDK와 스킬 스토어 기반 AI Agent와 채팅 시작',
        'zh-Hant': '開始與由 Claude Agent SDK 和技能商店驅動的 AI Agent 聊天',
      }),
      primaryButton: t({
        en: 'Start Claude Chat',
        'zh-Hans': '开始 Claude Chat',
        fr: 'Démarrer Claude Chat',
        ja: 'Claude Chat を開始',
        ko: 'Claude Chat 시작',
        'zh-Hant': '開始 Claude Chat',
      }),
      secondaryButton: t({
        en: 'Browse Skills',
        'zh-Hans': '浏览技能',
        fr: 'Parcourir les Skills',
        ja: 'スキルを閲覧',
        ko: '스킬 둘러보기',
        'zh-Hant': '瀏覽技能',
      }),
    },
    footer: {
      copyright: t({
        en: '© 2024 Constructa Starter. MIT License.',
        'zh-Hans': '© 2024 Constructa Starter. MIT 许可证。',
        fr: '© 2024 Constructa Starter. Licence MIT.',
        ja: '© 2024 Constructa Starter. MIT ライセンス。',
        ko: '© 2024 Constructa Starter. MIT 라이선스.',
        'zh-Hant': '© 2024 Constructa Starter. MIT 授權條款。',
      }),
      github: t({
        en: 'GitHub',
        'zh-Hans': 'GitHub',
        fr: 'GitHub',
        ja: 'GitHub',
        ko: 'GitHub',
        'zh-Hant': 'GitHub',
      }),
      claudeAgentSDK: t({
        en: 'Claude Agent SDK',
        'zh-Hans': 'Claude Agent SDK',
        fr: 'Claude Agent SDK',
        ja: 'Claude Agent SDK',
        ko: 'Claude Agent SDK',
        'zh-Hant': 'Claude Agent SDK',
      }),
      zhipuAi: t({
        en: 'Zhipu AI',
        'zh-Hans': '智谱 AI',
        fr: 'Zhipu AI',
        ja: 'Zhipu AI',
        ko: 'Zhipu AI',
        'zh-Hant': '智譜 AI',
      }),
      assistantUi: t({
        en: 'Assistant UI',
        'zh-Hans': 'Assistant UI',
        fr: 'Assistant UI',
        ja: 'Assistant UI',
        ko: 'Assistant UI',
        'zh-Hant': 'Assistant UI',
      }),
    },
    pricing: {
      hero: {
        badge: t({
          en: 'Simple & Transparent',
          'zh-Hans': '简单透明',
          fr: 'Simple et transparent',
          ja: 'シンプル＆透明',
          ko: '간단하고 투명',
          'zh-Hant': '簡單透明',
        }),
        title: t({
          en: 'AI Starter SaaS Kit',
          'zh-Hans': 'AI Starter SaaS Kit',
          fr: 'AI Starter SaaS Kit',
          ja: 'AI Starter SaaS Kit',
          ko: 'AI Starter SaaS Kit',
          'zh-Hant': 'AI Starter SaaS Kit',
        }),
        titleHighlight: t({
          en: 'Pricing Plans',
          'zh-Hans': '定价方案',
          fr: 'Plans tarifaires',
          ja: '料金プラン',
          ko: '요금 플랜',
          'zh-Hant': '定價方案',
        }),
        subtitle: t({
          en: 'Choose the perfect plan for your AI development journey. From free exploration to enterprise-grade solutions.',
          'zh-Hans': '为您的 AI 开发之旅选择完美的计划。从免费探索到企业级解决方案。',
          fr: 'Choisissez le plan adapté à votre projet IA. De l\'exploration gratuite à l\'entreprise.',
          ja: 'AI 開発に最適なプランを選択。無料からエンタープライズまで。',
          ko: 'AI 개발에 맞는 플랜을 선택하세요. 무료 체험부터 엔터프라이즈까지.',
          'zh-Hant': '為您的 AI 開發之旅選擇方案。從免費試用到企業級方案。',
        }),
      },
      plans: {
        free: {
          name: t({
            en: 'Free',
            'zh-Hans': '免费',
            fr: 'Gratuit',
            ja: '無料',
            ko: '무료',
            'zh-Hant': '免費',
          }),
          price: t({
            en: '$0',
            'zh-Hans': '¥0',
            fr: '0 €',
            ja: '¥0',
            ko: '₩0',
            'zh-Hant': '¥0',
          }),
          period: t({
            en: '',
            'zh-Hans': '',
            fr: '',
            ja: '',
            ko: '',
            'zh-Hant': '',
          }),
          description: t({
            en: 'Perfect for getting started with AI development',
            'zh-Hans': '非常适合开始 AI 开发',
            fr: 'Idéal pour démarrer avec l\'IA',
            ja: 'AI 開発の入門に最適',
            ko: 'AI 개발 시작에 적합',
            'zh-Hant': '非常適合開始 AI 開發',
          }),
          feature1: t({
            en: 'Basic access to AI tools',
            'zh-Hans': 'AI 工具的基础访问',
            fr: 'Accès de base aux outils IA',
            ja: 'AI ツールの基本アクセス',
            ko: 'AI 도구 기본 접근',
            'zh-Hant': 'AI 工具的基礎存取',
          }),
          feature2: t({
            en: 'Limited API usage',
            'zh-Hans': '有限的 API 使用',
            fr: 'Utilisation API limitée',
            ja: 'API 利用制限あり',
            ko: '제한된 API 사용',
            'zh-Hant': '有限的 API 使用',
          }),
          feature3: t({
            en: 'Community support',
            'zh-Hans': '社区支持',
            fr: 'Support communautaire',
            ja: 'コミュニティサポート',
            ko: '커뮤니티 지원',
            'zh-Hant': '社群支援',
          }),
          feature4: t({
            en: 'Core starter templates',
            'zh-Hans': '核心启动器模板',
            fr: 'Templates de démarrage',
            ja: 'コアスターターテンプレート',
            ko: '핵심 스타터 템플릿',
            'zh-Hant': '核心啟動器範本',
          }),
          feature5: t({
            en: 'Basic documentation',
            'zh-Hans': '基础文档',
            fr: 'Documentation de base',
            ja: '基本ドキュメント',
            ko: '기본 문서',
            'zh-Hant': '基礎文件',
          }),
          buttonText: t({
            en: 'Start Free',
            'zh-Hans': '免费开始',
            fr: 'Commencer gratuitement',
            ja: '無料で開始',
            ko: '무료로 시작',
            'zh-Hant': '免費開始',
          }),
        },
        tier1: {
          name: t({
            en: 'Tier 1',
            'zh-Hans': '一级计划',
            fr: 'Niveau 1',
            ja: 'ティア1',
            ko: '티어 1',
            'zh-Hant': '一級方案',
          }),
          price: t({
            en: '$350',
            'zh-Hans': '¥2,500',
            fr: '350 $',
            ja: '¥2,500',
            ko: '$350',
            'zh-Hant': '¥2,500',
          }),
          period: t({
            en: '/year',
            'zh-Hans': '/年',
            fr: '/an',
            ja: '/年',
            ko: '/년',
            'zh-Hant': '/年',
          }),
          description: t({
            en: 'For developers ready to build production apps',
            'zh-Hans': '适合准备构建生产应用的开发者',
            fr: 'Pour développeurs prêts pour la production',
            ja: '本番アプリ構築準備ができた開発者向け',
            ko: '프로덕션 앱 구축 준비된 개발자용',
            'zh-Hant': '適合準備建構正式環境應用的開發者',
          }),
          badge: t({
            en: 'Most Popular',
            'zh-Hans': '最受欢迎',
            fr: 'Le plus populaire',
            ja: '人気No.1',
            ko: '인기',
            'zh-Hant': '最受歡迎',
          }),
          feature1: t({
            en: 'All Free tier features',
            'zh-Hans': '免费计划的所有功能',
            fr: 'Toutes les fonctionnalités Free',
            ja: '無料プランの全機能',
            ko: '무료 플랜 전체 기능',
            'zh-Hant': '免費方案的所有功能',
          }),
          feature2: t({
            en: 'Priority support',
            'zh-Hans': '优先支持',
            fr: 'Support prioritaire',
            ja: '優先サポート',
            ko: '우선 지원',
            'zh-Hant': '優先支援',
          }),
          feature3: t({
            en: 'Extended usage caps',
            'zh-Hans': '扩展的使用上限',
            fr: 'Plafonds d\'usage étendus',
            ja: '拡張利用上限',
            ko: '확장 사용 한도',
            'zh-Hant': '擴展的使用上限',
          }),
          feature4: t({
            en: 'Advanced templates',
            'zh-Hans': '高级模板',
            fr: 'Templates avancés',
            ja: '高度なテンプレート',
            ko: '고급 템플릿',
            'zh-Hant': '進階範本',
          }),
          feature5: t({
            en: 'Premium documentation',
            'zh-Hans': '优质文档',
            fr: 'Documentation premium',
            ja: 'プレミアムドキュメント',
            ko: '프리미엄 문서',
            'zh-Hant': '優質文件',
          }),
          feature6: t({
            en: 'Community Discord access',
            'zh-Hans': '访问 Discord 社区',
            fr: 'Accès Discord communautaire',
            ja: 'Discord コミュニティへのアクセス',
            ko: 'Discord 커뮤니티 접근',
            'zh-Hant': '存取 Discord 社群',
          }),
          feature7: t({
            en: 'Monthly office hours',
            'zh-Hans': '每月办公时间',
            fr: 'Office hours mensuels',
            ja: '月次オフィスアワー',
            ko: '월간 오피스 아워',
            'zh-Hant': '每月辦公時間',
          }),
          buttonText: t({
            en: 'Start Building',
            'zh-Hans': '开始构建',
            fr: 'Commencer à construire',
            ja: '構築を開始',
            ko: '구축 시작',
            'zh-Hant': '開始建構',
          }),
        },
        tier2: {
          name: t({
            en: 'Tier 2',
            'zh-Hans': '二级计划',
            fr: 'Niveau 2',
            ja: 'ティア2',
            ko: '티어 2',
            'zh-Hant': '二級方案',
          }),
          price: t({
            en: '$8,500',
            'zh-Hans': '¥60,000',
            fr: '8 500 $',
            ja: '¥60,000',
            ko: '$8,500',
            'zh-Hant': '¥60,000',
          }),
          period: t({
            en: '/year + setup fee',
            'zh-Hans': '/年 + 设置费',
            fr: '/an + frais d\'installation',
            ja: '/年 + セットアップ料金',
            ko: '/년 + 설정 비용',
            'zh-Hant': '/年 + 設定費',
          }),
          description: t({
            en: 'Enterprise-grade solution with dedicated support',
            'zh-Hans': '企业级解决方案，配备专属支持',
            fr: 'Solution entreprise avec support dédié',
            ja: 'エンタープライズ向け、専用サポート付き',
            ko: '엔터프라이즈급, 전담 지원',
            'zh-Hant': '企業級方案，配備專屬支援',
          }),
          badge: t({
            en: 'Enterprise',
            'zh-Hans': '企业版',
            fr: 'Enterprise',
            ja: 'Enterprise',
            ko: 'Enterprise',
            'zh-Hant': '企業版',
          }),
          feature1: t({
            en: 'All Tier 1 features',
            'zh-Hans': '一级计划的所有功能',
            fr: 'Toutes les fonctionnalités Tier 1',
            ja: 'ティア1の全機能',
            ko: '티어 1 전체 기능',
            'zh-Hant': '一級方案的所有功能',
          }),
          feature2: t({
            en: 'Custom integrations',
            'zh-Hans': '定制集成',
            fr: 'Intégrations sur mesure',
            ja: 'カスタム連携',
            ko: '맞춤형 연동',
            'zh-Hant': '自訂整合',
          }),
          feature3: t({
            en: 'Dedicated support team',
            'zh-Hans': '专属支持团队',
            fr: 'Équipe support dédiée',
            ja: '専用サポートチーム',
            ko: '전담 지원 팀',
            'zh-Hant': '專屬支援團隊',
          }),
          feature4: t({
            en: 'Onboarding & setup assistance',
            'zh-Hans': '入职和设置协助',
            fr: 'Intégration et configuration',
            ja: 'オンボーディングとセットアップ支援',
            ko: '온보딩 및 설정 지원',
            'zh-Hant': '入職與設定協助',
          }),
          feature5: t({
            en: 'Custom feature development',
            'zh-Hans': '定制功能开发',
            fr: 'Développement de fonctionnalités sur mesure',
            ja: 'カスタム機能開発',
            ko: '맞춤형 기능 개발',
            'zh-Hant': '自訂功能開發',
          }),
          feature6: t({
            en: 'Priority bug fixes',
            'zh-Hans': '优先错误修复',
            fr: 'Corrections de bugs prioritaires',
            ja: '優先バグ修正',
            ko: '우선 버그 수정',
            'zh-Hant': '優先錯誤修復',
          }),
          feature7: t({
            en: 'Direct Slack channel',
            'zh-Hans': '直接 Slack 频道',
            fr: 'Canal Slack direct',
            ja: '直接 Slack チャンネル',
            ko: '직접 Slack 채널',
            'zh-Hant': '直接 Slack 頻道',
          }),
          feature8: t({
            en: 'Monthly strategy calls',
            'zh-Hans': '每月策略会议',
            fr: 'Appels stratégie mensuels',
            ja: '月次戦略コール',
            ko: '월간 전략 콜',
            'zh-Hant': '每月策略會議',
          }),
          buttonText: t({
            en: 'Contact Sales',
            'zh-Hans': '联系销售',
            fr: 'Contacter les ventes',
            ja: '営業に連絡',
            ko: '영업 문의',
            'zh-Hant': '聯絡銷售',
          }),
        },
      },
      comparison: {
        title: t({
          en: 'Compare Features',
          'zh-Hans': '比较功能',
          fr: 'Comparer les fonctionnalités',
          ja: '機能比較',
          ko: '기능 비교',
          'zh-Hant': '比較功能',
        }),
        subtitle: t({
          en: 'See what\'s included in each plan to make the best choice for your needs',
          'zh-Hans': '查看每个计划包含的内容，为您的需求做出最佳选择',
          fr: 'Voir le contenu de chaque offre pour faire le meilleur choix',
          ja: '各プランの内容を確認し、最適な選択を',
          ko: '각 플랜 포함 내용을 확인해 최적의 선택을 하세요',
          'zh-Hant': '查看每個方案包含的內容，為您的需求做出最佳選擇',
        }),
        communitySupport: {
          title: t({
            en: 'Community Support',
            'zh-Hans': '社区支持',
            fr: 'Support communautaire',
            ja: 'コミュニティサポート',
            ko: '커뮤니티 지원',
            'zh-Hant': '社群支援',
          }),
          description: t({
            en: 'Get help from our growing community of AI developers',
            'zh-Hans': '从我们不断增长的 AI 开发者社区获得帮助',
            fr: 'Aide de notre communauté de développeurs IA',
            ja: '成長する AI 開発者コミュニティからサポート',
            ko: '성장하는 AI 개발자 커뮤니티에서 도움 받기',
            'zh-Hant': '從我們不斷成長的 AI 開發者社群獲得協助',
          }),
        },
        prioritySupport: {
          title: t({
            en: 'Priority Support',
            'zh-Hans': '优先支持',
            fr: 'Support prioritaire',
            ja: '優先サポート',
            ko: '우선 지원',
            'zh-Hant': '優先支援',
          }),
          description: t({
            en: 'Get faster responses and dedicated help when you need it',
            'zh-Hans': '获得更快的响应和您需要时的专属帮助',
            fr: 'Réponses plus rapides et aide dédiée quand vous en avez besoin',
            ja: '必要な時に迅速な対応と専用サポート',
            ko: '필요할 때 빠른 응답과 전담 지원',
            'zh-Hant': '獲得更快的回應與您需要時的專屬協助',
          }),
        },
        customIntegrations: {
          title: t({
            en: 'Custom Integrations',
            'zh-Hans': '定制集成',
            fr: 'Intégrations sur mesure',
            ja: 'カスタム連携',
            ko: '맞춤형 연동',
            'zh-Hant': '自訂整合',
          }),
          description: t({
            en: 'Tailored solutions and custom feature development',
            'zh-Hans': '量身定制的解决方案和定制功能开发',
            fr: 'Solutions sur mesure et développement de fonctionnalités',
            ja: 'ニーズに合わせたソリューションとカスタム機能開発',
            ko: '맞춤 솔루션 및 맞춤형 기능 개발',
            'zh-Hant': '量身打造的解決方案與自訂功能開發',
          }),
        },
      },
      faq: {
        title: t({
          en: 'Pricing FAQ',
          'zh-Hans': '定价常见问题',
          fr: 'FAQ Tarification',
          ja: '料金 FAQ',
          ko: '요금 FAQ',
          'zh-Hant': '定價常見問題',
        }),
        q1: {
          question: t({
            en: 'Can I upgrade or downgrade my plan anytime?',
            'zh-Hans': '我可以随时升级或降级我的计划吗？',
            fr: 'Puis-je changer de plan à tout moment ?',
            ja: 'プランのアップグレード・ダウングレードはいつでも可能ですか？',
            ko: '언제든 플랜을 업그레이드하거나 다운그레이드할 수 있나요?',
            'zh-Hant': '我可以隨時升級或降級方案嗎？',
          }),
          answer: t({
            en: 'Yes! You can upgrade your plan at any time. When you upgrade, you\'ll be charged the prorated amount for the remaining billing period. Downgrades take effect at the end of your current billing cycle.',
            'zh-Hans': '可以！您可以随时升级计划。升级时，将按比例收取剩余计费周期的费用。降级将在当前计费周期结束时生效。',
            fr: 'Oui ! Vous pouvez upgrader à tout moment. Le montant au prorata sera facturé pour la période restante. Les downgrades prennent effet en fin de cycle.',
            ja: 'はい。いつでもアップグレード可能です。残り請求期間分の日割り料金が請求されます。ダウングレードは現在の請求サイクル終了時に適用されます。',
            ko: '네. 언제든 업그레이드할 수 있습니다. 업그레이드 시 남은 청구 기간에 대한 일할 계산 금액이 청구됩니다. 다운그레이드는 현재 청구 주기 종료 시 적용됩니다.',
            'zh-Hant': '可以！您可以隨時升級方案。升級時將按比例收取剩餘計費週期費用。降級於目前計費週期結束時生效。',
          }),
        },
        q2: {
          question: t({
            en: 'What\'s included in the setup fee for Tier 2?',
            'zh-Hans': '二级计划的设置费包含什么？',
            fr: 'Que comprend les frais d\'installation Tier 2 ?',
            ja: 'ティア2のセットアップ料金には何が含まれますか？',
            ko: '티어 2 설정 비용에는 무엇이 포함되나요?',
            'zh-Hant': '二級方案的設定費包含什麼？',
          }),
          answer: t({
            en: 'The setup fee covers dedicated onboarding, custom configuration, team training, and initial custom integrations. Our team will work with you to ensure the platform is perfectly tailored to your needs.',
            'zh-Hans': '设置费涵盖专属入职培训、定制配置、团队培训和初始定制集成。我们的团队将与您合作，确保平台完全满足您的需求。',
            fr: 'Les frais couvrent l\'onboarding dédié, la configuration sur mesure, la formation équipe et les intégrations initiales. Notre équipe vous accompagne pour adapter la plateforme à vos besoins.',
            ja: '専用オンボーディング、カスタム設定、チーム研修、初期カスタム連携が含まれます。プラットフォームをニーズに合わせて調整します。',
            ko: '전담 온보딩, 맞춤 설정, 팀 교육, 초기 맞춤 연동이 포함됩니다. 플랫폼이 요구사항에 맞도록 팀이 함께 진행합니다.',
            'zh-Hant': '設定費涵蓋專屬入職培訓、自訂設定、團隊培訓與初始自訂整合。我們的團隊將與您合作，確保平台完全符合您的需求。',
          }),
        },
        q3: {
          question: t({
            en: 'Do you offer refunds?',
            'zh-Hans': '你们提供退款吗？',
            fr: 'Proposez-vous des remboursements ?',
            ja: '返金は可能ですか？',
            ko: '환불이 가능한가요?',
            'zh-Hant': '你們提供退款嗎？',
          }),
          answer: t({
            en: 'We offer a 30-day money-back guarantee for all paid plans. If you\'re not satisfied with your purchase, contact us within 30 days for a full refund.',
            'zh-Hans': '我们为所有付费计划提供 30 天退款保证。如果您对购买不满意，请在 30 天内联系我们全额退款。',
            fr: 'Nous offrons 30 jours satisfait ou remboursé pour tous les plans payants. Contactez-nous sous 30 jours pour un remboursement intégral.',
            ja: '有料プランは30日間返金保証付きです。ご不満の場合は30日以内にご連絡ください。',
            ko: '모든 유료 플랜에 30일 환불 보장이 적용됩니다. 구매에 만족하지 않으시면 30일 이내에 문의해 주세요.',
            'zh-Hant': '我們為所有付費方案提供 30 天退款保證。若對購買不滿意，請於 30 天內聯絡我們全額退款。',
          }),
        },
        q4: {
          question: t({
            en: 'What payment methods do you accept?',
            'zh-Hans': '您接受哪些付款方式？',
            fr: 'Quels moyens de paiement acceptez-vous ?',
            ja: 'どのお支払い方法に対応していますか？',
            ko: '어떤 결제 수단을 지원하나요?',
            'zh-Hant': '您接受哪些付款方式？',
          }),
          answer: t({
            en: 'We accept all major credit cards (Visa, MasterCard, American Express) and PayPal. For enterprise accounts, we can also arrange bank transfers and custom billing cycles.',
            'zh-Hans': '我们接受所有主要信用卡（Visa、MasterCard、American Express）和 PayPal。对于企业账户，我们还可以安排银行转账和自定义计费周期。',
            fr: 'Nous acceptons les cartes majeures (Visa, MasterCard, American Express) et PayPal. Pour les comptes entreprise : virements et cycles de facturation sur mesure.',
            ja: '主要クレジットカード（Visa、MasterCard、Amex）と PayPal に対応。エンタープライズは銀行情報とカスタム請求サイクルも可能です。',
            ko: '주요 신용카드(Visa, MasterCard, Amex) 및 PayPal을 지원합니다. 엔터프라이즈는 송금 및 맞춤 청구 주기도 가능합니다.',
            'zh-Hant': '我們接受主要信用卡（Visa、MasterCard、American Express）與 PayPal。企業帳戶可安排銀行轉帳與自訂計費週期。',
          }),
        },
        q5: {
          question: t({
            en: 'Is there a discount for annual payments?',
            'zh-Hans': '年度付款有折扣吗？',
            fr: 'Y a-t-il une réduction pour le paiement annuel ?',
            ja: '年払いの割引はありますか？',
            ko: '연간 결제 시 할인이 있나요?',
            'zh-Hant': '年度付款有折扣嗎？',
          }),
          answer: t({
            en: 'Our listed prices are already for annual payments, providing significant savings compared to monthly billing. Contact us for custom enterprise pricing and multi-year discounts.',
            'zh-Hans': '我们列出的价格已经是年度付款价格，与月度账单相比可节省大量费用。联系我们获取定制企业定价和多年度折扣。',
            fr: 'Nos tarifs affichés sont déjà en paiement annuel, avec des économies par rapport au mensuel. Contactez-nous pour tarifs entreprise et remises multi-années.',
            ja: '表示価格はすでに年払い価格で、月払いよりお得です。エンタープライズ・複数年割引はお問い合わせください。',
            ko: '표시 가격은 이미 연간 결제 기준이며 월 결제 대비 절약됩니다. 엔터프라이즈 및 다년 할인은 문의하세요.',
            'zh-Hant': '我們列出的價格已為年度付款價格，較月付可節省不少。如需企業定價與多年折扣請聯絡我們。',
          }),
        },
      },
      cta: {
        title: t({
          en: 'Ready to Start Building?',
          'zh-Hans': '准备开始构建了吗？',
          fr: 'Prêt à commencer à construire ?',
          ja: '構築を始める準備はできましたか？',
          ko: '구축을 시작할 준비가 되셨나요?',
          'zh-Hant': '準備開始建構了嗎？',
        }),
        subtitle: t({
          en: 'Join thousands of developers building the future with AI-powered development',
          'zh-Hans': '加入数千名使用 AI 驱动开发构建未来的开发者',
          fr: 'Rejoignez des milliers de développeurs qui construisent l\'avenir avec l\'IA',
          ja: 'AI 駆動開発で未来を築く開発者たちに参加しよう',
          ko: 'AI 기반 개발로 미래를 만드는 수천 명의 개발자와 함께하세요',
          'zh-Hant': '加入數千名使用 AI 驅動開發建構未來的開發者',
        }),
        primaryButton: t({
          en: 'Start Your Free Trial',
          'zh-Hans': '开始免费试用',
          fr: 'Démarrer l\'essai gratuit',
          ja: '無料トライアルを開始',
          ko: '무료 체험 시작',
          'zh-Hant': '開始免費試用',
        }),
        secondaryButton: t({
          en: 'Talk to Sales',
          'zh-Hans': '与销售交谈',
          fr: 'Parler aux ventes',
          ja: '営業に相談',
          ko: '영업 문의',
          'zh-Hant': '與銷售交談',
        }),
      },
      trust: {
        security: t({
          en: 'Enterprise Security',
          'zh-Hans': '企业级安全',
          fr: 'Sécurité entreprise',
          ja: 'エンタープライズセキュリティ',
          ko: '엔터프라이즈 보안',
          'zh-Hant': '企業級安全',
        }),
        support: t({
          en: '24/7 Support',
          'zh-Hans': '24/7 支持',
          fr: 'Support 24/7',
          ja: '24時間サポート',
          ko: '24/7 지원',
          'zh-Hant': '24/7 支援',
        }),
        developers: t({
          en: '10,000+ Developers',
          'zh-Hans': '10,000+ 开发者',
          fr: '10 000+ développeurs',
          ja: '10,000人以上の開発者',
          ko: '10,000명 이상의 개발자',
          'zh-Hant': '10,000+ 開發者',
        }),
      },
    },
  },
  key: 'marketing',
} satisfies Dictionary;

export default marketingContent;
