import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

const mcpContent = {
  content: {
    // Page header
    header: {
      title: t({ en: 'MCP Store', 'zh-Hans': 'MCP 商店', fr: 'Boutique MCP', ja: 'MCP ストア', ko: 'MCP 스토어', 'zh-Hant': 'MCP 商店' }),
      description: t({
        en: 'Manage MCP servers ({total} total, {custom} custom)',
        'zh-Hans': '管理 MCP 服务器（共 {total} 个，{custom} 个自定义）',
        fr: 'Gérer les serveurs MCP ({total} au total, {custom} personnalisés)',
        ja: 'MCP サーバーを管理（合計 {total}、{custom} カスタム）',
        ko: 'MCP 서버 관리 (총 {total}, 맞춤 {custom})',
        'zh-Hant': '管理 MCP 伺服器（共 {total} 個，{custom} 個自訂）',
      }),
    },

    // Sidebar
    sidebar: {
      title: t({ en: 'MCP Store', 'zh-Hans': 'MCP 商店', fr: 'Boutique MCP', ja: 'MCP ストア', ko: 'MCP 스토어', 'zh-Hant': 'MCP 商店' }),
      categories: {
        all: t({ en: 'All MCPs', 'zh-Hans': 'All MCPs', fr: 'Tous les MCPs', ja: 'すべての MCP', ko: '모든 MCP', 'zh-Hant': 'All MCPs' }),
        development: t({ en: 'Development', 'zh-Hans': 'Development', fr: 'Développement', ja: 'Development', ko: 'Development', 'zh-Hant': 'Development' }),
        data: t({ en: 'Data', 'zh-Hans': 'Data', fr: 'Data', ja: 'Data', ko: 'Data', 'zh-Hant': 'Data' }),
        installed: t({ en: 'Enabled', 'zh-Hans': 'Enabled', fr: 'Activés', ja: '有効', ko: '활성화됨', 'zh-Hant': 'Enabled' }),
        system: t({ en: 'System MCPs', 'zh-Hans': 'System MCPs', fr: 'MCPs système', ja: 'システム MCP', ko: '시스템 MCP', 'zh-Hant': 'System MCPs' }),
        custom: t({ en: 'My MCPs', 'zh-Hans': 'My MCPs', fr: 'Mes MCPs', ja: 'マイ MCP', ko: '내 MCP', 'zh-Hant': 'My MCPs' }),
      },
    },

    // Main page
    page: {
      searchPlaceholder: t({ en: 'Search MCPs...', 'zh-Hans': '搜索 MCPs...', fr: 'Rechercher des MCPs...', ja: 'MCP を検索...', ko: 'MCP 검색...', 'zh-Hant': '搜尋 MCPs...' }),
      addMcpButton: t({ en: 'Add MCP', 'zh-Hans': '添加 MCP', fr: 'Ajouter MCP', ja: 'MCP を追加', ko: 'MCP 추가', 'zh-Hant': '新增 MCP' }),
      noResults: t({ en: 'No MCP servers found', 'zh-Hans': '未找到 MCP 服务器', fr: 'Aucun serveur MCP trouvé', ja: 'MCP サーバーが見つかりません', ko: 'MCP 서버를 찾을 수 없습니다', 'zh-Hant': '未找到 MCP 伺服器' }),
      noResultsHint: t({ en: 'Try adjusting your search or filter', 'zh-Hans': '尝试调整搜索条件或筛选器', fr: 'Modifiez la recherche ou les filtres', ja: '検索またはフィルターを調整してください', ko: '검색 또는 필터를 조정해 보세요', 'zh-Hant': '嘗試調整搜尋條件或篩選器' }),
    },

    // Card
    card: {
      enable: t({ en: 'Enable', 'zh-Hans': '启用', fr: 'Activer', ja: '有効にする', ko: '활성화', 'zh-Hant': '啟用' }),
      disable: t({ en: 'Disable', 'zh-Hans': '禁用', fr: 'Désactiver', ja: '無効にする', ko: '비활성화', 'zh-Hant': '停用' }),
      viewDetails: t({ en: 'View details', 'zh-Hans': '查看详情', fr: 'Voir les détails', ja: '詳細を見る', ko: '상세 보기', 'zh-Hant': '查看詳情' }),
      verifyMcp: t({ en: 'Verify MCP', 'zh-Hans': '验证 MCP', fr: 'Vérifier MCP', ja: 'MCP を検証', ko: 'MCP 검증', 'zh-Hant': '驗證 MCP' }),
      deleteMcp: t({ en: 'Delete MCP', 'zh-Hans': '删除 MCP', fr: 'Supprimer MCP', ja: 'MCP を削除', ko: 'MCP 삭제', 'zh-Hant': '刪除 MCP' }),
      systemBadge: t({ en: 'System', 'zh-Hans': 'System', fr: 'Système', ja: 'System', ko: 'System', 'zh-Hant': 'System' }),
      personalBadge: t({ en: 'Personal', 'zh-Hans': 'Personal', fr: 'Personnel', ja: 'Personal', ko: 'Personal', 'zh-Hant': 'Personal' }),
    },

    // Delete confirmation
    deleteConfirm: {
      system: t({
        en: 'Are you sure you want to delete system MCP "{slug}"? This will affect all users. This action cannot be undone.',
        'zh-Hans': '确定要删除系统级 MCP "{slug}" 吗？这将影响所有用户。此操作无法撤销。',
        fr: 'Supprimer le MCP système "{slug}" ? Tous les utilisateurs seront affectés. Action irréversible.',
        ja: 'システム MCP "{slug}" を削除しますか？全ユーザーに影響します。元に戻せません。',
        ko: '시스템 MCP "{slug}"(을)를 삭제할까요? 모든 사용자에게 영향을 줍니다. 되돌릴 수 없습니다.',
        'zh-Hant': '確定要刪除系統級 MCP "{slug}" 嗎？這將影響所有使用者。此操作無法復原。',
      }),
      personal: t({
        en: 'Are you sure you want to delete "{slug}"? This action cannot be undone.',
        'zh-Hans': '确定要删除 "{slug}" 吗？此操作无法撤销。',
        fr: 'Supprimer "{slug}" ? Cette action est irréversible.',
        ja: '"{slug}" を削除しますか？元に戻せません。',
        ko: '"{slug}"(을)를 삭제할까요? 되돌릴 수 없습니다.',
        'zh-Hant': '確定要刪除 "{slug}" 嗎？此操作無法復原。',
      }),
    },

    // Verify messages
    verify: {
      success: t({ en: 'MCP verified successfully.', 'zh-Hans': 'MCP 验证成功。', fr: 'MCP vérifié avec succès.', ja: 'MCP の検証に成功しました。', ko: 'MCP 검증 성공.', 'zh-Hant': 'MCP 驗證成功。' }),
      failed: t({ en: 'MCP verification failed.', 'zh-Hans': 'MCP 验证失败。', fr: 'Échec de la vérification MCP.', ja: 'MCP の検証に失敗しました。', ko: 'MCP 검증 실패.', 'zh-Hant': 'MCP 驗證失敗。' }),
      genericFailed: t({ en: 'MCP verification failed.', 'zh-Hans': 'MCP 验证失败。', fr: 'Échec de la vérification MCP.', ja: 'MCP の検証に失敗しました。', ko: 'MCP 검증 실패.', 'zh-Hant': 'MCP 驗證失敗。' }),
    },

    // Delete messages
    delete: {
      failed: t({ en: 'Failed to delete MCP.', 'zh-Hans': '删除 MCP 失败。', fr: 'Échec de la suppression du MCP.', ja: 'MCP の削除に失敗しました。', ko: 'MCP 삭제 실패.', 'zh-Hant': '刪除 MCP 失敗。' }),
    },

    // Detail Dialog
    detailDialog: {
      enabled: t({ en: 'Enabled', 'zh-Hans': '已启用', fr: 'Activé', ja: '有効', ko: '활성화됨', 'zh-Hant': '已啟用' }),
      disabled: t({ en: 'Disabled', 'zh-Hans': '已禁用', fr: 'Désactivé', ja: '無効', ko: '비활성화됨', 'zh-Hant': '已停用' }),
      refresh: t({ en: 'Refresh', 'zh-Hans': '刷新', fr: 'Actualiser', ja: '更新', ko: '새로고침', 'zh-Hant': '重新整理' }),
      install: t({ en: 'Enable', 'zh-Hans': '启用', fr: 'Activer', ja: '有効にする', ko: '활성화', 'zh-Hant': '啟用' }),
      uninstall: t({ en: 'Disable', 'zh-Hans': '禁用', fr: 'Désactiver', ja: '無効にする', ko: '비활성화', 'zh-Hant': '停用' }),
      storeBadge: {
        system: t({ en: 'System', 'zh-Hans': 'System', fr: 'Système', ja: 'System', ko: 'System', 'zh-Hant': 'System' }),
        personal: t({ en: 'Personal', 'zh-Hans': 'Personal', fr: 'Personnel', ja: 'Personal', ko: 'Personal', 'zh-Hant': 'Personal' }),
      },
      tabs: {
        about: t({ en: 'About', 'zh-Hans': '关于', fr: 'À propos', ja: '概要', ko: '정보', 'zh-Hant': '關於' }),
        configure: t({ en: 'Configure', 'zh-Hans': '配置', fr: 'Configurer', ja: '設定', ko: '설정', 'zh-Hant': '設定' }),
        tools: t({ en: 'Tools', 'zh-Hans': '工具', fr: 'Outils', ja: 'ツール', ko: '도구', 'zh-Hant': '工具' }),
      },
      about: {
        noDocs: t({ en: 'No documentation available for this MCP.', 'zh-Hans': '此 MCP 没有可用文档。', fr: 'Aucune documentation pour ce MCP.', ja: 'この MCP にドキュメントはありません。', ko: '이 MCP에 문서가 없습니다.', 'zh-Hant': '此 MCP 沒有可用文件。' }),
        configuration: t({ en: 'Configuration', 'zh-Hans': '配置', fr: 'Configuration', ja: '設定', ko: '설정', 'zh-Hant': '設定' }),
        tools: t({ en: 'Available Tools', 'zh-Hans': '可用工具', fr: 'Outils disponibles', ja: '利用可能なツール', ko: '사용 가능한 도구', 'zh-Hant': '可用工具' }),
        copy: t({ en: 'Copy', 'zh-Hans': '复制', fr: 'Copier', ja: 'コピー', ko: '복사', 'zh-Hant': '複製' }),
        copied: t({ en: 'Copied', 'zh-Hans': '已复制', fr: 'Copié', ja: 'コピー済み', ko: '복사됨', 'zh-Hant': '已複製' }),
      },
      configure: {
        noConfig: t({ en: 'No configuration needed for {name}.', 'zh-Hans': '{name} 无需配置。', fr: 'Aucune configuration requise pour {name}.', ja: '{name} は設定不要です。', ko: '{name}은(는) 설정 불필요.', 'zh-Hant': '{name} 無需設定。' }),
        loading: t({ en: 'Loading configuration...', 'zh-Hans': '加载配置中...', fr: 'Chargement de la configuration...', ja: '設定を読み込み中...', ko: '설정 로딩 중...', 'zh-Hant': '載入設定中...' }),
        enterPlaceholder: t({ en: 'Enter {label}', 'zh-Hans': '输入 {label}', fr: 'Saisir {label}', ja: '{label} を入力', ko: '{label} 입력', 'zh-Hant': '輸入 {label}' }),
        saveButton: t({ en: 'Save Configuration', 'zh-Hans': '保存配置', fr: 'Enregistrer la configuration', ja: '設定を保存', ko: '설정 저장', 'zh-Hant': '儲存設定' }),
        saving: t({ en: 'Saving...', 'zh-Hans': '保存中...', fr: 'Enregistrement...', ja: '保存中...', ko: '저장 중...', 'zh-Hant': '儲存中...' }),
        saved: t({ en: 'Saved', 'zh-Hans': '已保存', fr: 'Enregistré', ja: '保存しました', ko: '저장됨', 'zh-Hant': '已儲存' }),
        saveError: t({ en: 'Failed to save credentials', 'zh-Hans': '保存凭据失败', fr: 'Échec de l\'enregistrement des identifiants', ja: '認証情報の保存に失敗しました', ko: '자격 증명 저장 실패', 'zh-Hant': '儲存憑證失敗' }),
      },
      tools: {
        loading: t({ en: 'Loading tools...', 'zh-Hans': '加载工具中...', fr: 'Chargement des outils...', ja: 'ツールを読み込み中...', ko: '도구 로딩 중...', 'zh-Hant': '載入工具中...' }),
        error: t({ en: 'Error loading tools', 'zh-Hans': '加载工具时出错', fr: 'Erreur lors du chargement des outils', ja: 'ツールの読み込みエラー', ko: '도구 로드 오류', 'zh-Hant': '載入工具時發生錯誤' }),
        retry: t({ en: 'Retry', 'zh-Hans': '重试', fr: 'Réessayer', ja: '再試行', ko: '다시 시도', 'zh-Hant': '重試' }),
        noTools: t({ en: 'No tools available for this MCP server.', 'zh-Hans': '此 MCP 服务器没有可用工具。', fr: 'Aucun outil disponible pour ce serveur MCP.', ja: 'この MCP サーバーにツールはありません。', ko: '이 MCP 서버에 사용 가능한 도구가 없습니다.', 'zh-Hant': '此 MCP 伺服器沒有可用工具。' }),
        connectionWarning: t({ en: 'Could not connect to MCP server', 'zh-Hans': '无法连接到 MCP 服务器', fr: 'Impossible de se connecter au serveur MCP', ja: 'MCP サーバーに接続できません', ko: 'MCP 서버에 연결할 수 없습니다', 'zh-Hant': '無法連線至 MCP 伺服器' }),
        connectionWarningHint: t({
          en: 'Showing predefined tools from configuration. You may need to configure credentials or install the MCP package.',
          'zh-Hans': '显示配置中的预定义工具。您可能需要配置凭据或安装 MCP 包。',
          fr: 'Affichage des outils prédéfinis. Configurez les identifiants ou installez le paquet MCP si besoin.',
          ja: '設定の事前定義ツールを表示しています。認証情報の設定または MCP パッケージのインストールが必要な場合があります。',
          ko: '설정의 사전 정의 도구를 표시 중입니다. 자격 증명 설정 또는 MCP 패키지 설치가 필요할 수 있습니다.',
          'zh-Hant': '顯示設定中的預定義工具。您可能需要設定憑證或安裝 MCP 套件。',
        }),
        stats: t({
          en: '{count} tools · {enabled} enabled',
          'zh-Hans': '{count} 个工具 · {enabled} 个已启用',
          fr: '{count} outil(s) · {enabled} activé(s)',
          ja: '{count} ツール · {enabled} 有効',
          ko: '도구 {count}개 · {enabled}개 활성화',
          'zh-Hant': '{count} 個工具 · {enabled} 個已啟用',
        }),
        saveChanges: t({ en: 'Save Changes', 'zh-Hans': '保存更改', fr: 'Enregistrer les modifications', ja: '変更を保存', ko: '변경 저장', 'zh-Hant': '儲存變更' }),
        saving: t({ en: 'Saving...', 'zh-Hans': '保存中...', fr: 'Enregistrement...', ja: '保存中...', ko: '저장 중...', 'zh-Hant': '儲存中...' }),
        saved: t({ en: 'Saved', 'zh-Hans': '已保存', fr: 'Enregistré', ja: '保存しました', ko: '저장됨', 'zh-Hant': '已儲存' }),
        saveError: t({ en: 'Failed to save', 'zh-Hans': '保存失败', fr: 'Échec de l\'enregistrement', ja: '保存に失敗しました', ko: '저장 실패', 'zh-Hant': '儲存失敗' }),
        loadError: t({ en: 'Failed to load MCP info', 'zh-Hans': '加载 MCP 信息失败', fr: 'Échec du chargement des infos MCP', ja: 'MCP 情報の読み込みに失敗しました', ko: 'MCP 정보 로드 실패', 'zh-Hant': '載入 MCP 資訊失敗' }),
        connectionError: t({ en: 'Failed to connect to MCP server', 'zh-Hans': '连接到 MCP 服务器失败', fr: 'Échec de la connexion au serveur MCP', ja: 'MCP サーバーへの接続に失敗しました', ko: 'MCP 서버 연결 실패', 'zh-Hant': '連線至 MCP 伺服器失敗' }),
      },
    },

    // Add Custom MCP Dialog
    addDialog: {
      title: t({ en: 'Add Custom MCP Server', 'zh-Hans': '添加自定义 MCP 服务器', fr: 'Ajouter un serveur MCP personnalisé', ja: 'カスタム MCP サーバーを追加', ko: '맞춤 MCP 서버 추가', 'zh-Hant': '新增自訂 MCP 伺服器' }),
      description: t({
        en: 'Add a custom MCP server using one of the methods below.',
        'zh-Hans': '使用以下任一方法添加自定义 MCP 服务器。',
        fr: 'Ajoutez un serveur MCP personnalisé avec l\'une des méthodes ci-dessous.',
        ja: '以下のいずれかの方法でカスタム MCP サーバーを追加します。',
        ko: '아래 방법 중 하나로 맞춤 MCP 서버를 추가하세요.',
        'zh-Hant': '使用以下任一方式新增自訂 MCP 伺服器。',
      }),
      tabs: {
        form: t({ en: 'Form', 'zh-Hans': '表单', fr: 'Formulaire', ja: 'フォーム', ko: '폼', 'zh-Hant': '表單' }),
        yamlJson: t({ en: 'YAML/JSON', 'zh-Hans': 'YAML/JSON', fr: 'YAML/JSON', ja: 'YAML/JSON', ko: 'YAML/JSON', 'zh-Hant': 'YAML/JSON' }),
        url: t({ en: 'URL', 'zh-Hans': 'URL', fr: 'URL', ja: 'URL', ko: 'URL', 'zh-Hant': 'URL' }),
        npm: t({ en: 'npm', 'zh-Hans': 'npm', fr: 'npm', ja: 'npm', ko: 'npm', 'zh-Hant': 'npm' }),
      },
      form: {
        manual: t({ en: 'Fill in the configuration manually', 'zh-Hans': '手动填写配置', fr: 'Remplir la configuration manuellement', ja: '設定を手動で入力', ko: '설정을 수동으로 입력', 'zh-Hant': '手動填寫設定' }),
        example: t({ en: 'Example', 'zh-Hans': '示例', fr: 'Exemple', ja: '例', ko: '예제', 'zh-Hant': '範例' }),
        useExample: t({ en: 'Use Example', 'zh-Hans': '使用示例', fr: 'Utiliser l\'exemple', ja: '例を使用', ko: '예제 사용', 'zh-Hant': '使用範例' }),
        exampleTitle: t({ en: 'Z.AI Vision Server', 'zh-Hans': 'Z.AI 视觉服务器', fr: 'Z.AI Vision Server', ja: 'Z.AI ビジョンサーバー', ko: 'Z.AI Vision Server', 'zh-Hant': 'Z.AI 視覺伺服器' }),
        exampleDescription: t({
          en: 'Example: Adding a vision understanding MCP server',
          'zh-Hans': '示例：添加视觉理解 MCP 服务器',
          fr: 'Exemple : ajouter un serveur MCP vision',
          ja: '例：視覚理解 MCP サーバーを追加',
          ko: '예: 시각 이해 MCP 서버 추가',
          'zh-Hant': '範例：新增視覺理解 MCP 伺服器',
        }),
        nameLabel: t({ en: 'Name', 'zh-Hans': '名称', fr: 'Nom', ja: '名前', ko: '이름', 'zh-Hant': '名稱' }),
        namePlaceholder: t({ en: 'My MCP Server', 'zh-Hans': '我的 MCP 服务器', fr: 'Mon serveur MCP', ja: 'マイ MCP サーバー', ko: '내 MCP 서버', 'zh-Hant': '我的 MCP 伺服器' }),
        slugLabel: t({ en: 'Slug', 'zh-Hans': '标识符', fr: 'Slug', ja: '識別子', ko: '슬러그', 'zh-Hant': '識別碼' }),
        slugPlaceholder: t({ en: 'my-mcp-server', 'zh-Hans': 'my-mcp-server', fr: 'my-mcp-server', ja: 'my-mcp-server', ko: 'my-mcp-server', 'zh-Hant': 'my-mcp-server' }),
        descriptionLabel: t({ en: 'Description', 'zh-Hans': '描述', fr: 'Description', ja: '説明', ko: '설명', 'zh-Hant': '描述' }),
        descriptionPlaceholder: t({
          en: 'What does this MCP server do?',
          'zh-Hans': '此 MCP 服务器的功能是什么？',
          fr: 'Que fait ce serveur MCP ?',
          ja: 'この MCP サーバーの機能は？',
          ko: '이 MCP 서버의 기능은?',
          'zh-Hant': '此 MCP 伺服器的功能是什麼？',
        }),
        categoryLabel: t({ en: 'Category', 'zh-Hans': '分类', fr: 'Catégorie', ja: 'カテゴリ', ko: '카테고리', 'zh-Hant': '分類' }),
        categoryGeneral: t({ en: 'General', 'zh-Hans': 'General', fr: 'General', ja: 'General', ko: 'General', 'zh-Hant': 'General' }),
        categoryDevelopment: t({ en: 'Development', 'zh-Hans': 'Development', fr: 'Développement', ja: 'Development', ko: 'Development', 'zh-Hant': 'Development' }),
        categoryData: t({ en: 'Data', 'zh-Hans': 'Data', fr: 'Data', ja: 'Data', ko: 'Data', 'zh-Hant': 'Data' }),
        categoryIntegration: t({ en: 'Integration', 'zh-Hans': 'Integration', fr: 'Intégration', ja: 'Integration', ko: 'Integration', 'zh-Hant': 'Integration' }),
        connectionTypeLabel: t({ en: 'Connection Type', 'zh-Hans': '连接类型', fr: 'Type de connexion', ja: '接続タイプ', ko: '연결 유형', 'zh-Hant': '連線類型' }),
        typeStdio: t({ en: 'stdio (Local Process)', 'zh-Hans': 'stdio（本地进程）', fr: 'stdio (processus local)', ja: 'stdio（ローカルプロセス）', ko: 'stdio(로컬 프로세스)', 'zh-Hant': 'stdio（本機程序）' }),
        typeHttp: t({ en: 'HTTP', 'zh-Hans': 'HTTP', fr: 'HTTP', ja: 'HTTP', ko: 'HTTP', 'zh-Hant': 'HTTP' }),
        typeSse: t({ en: 'SSE (Server-Sent Events)', 'zh-Hans': 'SSE（服务器发送事件）', fr: 'SSE (Server-Sent Events)', ja: 'SSE（サーバー送信イベント）', ko: 'SSE(서버 전송 이벤트)', 'zh-Hant': 'SSE（伺服器發送事件）' }),
        commandLabel: t({ en: 'Command', 'zh-Hans': '命令', fr: 'Commande', ja: 'コマンド', ko: '명령', 'zh-Hant': '命令' }),
        commandPlaceholder: t({ en: 'npx', 'zh-Hans': 'npx', fr: 'npx', ja: 'npx', ko: 'npx', 'zh-Hant': 'npx' }),
        argsLabel: t({ en: 'Arguments (space or comma separated)', 'zh-Hans': '参数（空格或逗号分隔）', fr: 'Arguments (espaces ou virgules)', ja: '引数（スペースまたはカンマ区切り）', ko: '인자(공백 또는 쉼표)', 'zh-Hant': '參數（空格或逗號分隔）' }),
        argsPlaceholder: t({ en: '-y @org/mcp-server', 'zh-Hans': '-y @org/mcp-server', fr: '-y @org/mcp-server', ja: '-y @org/mcp-server', ko: '-y @org/mcp-server', 'zh-Hant': '-y @org/mcp-server' }),
        envVarsLabel: t({ en: 'Environment Variables', 'zh-Hans': '环境变量', fr: 'Variables d\'environnement', ja: '環境変数', ko: '환경 변수', 'zh-Hant': '環境變數' }),
        addEnvVar: t({ en: 'Add', 'zh-Hans': '添加', fr: 'Ajouter', ja: '追加', ko: '추가', 'zh-Hant': '新增' }),
        keyPlaceholder: t({ en: 'KEY', 'zh-Hans': 'KEY', fr: 'KEY', ja: 'KEY', ko: 'KEY', 'zh-Hant': 'KEY' }),
        valuePlaceholder: t({ en: '${KEY} or value', 'zh-Hans': '${KEY} 或值', fr: '${KEY} ou valeur', ja: '${KEY} または値', ko: '${KEY} 또는 값', 'zh-Hant': '${KEY} 或值' }),
        urlLabel: t({ en: 'URL', 'zh-Hans': 'URL', fr: 'URL', ja: 'URL', ko: 'URL', 'zh-Hant': 'URL' }),
        urlPlaceholder: t({ en: 'https://api.example.com/mcp', 'zh-Hans': 'https://api.example.com/mcp', fr: 'https://api.example.com/mcp', ja: 'https://api.example.com/mcp', ko: 'https://api.example.com/mcp', 'zh-Hant': 'https://api.example.com/mcp' }),
        credentialsLabel: t({ en: 'Credential Fields (for user to fill)', 'zh-Hans': '凭据字段（供用户填写）', fr: 'Champs d\'identifiants (à remplir)', ja: '認証情報フィールド（ユーザー入力）', ko: '자격 증명 필드(사용자 입력)', 'zh-Hant': '憑證欄位（供使用者填寫）' }),
        credentialsHint: t({
          en: 'Define fields that users need to provide (like API keys)',
          'zh-Hans': '定义用户需要提供的字段（如 API 密钥）',
          fr: 'Définir les champs à fournir (ex. clés API)',
          ja: 'ユーザーが提供するフィールドを定義（API キーなど）',
          ko: '사용자가 제공할 필드 정의(API 키 등)',
          'zh-Hant': '定義使用者需提供的欄位（如 API 金鑰）',
        }),
        keyPlaceholderShort: t({ en: 'KEY', 'zh-Hans': 'KEY', fr: 'KEY', ja: 'KEY', ko: 'KEY', 'zh-Hant': 'KEY' }),
        labelPlaceholder: t({ en: 'Label', 'zh-Hans': '标签', fr: 'Libellé', ja: 'ラベル', ko: '레이블', 'zh-Hant': '標籤' }),
        required: t({ en: 'Required', 'zh-Hans': '必需', fr: 'Requis', ja: '必須', ko: '필수', 'zh-Hant': '必填' }),
        visibility: t({ en: 'Visibility', 'zh-Hans': '可见性', fr: 'Visibilité', ja: '表示', ko: '표시', 'zh-Hant': '可見性' }),
        visibilityPersonal: t({ en: 'Personal', 'zh-Hans': '个人', fr: 'Personnel', ja: '個人', ko: '개인', 'zh-Hant': '個人' }),
        visibilityPersonalDesc: t({
          en: 'Only visible to you. You can modify or delete it anytime.',
          'zh-Hans': '仅您可见。您可以随时修改或删除。',
          fr: 'Visible uniquement par vous. Vous pouvez modifier ou supprimer à tout moment.',
          ja: '自分だけに表示。いつでも編集・削除できます。',
          ko: '본인만 볼 수 있습니다. 언제든 수정하거나 삭제할 수 있습니다.',
          'zh-Hant': '僅您可見。您可以隨時修改或刪除。',
        }),
        visibilitySystem: t({ en: 'System', 'zh-Hans': '系统', fr: 'Système', ja: 'システム', ko: '시스템', 'zh-Hant': '系統' }),
        visibilitySystemDesc: t({
          en: 'Visible to all users. Only administrators can modify or delete.',
          'zh-Hans': '所有用户可见。只有管理员可以修改或删除。',
          fr: 'Visible par tous. Seuls les administrateurs peuvent modifier ou supprimer.',
          ja: '全ユーザーに表示。管理者のみ編集・削除可能。',
          ko: '모든 사용자에게 표시. 관리자만 수정·삭제 가능.',
          'zh-Hant': '所有使用者可見。僅管理員可修改或刪除。',
        }),
        cancelButton: t({ en: 'Cancel', 'zh-Hans': '取消', fr: 'Annuler', ja: 'キャンセル', ko: '취소', 'zh-Hant': '取消' }),
        addButton: t({ en: 'Add MCP', 'zh-Hans': '添加 MCP', fr: 'Ajouter MCP', ja: 'MCP を追加', ko: 'MCP 추가', 'zh-Hant': '新增 MCP' }),
        adding: t({ en: 'Adding...', 'zh-Hans': '添加中...', fr: 'Ajout...', ja: '追加中...', ko: '추가 중...', 'zh-Hant': '新增中...' }),
      },
      json: {
        title: t({ en: 'Paste Configuration', 'zh-Hans': '粘贴配置', fr: 'Coller la configuration', ja: '設定を貼り付け', ko: '설정 붙여넣기', 'zh-Hant': '貼上設定' }),
        description: t({ en: 'Paste YAML or JSON configuration', 'zh-Hans': '粘贴 YAML 或 JSON 配置', fr: 'Collez la config YAML ou JSON', ja: 'YAML または JSON 設定を貼り付け', ko: 'YAML 또는 JSON 설정 붙여넣기', 'zh-Hant': '貼上 YAML 或 JSON 設定' }),
        viewExample: t({ en: 'View example format', 'zh-Hans': '查看示例格式', fr: 'Voir le format d\'exemple', ja: '例の形式を見る', ko: '예제 형식 보기', 'zh-Hant': '查看範例格式' }),
        configLabel: t({ en: 'Configuration (YAML or JSON)', 'zh-Hans': '配置（YAML 或 JSON）', fr: 'Configuration (YAML ou JSON)', ja: '設定（YAML または JSON）', ko: '설정(YAML 또는 JSON)', 'zh-Hant': '設定（YAML 或 JSON）' }),
        configPlaceholder: t({ en: 'Paste your YAML or JSON configuration here...', 'zh-Hans': '在此处粘贴您的 YAML 或 JSON 配置...', fr: 'Collez votre config YAML ou JSON ici...', ja: 'YAML または JSON 設定をここに貼り付け...', ko: 'YAML 또는 JSON 설정을 여기에 붙여넣기...', 'zh-Hant': '在此處貼上您的 YAML 或 JSON 設定...' }),
        parseButton: t({ en: 'Parse & Continue', 'zh-Hans': '解析并继续', fr: 'Parser et continuer', ja: '解析して続行', ko: '파싱 후 계속', 'zh-Hant': '解析並繼續' }),
        parsing: t({ en: 'Parsing...', 'zh-Hans': '解析中...', fr: 'Analyse...', ja: '解析中...', ko: '파싱 중...', 'zh-Hant': '解析中...' }),
      },
      url: {
        title: t({ en: 'Import from URL', 'zh-Hans': '从 URL 导入', fr: 'Importer depuis URL', ja: 'URL からインポート', ko: 'URL에서 가져오기', 'zh-Hant': '從 URL 匯入' }),
        description: t({ en: 'Import MCP configuration from a URL', 'zh-Hans': '从 URL 导入 MCP 配置', fr: 'Importer la config MCP depuis une URL', ja: 'URL から MCP 設定をインポート', ko: 'URL에서 MCP 설정 가져오기', 'zh-Hant': '從 URL 匯入 MCP 設定' }),
        example: t({ en: 'https://raw.githubusercontent.com/user/repo/main/MCP.md', 'zh-Hans': 'https://raw.githubusercontent.com/user/repo/main/MCP.md', fr: 'https://raw.githubusercontent.com/user/repo/main/MCP.md', ja: 'https://raw.githubusercontent.com/user/repo/main/MCP.md', ko: 'https://raw.githubusercontent.com/user/repo/main/MCP.md', 'zh-Hant': 'https://raw.githubusercontent.com/user/repo/main/MCP.md' }),
        urlLabel: t({ en: 'MCP Configuration URL', 'zh-Hans': 'MCP 配置 URL', fr: 'URL de configuration MCP', ja: 'MCP 設定 URL', ko: 'MCP 설정 URL', 'zh-Hant': 'MCP 設定 URL' }),
        urlPlaceholder: t({ en: 'https://...', 'zh-Hans': 'https://...', fr: 'https://...', ja: 'https://...', ko: 'https://...', 'zh-Hant': 'https://...' }),
        urlHint: t({
          en: 'URL should point to an MCP.md file or a raw YAML/JSON configuration',
          'zh-Hans': 'URL 应指向 MCP.md 文件或原始 YAML/JSON 配置',
          fr: 'L\'URL doit pointer vers un fichier MCP.md ou une config YAML/JSON brute',
          ja: 'URL は MCP.md ファイルまたは生の YAML/JSON 設定を指す必要があります',
          ko: 'URL은 MCP.md 파일 또는 원시 YAML/JSON 설정을 가리켜야 합니다',
          'zh-Hant': 'URL 應指向 MCP.md 檔案或原始 YAML/JSON 設定',
        }),
        fetchButton: t({ en: 'Fetch & Continue', 'zh-Hans': '获取并继续', fr: 'Récupérer et continuer', ja: '取得して続行', ko: '가져와서 계속', 'zh-Hant': '取得並繼續' }),
        fetching: t({ en: 'Fetching...', 'zh-Hans': '获取中...', fr: 'Récupération...', ja: '取得中...', ko: '가져오는 중...', 'zh-Hant': '取得中...' }),
      },
      npm: {
        title: t({ en: 'npm Package', 'zh-Hans': 'npm 包', fr: 'Paquet npm', ja: 'npm パッケージ', ko: 'npm 패키지', 'zh-Hant': 'npm 套件' }),
        description: t({ en: 'Auto-detect from npm package', 'zh-Hans': '从 npm 包自动检测', fr: 'Détection automatique depuis le paquet npm', ja: 'npm パッケージから自動検出', ko: 'npm 패키지에서 자동 감지', 'zh-Hant': '從 npm 套件自動偵測' }),
        example: t({ en: '@modelcontextprotocol/server-github', 'zh-Hans': '@modelcontextprotocol/server-github', fr: '@modelcontextprotocol/server-github', ja: '@modelcontextprotocol/server-github', ko: '@modelcontextprotocol/server-github', 'zh-Hant': '@modelcontextprotocol/server-github' }),
        packageLabel: t({ en: 'npm Package Name', 'zh-Hans': 'npm 包名', fr: 'Nom du paquet npm', ja: 'npm パッケージ名', ko: 'npm 패키지 이름', 'zh-Hant': 'npm 套件名稱' }),
        packagePlaceholder: t({ en: '@org/mcp-server', 'zh-Hans': '@org/mcp-server', fr: '@org/mcp-server', ja: '@org/mcp-server', ko: '@org/mcp-server', 'zh-Hant': '@org/mcp-server' }),
        packageHint: t({
          en: 'The package info will be fetched and a configuration will be auto-generated',
          'zh-Hans': '将获取包信息并自动生成配置',
          fr: 'Les infos du paquet seront récupérées et une config sera générée automatiquement',
          ja: 'パッケージ情報を取得し、設定が自動生成されます',
          ko: '패키지 정보를 가져와 설정이 자동 생성됩니다',
          'zh-Hant': '將取得套件資訊並自動產生設定',
        }),
        detectButton: t({ en: 'Detect & Continue', 'zh-Hans': '检测并继续', fr: 'Détecter et continuer', ja: '検出して続行', ko: '감지 후 계속', 'zh-Hant': '偵測並繼續' }),
        detecting: t({ en: 'Detecting...', 'zh-Hans': '检测中...', fr: 'Détection...', ja: '検出中...', ko: '감지 중...', 'zh-Hant': '偵測中...' }),
      },
      errors: {
        slugNameRequired: t({ en: 'Slug and Name are required.', 'zh-Hans': '标识符和名称为必填项。', fr: 'Slug et Nom sont requis.', ja: '識別子と名前は必須です。', ko: '슬러그와 이름은 필수입니다.', 'zh-Hant': '識別碼與名稱為必填。' }),
        commandRequired: t({ en: 'Command is required for stdio type.', 'zh-Hans': 'stdio 类型需要命令。', fr: 'La commande est requise pour le type stdio.', ja: 'stdio タイプにはコマンドが必要です。', ko: 'stdio 타입에는 명령이 필요합니다.', 'zh-Hant': 'stdio 類型需要命令。' }),
        urlRequired: t({ en: 'URL is required for HTTP/SSE type.', 'zh-Hans': 'HTTP/SSE 类型需要 URL。', fr: 'L\'URL est requise pour le type HTTP/SSE.', ja: 'HTTP/SSE タイプには URL が必要です。', ko: 'HTTP/SSE 타입에는 URL이 필요합니다.', 'zh-Hant': 'HTTP/SSE 類型需要 URL。' }),
        failedToAdd: t({ en: 'Failed to add MCP.', 'zh-Hans': '添加 MCP 失败。', fr: 'Échec de l\'ajout du MCP.', ja: 'MCP の追加に失敗しました。', ko: 'MCP 추가 실패.', 'zh-Hant': '新增 MCP 失敗。' }),
        anErrorOccurred: t({ en: 'An error occurred.', 'zh-Hans': '发生错误。', fr: 'Une erreur s\'est produite.', ja: 'エラーが発生しました。', ko: '오류가 발생했습니다.', 'zh-Hant': '發生錯誤。' }),
        pasteContent: t({ en: 'Please paste configuration content.', 'zh-Hans': '请粘贴配置内容。', fr: 'Veuillez coller le contenu de la configuration.', ja: '設定内容を貼り付けてください。', ko: '설정 내용을 붙여넣어 주세요.', 'zh-Hant': '請貼上設定內容。' }),
        parseFailed: t({ en: 'Failed to parse configuration.', 'zh-Hans': '解析配置失败。', fr: 'Échec du parsing de la configuration.', ja: '設定の解析に失敗しました。', ko: '설정 파싱 실패.', 'zh-Hant': '解析設定失敗。' }),
        parseError: t({ en: 'Parse error.', 'zh-Hans': '解析错误。', fr: 'Erreur de parsing.', ja: '解析エラー。', ko: '파싱 오류.', 'zh-Hant': '解析錯誤。' }),
        enterUrl: t({ en: 'Please enter a URL.', 'zh-Hans': '请输入 URL。', fr: 'Veuillez entrer une URL.', ja: 'URL を入力してください。', ko: 'URL을 입력해 주세요.', 'zh-Hant': '請輸入 URL。' }),
        fetchFailed: t({ en: 'Failed to fetch from URL.', 'zh-Hans': '从 URL 获取失败。', fr: 'Échec de la récupération depuis l\'URL.', ja: 'URL からの取得に失敗しました。', ko: 'URL에서 가져오기 실패.', 'zh-Hant': '從 URL 取得失敗。' }),
        fetchError: t({ en: 'Fetch error.', 'zh-Hans': '获取错误。', fr: 'Erreur de récupération.', ja: '取得エラー。', ko: '가져오기 오류.', 'zh-Hant': '取得錯誤。' }),
        enterPackage: t({ en: 'Please enter an npm package name.', 'zh-Hans': '请输入 npm 包名。', fr: 'Veuillez entrer un nom de paquet npm.', ja: 'npm パッケージ名を入力してください。', ko: 'npm 패키지 이름을 입력해 주세요.', 'zh-Hant': '請輸入 npm 套件名稱。' }),
        npmParseFailed: t({ en: 'Failed to parse npm package.', 'zh-Hans': '解析 npm 包失败。', fr: 'Échec du parsing du paquet npm.', ja: 'npm パッケージの解析に失敗しました。', ko: 'npm 패키지 파싱 실패.', 'zh-Hant': '解析 npm 套件失敗。' }),
        npmError: t({ en: 'npm error.', 'zh-Hans': 'npm 错误。', fr: 'Erreur npm.', ja: 'npm エラー。', ko: 'npm 오류.', 'zh-Hant': 'npm 錯誤。' }),
      },
      success: {
        added: t({ en: 'MCP "{slug}" added as {scope} successfully!', 'zh-Hans': 'MCP "{slug}" 已成功添加为 {scope}！', fr: 'MCP "{slug}" ajouté en tant que {scope} avec succès !', ja: 'MCP "{slug}" を {scope} として追加しました！', ko: 'MCP "{slug}"(이)가 {scope}(으)로 추가됨!', 'zh-Hant': 'MCP "{slug}" 已成功新增為 {scope}！' }),
        scopePersonal: t({ en: 'personal', 'zh-Hans': '个人', fr: 'personnel', ja: '個人', ko: '개인', 'zh-Hant': '個人' }),
        scopeSystem: t({ en: 'system', 'zh-Hans': '系统', fr: 'système', ja: 'システム', ko: '시스템', 'zh-Hant': '系統' }),
        parsed: t({ en: 'Configuration parsed! Review and submit.', 'zh-Hans': '配置已解析！请检查并提交。', fr: 'Configuration parsée ! Vérifiez et soumettez.', ja: '設定を解析しました。確認して送信してください。', ko: '설정 파싱됨. 검토 후 제출하세요.', 'zh-Hant': '設定已解析！請檢查並提交。' }),
        imported: t({ en: 'Configuration imported! Review and submit.', 'zh-Hans': '配置已导入！请检查并提交。', fr: 'Configuration importée ! Vérifiez et soumettez.', ja: '設定をインポートしました。確認して送信してください。', ko: '설정 가져옴. 검토 후 제출하세요.', 'zh-Hant': '設定已匯入！請檢查並提交。' }),
        packageLoaded: t({ en: 'Package info loaded! Review and submit.', 'zh-Hans': '包信息已加载！请检查并提交。', fr: 'Infos du paquet chargées ! Vérifiez et soumettez.', ja: 'パッケージ情報を読み込みました。確認して送信してください。', ko: '패키지 정보 로드됨. 검토 후 제출하세요.', 'zh-Hant': '套件資訊已載入！請檢查並提交。' }),
      },
    },
  },
  key: 'mcp',
} satisfies Dictionary;

export default mcpContent;
