import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Projects content dictionary — the Projects-centric IA (项目 + 最近 rail,
 * project home, create/share). Mirrors the ChatGPT / Claude Desktop "everything
 * is a Project" model (PRD 2026-06-projects-collaboration).
 */
const projectsContent = {
  content: {
    nav: {
      projects: t({
        en: 'Projects',
        'zh-Hans': '项目',
        fr: 'Projets',
        ja: 'プロジェクト',
        ko: '프로젝트',
        'zh-Hant': '專案',
      }),
    },
    rail: {
      newChat: t({
        en: 'New chat',
        'zh-Hans': '新建聊天',
        fr: 'Nouveau chat',
        ja: '新しいチャット',
        ko: '새 채팅',
        'zh-Hant': '新增聊天',
      }),
      projectsHeading: t({
        en: 'Projects',
        'zh-Hans': '项目',
        fr: 'Projets',
        ja: 'プロジェクト',
        ko: '프로젝트',
        'zh-Hant': '專案',
      }),
      newProject: t({
        en: 'New project',
        'zh-Hans': '新项目',
        fr: 'Nouveau projet',
        ja: '新しいプロジェクト',
        ko: '새 프로젝트',
        'zh-Hant': '新增專案',
      }),
      recentHeading: t({
        en: 'Recent',
        'zh-Hans': '最近',
        fr: 'Récent',
        ja: '最近',
        ko: '최근',
        'zh-Hant': '最近',
      }),
      noProjects: t({
        en: 'No projects yet',
        'zh-Hans': '还没有项目',
        fr: 'Aucun projet',
        ja: 'プロジェクトがありません',
        ko: '프로젝트가 없습니다',
        'zh-Hant': '尚無專案',
      }),
      noRecent: t({
        en: 'No recent chats',
        'zh-Hans': '暂无最近聊天',
        fr: 'Aucun chat récent',
        ja: '最近のチャットはありません',
        ko: '최근 채팅이 없습니다',
        'zh-Hant': '尚無最近聊天',
      }),
      personal: t({
        en: 'Personal',
        'zh-Hans': '个人',
        fr: 'Personnel',
        ja: '個人',
        ko: '개인',
        'zh-Hant': '個人',
      }),
    },
    create: {
      title: t({
        en: 'Create project',
        'zh-Hans': '创建项目',
        fr: 'Créer un projet',
        ja: 'プロジェクトを作成',
        ko: '프로젝트 만들기',
        'zh-Hant': '建立專案',
      }),
      nameLabel: t({
        en: 'Project name',
        'zh-Hans': '项目名称',
        fr: 'Nom du projet',
        ja: 'プロジェクト名',
        ko: '프로젝트 이름',
        'zh-Hant': '專案名稱',
      }),
      namePlaceholder: t({
        en: 'e.g. Kin',
        'zh-Hans': '例如：Kin',
        fr: 'ex. Kin',
        ja: '例：Kin',
        ko: '예: Kin',
        'zh-Hant': '例如：Kin',
      }),
      hint: t({
        en: 'Projects keep your chats, files, and custom instructions together — for ongoing work, or simply to stay organized.',
        'zh-Hans': '项目功能可将聊天、文件和自定义指令集中保存，以便用于持续进行的工作，或者单纯用于整理内容，让一切更井然有序。',
        fr: 'Les projets regroupent vos chats, fichiers et instructions personnalisées — pour un travail continu ou simplement pour rester organisé.',
        ja: 'プロジェクトはチャット・ファイル・カスタム指示をまとめて保存します。継続的な作業にも、単に整理するためにも使えます。',
        ko: '프로젝트는 채팅, 파일, 사용자 지정 지침을 함께 보관합니다. 지속적인 작업이나 단순한 정리에 모두 사용할 수 있습니다.',
        'zh-Hant': '專案功能可將聊天、檔案和自訂指令集中保存，用於持續進行的工作，或單純用於整理內容，讓一切更井然有序。',
      }),
      submit: t({
        en: 'Create project',
        'zh-Hans': '创建项目',
        fr: 'Créer le projet',
        ja: 'プロジェクトを作成',
        ko: '프로젝트 만들기',
        'zh-Hant': '建立專案',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
    },
    home: {
      newChatIn: t({
        en: 'New chat in {name}',
        'zh-Hans': '「{name}」中的新聊天',
        fr: 'Nouveau chat dans {name}',
        ja: '{name} の新しいチャット',
        ko: '{name}의 새 채팅',
        'zh-Hant': '「{name}」中的新聊天',
      }),
      tabChats: t({
        en: 'Chats',
        'zh-Hans': '聊天',
        fr: 'Chats',
        ja: 'チャット',
        ko: '채팅',
        'zh-Hant': '聊天',
      }),
      tabSources: t({
        en: 'Sources',
        'zh-Hans': '来源',
        fr: 'Sources',
        ja: 'ソース',
        ko: '소스',
        'zh-Hant': '來源',
      }),
      share: t({
        en: 'Share',
        'zh-Hans': '分享',
        fr: 'Partager',
        ja: '共有',
        ko: '공유',
        'zh-Hant': '分享',
      }),
      chatsEmpty: t({
        en: 'No chats in this project yet',
        'zh-Hans': '这个项目还没有聊天',
        fr: 'Aucun chat dans ce projet',
        ja: 'このプロジェクトにはまだチャットがありません',
        ko: '이 프로젝트에 아직 채팅이 없습니다',
        'zh-Hant': '這個專案還沒有聊天',
      }),
      chatsEmptyHint: t({
        en: 'Start a new chat above to keep it in this project.',
        'zh-Hans': '在上方开始一个新聊天，它会保存在这个项目里。',
        fr: 'Démarrez un nouveau chat ci-dessus pour le garder dans ce projet.',
        ja: '上で新しいチャットを開始すると、このプロジェクトに保存されます。',
        ko: '위에서 새 채팅을 시작하면 이 프로젝트에 저장됩니다.',
        'zh-Hant': '在上方開始一個新聊天，它會保存在這個專案裡。',
      }),
      sourcesEmpty: t({
        en: 'No sources in this project yet',
        'zh-Hans': '这个项目还没有来源',
        fr: 'Aucune source dans ce projet',
        ja: 'このプロジェクトにはまだソースがありません',
        ko: '이 프로젝트에 아직 소스가 없습니다',
        'zh-Hant': '這個專案還沒有來源',
      }),
      sourcesHint: t({
        en: 'Documents added here become shared sources every chat in this project can search.',
        'zh-Hans': '在此添加的文档会成为共享来源，项目里的每个聊天都能检索。',
        fr: 'Les documents ajoutés ici deviennent des sources partagées que chaque chat du projet peut rechercher.',
        ja: 'ここに追加したドキュメントは共有ソースとなり、プロジェクト内の各チャットが検索できます。',
        ko: '여기에 추가한 문서는 공유 소스가 되어 프로젝트의 모든 채팅이 검색할 수 있습니다.',
        'zh-Hant': '在此新增的文件會成為共享來源，專案裡的每個聊天都能檢索。',
      }),
      addSource: t({
        en: 'Add source',
        'zh-Hans': '添加来源',
        fr: 'Ajouter une source',
        ja: 'ソースを追加',
        ko: '소스 추가',
        'zh-Hant': '新增來源',
      }),
      sharedBadge: t({
        en: 'Shared',
        'zh-Hans': '已共享',
        fr: 'Partagé',
        ja: '共有中',
        ko: '공유됨',
        'zh-Hant': '已分享',
      }),
      comingSoon: t({
        en: 'Coming soon',
        'zh-Hans': '即将上线',
        fr: 'Bientôt disponible',
        ja: '近日公開',
        ko: '출시 예정',
        'zh-Hant': '即將上線',
      }),
    },
    share: {
      title: t({
        en: 'Share project',
        'zh-Hans': '分享项目',
        fr: 'Partager le projet',
        ja: 'プロジェクトを共有',
        ko: '프로젝트 공유',
        'zh-Hant': '分享專案',
      }),
      desc: t({
        en: 'Add members to share every chat and source in this project — instantly, with no re-indexing.',
        'zh-Hans': '添加成员即可共享该项目的全部聊天与来源——即时生效，无需重新索引。',
        fr: 'Ajoutez des membres pour partager tous les chats et sources de ce projet — instantanément, sans réindexation.',
        ja: 'メンバーを追加すると、プロジェクト内のすべてのチャットとソースを即座に共有できます。再インデックス不要です。',
        ko: '멤버를 추가하면 이 프로젝트의 모든 채팅과 소스를 즉시 공유합니다. 재색인이 필요 없습니다.',
        'zh-Hant': '新增成員即可共享該專案的全部聊天與來源——即時生效，無需重新索引。',
      }),
      emailPlaceholder: t({
        en: "Colleague's email",
        'zh-Hans': '输入同事邮箱',
        fr: "E-mail du collègue",
        ja: '同僚のメールアドレス',
        ko: '동료 이메일',
        'zh-Hant': '輸入同事信箱',
      }),
      addMember: t({
        en: 'Add member',
        'zh-Hans': '添加成员',
        fr: 'Ajouter un membre',
        ja: 'メンバーを追加',
        ko: '멤버 추가',
        'zh-Hant': '新增成員',
      }),
      ownerBadge: t({
        en: 'Owner',
        'zh-Hans': '所有者',
        fr: 'Propriétaire',
        ja: 'オーナー',
        ko: '소유자',
        'zh-Hant': '擁有者',
      }),
      removeMember: t({
        en: 'Remove member',
        'zh-Hans': '移除成员',
        fr: 'Retirer le membre',
        ja: 'メンバーを削除',
        ko: '멤버 제거',
        'zh-Hant': '移除成員',
      }),
      userNotFound: t({
        en: 'No user with that email in this workspace.',
        'zh-Hans': '该邮箱在本工作区中没有对应用户。',
        fr: "Aucun utilisateur avec cet e-mail dans cet espace de travail.",
        ja: 'このメールアドレスのユーザーはこのワークスペースにいません。',
        ko: '이 워크스페이스에 해당 이메일의 사용자가 없습니다.',
        'zh-Hant': '該信箱在本工作區中沒有對應使用者。',
      }),
      addFailed: t({
        en: 'Could not update members. Try again.',
        'zh-Hans': '更新成员失败，请重试。',
        fr: 'Impossible de mettre à jour les membres. Réessayez.',
        ja: 'メンバーを更新できませんでした。もう一度お試しください。',
        ko: '멤버를 업데이트하지 못했습니다. 다시 시도하세요.',
        'zh-Hant': '更新成員失敗，請重試。',
      }),
    },
    index: {
      title: t({
        en: 'Projects',
        'zh-Hans': '项目',
        fr: 'Projets',
        ja: 'プロジェクト',
        ko: '프로젝트',
        'zh-Hant': '專案',
      }),
      subtitle: t({
        en: 'Pick a project on the left, or create a new one to organize chats, files, and instructions.',
        'zh-Hans': '在左侧选择一个项目，或新建一个，用来统筹聊天、文件与指令。',
        fr: 'Choisissez un projet à gauche, ou créez-en un nouveau pour organiser chats, fichiers et instructions.',
        ja: '左でプロジェクトを選ぶか、新規作成してチャット・ファイル・指示を整理しましょう。',
        ko: '왼쪽에서 프로젝트를 선택하거나 새로 만들어 채팅, 파일, 지침을 정리하세요.',
        'zh-Hant': '在左側選擇一個專案，或新建一個，用來統籌聊天、檔案與指令。',
      }),
    },
    branch: {
      // Shown above the composer when viewing a session you don't own (reply → branch).
      replyWillBranch: t({
        en: 'Viewing a shared conversation — replying will create your own branch.',
        'zh-Hans': '你正在查看共享会话 —— 发表回复将创建你的分支。',
        fr: "Vous consultez une conversation partagée — répondre créera votre propre branche.",
        ja: '共有会話を閲覧中 —— 返信するとあなたの分岐が作成されます。',
        ko: '공유 대화를 보는 중입니다 — 답장하면 내 분기가 생성됩니다.',
        'zh-Hant': '你正在查看共享會話 —— 發表回覆將建立你的分支。',
      }),
      // Divider in a branched session: "Branch from {title}".
      fromSource: t({
        en: 'Branch from {title}',
        'zh-Hans': '从 {title} 建立的分支',
        fr: 'Branche de {title}',
        ja: '{title} からの分岐',
        ko: '{title}에서 만든 분기',
        'zh-Hant': '從 {title} 建立的分支',
      }),
      untitledSource: t({
        en: 'a conversation',
        'zh-Hans': '某个会话',
        fr: 'une conversation',
        ja: 'ある会話',
        ko: '어떤 대화',
        'zh-Hant': '某個會話',
      }),
    },
  },
  key: 'projects',
} satisfies Dictionary;

export default projectsContent;
