import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

/**
 * Settings page content dictionary
 * Contains labels and messages for user settings and preferences
 */
const settingsContent = {
  content: {
    page: {
      title: t({
        en: 'Settings',
        'zh-Hans': '设置',
        fr: 'Paramètres',
        ja: '設定',
        ko: '설정',
        'zh-Hant': '設定',
      }),
      breadcrumb: t({
        en: 'Settings',
        'zh-Hans': '设置',
        fr: 'Paramètres',
        ja: '設定',
        ko: '설정',
        'zh-Hant': '設定',
      }),
      dialogDescription: t({
        en: 'Project and chat settings',
        'zh-Hans': '项目与聊天设置',
        fr: 'Paramètres du projet et du chat',
        ja: 'プロジェクトとチャットの設定',
        ko: '프로젝트 및 채팅 설정',
        'zh-Hant': '專案與聊天設定',
      }),
    },
    dialog: {
      title: t({
        en: 'Settings',
        'zh-Hans': '设置',
        fr: 'Paramètres',
        ja: '設定',
        ko: '설정',
        'zh-Hant': '設定',
      }),
      description: t({
        en: 'Project and chat settings',
        'zh-Hans': '项目与聊天设置',
        fr: 'Paramètres du projet et du chat',
        ja: 'プロジェクトとチャットの設定',
        ko: '프로젝트 및 채팅 설정',
        'zh-Hant': '專案與聊天設定',
      }),
    },
    permissionModes: {
      standard: t({
        en: 'Standard',
        'zh-Hans': '标准',
        fr: 'Standard',
        ja: '標準',
        ko: '표준',
        'zh-Hant': '標準',
      }),
      plan: t({
        en: 'Plan',
        'zh-Hans': '计划',
        fr: 'Plan',
        ja: '計画',
        ko: '플랜',
        'zh-Hant': '計劃',
      }),
      dontAsk: t({
        en: "Don't Ask",
        'zh-Hans': '不再询问',
        fr: 'Ne pas demander',
        ja: '確認しない',
        ko: '묻지 않음',
        'zh-Hant': '不再詢問',
      }),
      acceptEdits: t({
        en: 'Accept Edits',
        'zh-Hans': '接受编辑',
        fr: 'Accepter les modifications',
        ja: '編集を許可',
        ko: '편집 수락',
        'zh-Hant': '接受編輯',
      }),
      delegate: t({
        en: 'Delegate',
        'zh-Hans': '委托',
        fr: 'Déléguer',
        ja: '委任',
        ko: '위임',
        'zh-Hant': '委託',
      }),
      bypass: t({
        en: 'Bypass',
        'zh-Hans': '绕过',
        fr: 'Contourner',
        ja: 'バイパス',
        ko: '우회',
        'zh-Hant': '繞過',
      }),
      descStandard: t({
        en: 'Safe mode: requires permission confirmation',
        'zh-Hans': '安全模式：需要权限确认',
        fr: 'Mode sûr : confirmation requise',
        ja: '安全モード：許可の確認が必要',
        ko: '안전 모드: 권한 확인 필요',
        'zh-Hant': '安全模式：需權限確認',
      }),
      descPlan: t({
        en: 'Plan mode: prefers EnterPlanMode',
        'zh-Hans': '规划模式：优先使用 EnterPlanMode',
        fr: 'Mode plan : privilégie EnterPlanMode',
        ja: '計画モード：EnterPlanMode を優先',
        ko: '플랜 모드: EnterPlanMode 우선',
        'zh-Hant': '規劃模式：優先使用 EnterPlanMode',
      }),
      descDontAsk: t({
        en: 'Auto mode: executes safe actions automatically',
        'zh-Hans': '自动模式：自动执行安全操作',
        fr: 'Mode auto : exécute les actions sûres',
        ja: '自動モード：安全な操作を自動実行',
        ko: '자동 모드: 안전 작업 자동 실행',
        'zh-Hant': '自動模式：自動執行安全操作',
      }),
      descAcceptEdits: t({
        en: 'Edit mode: auto-accepts file edits',
        'zh-Hans': '编辑模式：自动接受文件编辑',
        fr: 'Mode édition : accepte les modifications',
        ja: '編集モード：ファイル編集を自動許可',
        ko: '편집 모드: 파일 편집 자동 수락',
        'zh-Hant': '編輯模式：自動接受檔案編輯',
      }),
      descDelegate: t({
        en: 'Delegate mode: allows task delegation',
        'zh-Hans': '委托模式：允许委派任务',
        fr: 'Mode délégation : permet de déléguer',
        ja: '委任モード：タスク委任を許可',
        ko: '위임 모드: 작업 위임 허용',
        'zh-Hant': '委託模式：允許委派任務',
      }),
      descBypass: t({
        en: 'Advanced mode: no permission confirmation',
        'zh-Hans': '高级模式：无权限确认',
        fr: 'Mode avancé : pas de confirmation',
        ja: '上級モード：許可確認なし',
        ko: '고급 모드: 권한 확인 없음',
        'zh-Hant': '進階模式：無權限確認',
      }),
    },
    navigation: {
      workspace: t({
        en: 'Workspace',
        'zh-Hans': '工作空间',
        fr: 'Espace de travail',
        ja: 'ワークスペース',
        ko: '작업 공간',
        'zh-Hant': '工作空間',
      }),
      billing: t({
        en: 'Billing',
        'zh-Hans': '账单',
        fr: 'Facturation',
        ja: '請求',
        ko: '결제',
        'zh-Hant': '帳單',
      }),
    },
    sections: {
      profile: {
        title: t({
          en: 'Profile',
          'zh-Hans': '个人资料',
          fr: 'Profil',
          ja: 'プロフィール',
          ko: '프로필',
          'zh-Hant': '個人資料',
        }),
        description: t({
          en: 'Update your personal information',
          'zh-Hans': '更新您的个人信息',
          fr: 'Mettre à jour vos informations',
          ja: '個人情報を更新',
          ko: '개인 정보 업데이트',
          'zh-Hant': '更新您的個人資訊',
        }),
      },
      account: {
        title: t({
          en: 'Account',
          'zh-Hans': '账户',
          fr: 'Compte',
          ja: 'アカウント',
          ko: '계정',
          'zh-Hant': '帳戶',
        }),
        description: t({
          en: 'Manage profile details and security credentials',
          'zh-Hans': '管理个人资料详情和安全凭证',
          fr: 'Profil et identifiants de sécurité',
          ja: 'プロフィールとセキュリティ認証情報を管理',
          ko: '프로필 및 보안 인증 정보 관리',
          'zh-Hant': '管理個人資料與安全憑證',
        }),
      },
      organization: {
        title: t({
          en: 'Organization',
          'zh-Hans': '组织',
          fr: 'Organisation',
          ja: '組織',
          ko: '조직',
          'zh-Hant': '組織',
        }),
        description: t({
          en: 'Create and manage your organization',
          'zh-Hans': '创建和管理您的组织',
          fr: 'Créer et gérer votre organisation',
          ja: '組織の作成と管理',
          ko: '조직 생성 및 관리',
          'zh-Hant': '建立與管理您的組織',
        }),
      },
      preferences: {
        title: t({
          en: 'Preferences',
          'zh-Hans': '偏好设置',
          fr: 'Préférences',
          ja: '設定',
          ko: '환경설정',
          'zh-Hant': '偏好設定',
        }),
        description: t({
          en: 'Interface and theme settings',
          'zh-Hans': '界面和主题设置',
          fr: 'Interface et thème',
          ja: 'インターフェースとテーマの設定',
          ko: '인터페이스 및 테마 설정',
          'zh-Hant': '介面與主題設定',
        }),
      },
      plans: {
        title: t({
          en: 'Plans',
          'zh-Hans': '计划',
          fr: 'Plans',
          ja: 'プラン',
          ko: '플랜',
          'zh-Hant': '方案',
        }),
        description: t({
          en: 'Manage your subscription tiers and credit packs',
          'zh-Hans': '管理您的订阅计划和信用包',
          fr: 'Plans d\'abonnement et packs de crédits',
          ja: 'サブスクリプションとクレジットパックを管理',
          ko: '구독 플랜 및 크레딧 패키지 관리',
          'zh-Hant': '管理您的訂閱方案與點數包',
        }),
      },
      billing: {
        title: t({
          en: 'Billing & Invoices',
          'zh-Hans': '账单与发票',
          fr: 'Facturation et factures',
          ja: '請求と請求書',
          ko: '결제 및 청구서',
          'zh-Hant': '帳單與發票',
        }),
        description: t({
          en: 'Payment details, billing profile, and invoices',
          'zh-Hans': '付款详情、账单资料和发票',
          fr: 'Paiement, profil de facturation et factures',
          ja: '支払い詳細、請求プロフィール、請求書',
          ko: '결제 세부정보, 청구 프로필, 청구서',
          'zh-Hant': '付款詳情、帳單資料與發票',
        }),
        page: {
          title: t({
            en: 'Billing settings',
            'zh-Hans': '账单设置',
            fr: 'Paramètres de facturation',
            ja: '請求設定',
            ko: '결제 설정',
            'zh-Hant': '帳單設定',
          }),
          subtitle: t({
            en: 'Update invoice details, download receipts, and manage your subscription',
            'zh-Hans': '更新发票详情、下载收据并管理您的订阅',
            fr: 'Factures, reçus et abonnement',
            ja: '請求書の更新、領収書のダウンロード、サブスクリプション管理',
            ko: '청구서 업데이트, 영수증 다운로드, 구독 관리',
            'zh-Hant': '更新發票詳情、下載收據並管理訂閱',
          }),
        },
      },
      permissions: {
        title: t({
          en: 'Permissions',
          'zh-Hans': '权限',
          fr: 'Autorisations',
          ja: '権限',
          ko: '권한',
          'zh-Hant': '權限',
        }),
        description: t({
          en: 'Configure organization permission modes and tool access control',
          'zh-Hans': '配置组织的权限模式和工具访问控制',
          fr: 'Modes de permission et accès aux outils',
          ja: '組織の権限モードとツールアクセスを設定',
          ko: '조직 권한 모드 및 도구 접근 제어',
          'zh-Hant': '設定組織權限模式與工具存取控制',
        }),
      },
      security: {
        title: t({
          en: 'Security',
          'zh-Hans': '安全',
          fr: 'Sécurité',
          ja: 'セキュリティ',
          ko: '보안',
          'zh-Hant': '安全',
        }),
        description: t({
          en: 'Manage your security settings',
          'zh-Hans': '管理您的安全设置',
          fr: 'Paramètres de sécurité',
          ja: 'セキュリティ設定を管理',
          ko: '보안 설정 관리',
          'zh-Hant': '管理您的安全設定',
        }),
      },
      notifications: {
        title: t({
          en: 'Notifications',
          'zh-Hans': '通知',
          fr: 'Notifications',
          ja: '通知',
          ko: '알림',
          'zh-Hant': '通知',
        }),
        description: t({
          en: 'Manage your notification preferences',
          'zh-Hans': '管理您的通知偏好',
          fr: 'Préférences de notification',
          ja: '通知設定を管理',
          ko: '알림 환경설정',
          'zh-Hant': '管理您的通知偏好',
        }),
      },
      apiKeys: {
        title: t({
          en: 'API Keys',
          'zh-Hans': 'API 密钥',
          fr: 'Clés API',
          ja: 'API キー',
          ko: 'API 키',
          'zh-Hant': 'API 金鑰',
        }),
        description: t({
          en: 'Manage your API keys',
          'zh-Hans': '管理您的 API 密钥',
          fr: 'Gérer vos clés API',
          ja: 'API キーを管理',
          ko: 'API 키 관리',
          'zh-Hant': '管理您的 API 金鑰',
        }),
      },
    },
    profile: {
      nameLabel: t({
        en: 'Display Name',
        'zh-Hans': '显示名称',
        fr: 'Nom d\'affichage',
        ja: '表示名',
        ko: '표시 이름',
        'zh-Hant': '顯示名稱',
      }),
      namePlaceholder: t({
        en: 'Enter your name',
        'zh-Hans': '输入您的姓名',
        fr: 'Entrez votre nom',
        ja: '名前を入力',
        ko: '이름 입력',
        'zh-Hant': '請輸入您的姓名',
      }),
      emailLabel: t({
        en: 'Email',
        'zh-Hans': '邮箱',
        fr: 'E-mail',
        ja: 'メール',
        ko: '이메일',
        'zh-Hant': '電子郵件',
      }),
      emailLabelReadonly: t({
        en: 'Email (cannot be changed)',
        'zh-Hans': '邮箱（不可更改）',
        fr: 'E-mail (non modifiable)',
        ja: 'メール（変更不可）',
        ko: '이메일(변경 불가)',
        'zh-Hant': '電子郵件（不可變更）',
      }),
      avatarLabel: t({
        en: 'Avatar',
        'zh-Hans': '头像',
        fr: 'Avatar',
        ja: 'アバター',
        ko: '아바타',
        'zh-Hant': '頭像',
      }),
      uploadAvatar: t({
        en: 'Upload new avatar',
        'zh-Hans': '上传新头像',
        fr: 'Télécharger un avatar',
        ja: '新しいアバターをアップロード',
        ko: '새 아바타 업로드',
        'zh-Hant': '上傳新頭像',
      }),
      removeAvatar: t({
        en: 'Remove avatar',
        'zh-Hans': '移除头像',
        fr: 'Supprimer l\'avatar',
        ja: 'アバターを削除',
        ko: '아바타 제거',
        'zh-Hant': '移除頭像',
      }),
    },
    preferences: {
      theme: {
        label: t({
          en: 'Theme',
          'zh-Hans': '主题',
          fr: 'Thème',
          ja: 'テーマ',
          ko: '테마',
          'zh-Hant': '主題',
        }),
        light: t({
          en: 'Light',
          'zh-Hans': '浅色',
          fr: 'Clair',
          ja: 'ライト',
          ko: '라이트',
          'zh-Hant': '淺色',
        }),
        dark: t({
          en: 'Dark',
          'zh-Hans': '深色',
          fr: 'Sombre',
          ja: 'ダーク',
          ko: '다크',
          'zh-Hant': '深色',
        }),
        system: t({
          en: 'System',
          'zh-Hans': '跟随系统',
          fr: 'Système',
          ja: 'システムに従う',
          ko: '시스템 따름',
          'zh-Hant': '跟隨系統',
        }),
      },
      language: {
        label: t({
          en: 'Language',
          'zh-Hans': '语言',
          fr: 'Langue',
          ja: '言語',
          ko: '언어',
          'zh-Hant': '語言',
        }),
        english: t({
          en: 'English',
          'zh-Hans': '英语',
          fr: 'Anglais',
          ja: '英語',
          ko: '영어',
          'zh-Hant': '英語',
        }),
        french: t({
          en: 'French',
          'zh-Hans': '法语',
          fr: 'Français',
          ja: 'フランス語',
          ko: '프랑스어',
          'zh-Hant': '法語',
        }),
        japanese: t({
          en: 'Japanese',
          'zh-Hans': '日语',
          fr: 'Japonais',
          ja: '日本語',
          ko: '일본어',
          'zh-Hant': '日語',
        }),
        korean: t({
          en: 'Korean',
          'zh-Hans': '韩语',
          fr: 'Coréen',
          ja: '韓国語',
          ko: '한국어',
          'zh-Hant': '韓語',
        }),
        chineseSimplified: t({
          en: 'Simplified Chinese',
          'zh-Hans': '简体中文',
          fr: 'Chinois simplifié',
          ja: '簡体字中国語',
          ko: '간체 중국어',
          'zh-Hant': '簡體中文',
        }),
        chineseTraditional: t({
          en: 'Traditional Chinese',
          'zh-Hans': '繁体中文',
          fr: 'Chinois traditionnel',
          ja: '繁体字中国語',
          ko: '번체 중국어',
          'zh-Hant': '繁體中文',
        }),
      },
      timezone: {
        label: t({
          en: 'Timezone',
          'zh-Hans': '时区',
          fr: 'Fuseau horaire',
          ja: 'タイムゾーン',
          ko: '시간대',
          'zh-Hant': '時區',
        }),
      },
    },
    security: {
      changePassword: {
        title: t({
          en: 'Change Password',
          'zh-Hans': '更改密码',
          fr: 'Changer le mot de passe',
          ja: 'パスワードを変更',
          ko: '비밀번호 변경',
          'zh-Hant': '變更密碼',
        }),
        currentPassword: t({
          en: 'Current Password',
          'zh-Hans': '当前密码',
          fr: 'Mot de passe actuel',
          ja: '現在のパスワード',
          ko: '현재 비밀번호',
          'zh-Hant': '目前密碼',
        }),
        newPassword: t({
          en: 'New Password',
          'zh-Hans': '新密码',
          fr: 'Nouveau mot de passe',
          ja: '新しいパスワード',
          ko: '새 비밀번호',
          'zh-Hant': '新密碼',
        }),
        confirmPassword: t({
          en: 'Confirm New Password',
          'zh-Hans': '确认新密码',
          fr: 'Confirmer le nouveau mot de passe',
          ja: '新しいパスワードを確認',
          ko: '새 비밀번호 확인',
          'zh-Hant': '確認新密碼',
        }),
        submitButton: t({
          en: 'Update Password',
          'zh-Hans': '更新密码',
          fr: 'Mettre à jour',
          ja: '更新',
          ko: '비밀번호 업데이트',
          'zh-Hant': '更新密碼',
        }),
      },
      twoFactor: {
        title: t({
          en: 'Two-Factor Authentication',
          'zh-Hans': '双因素认证',
          fr: 'Authentification à deux facteurs',
          ja: '二要素認証',
          ko: '2단계 인증',
          'zh-Hant': '雙因素驗證',
        }),
        description: t({
          en: 'Add an extra layer of security to your account',
          'zh-Hans': '为您的账户添加额外的安全层',
          fr: 'Sécurisez votre compte',
          ja: 'アカウントのセキュリティを強化',
          ko: '계정 보안 강화',
          'zh-Hant': '為您的帳戶增加一層安全保護',
        }),
        enable: t({
          en: 'Enable',
          'zh-Hans': '启用',
          fr: 'Activer',
          ja: '有効にする',
          ko: '활성화',
          'zh-Hant': '啟用',
        }),
        disable: t({
          en: 'Disable',
          'zh-Hans': '禁用',
          fr: 'Désactiver',
          ja: '無効にする',
          ko: '비활성화',
          'zh-Hant': '停用',
        }),
        enabled: t({
          en: 'Enabled',
          'zh-Hans': '已启用',
          fr: 'Activé',
          ja: '有効',
          ko: '활성화됨',
          'zh-Hant': '已啟用',
        }),
        disabled: t({
          en: 'Disabled',
          'zh-Hans': '已禁用',
          fr: 'Désactivé',
          ja: '無効',
          ko: '비활성화됨',
          'zh-Hant': '已停用',
        }),
      },
      sessions: {
        title: t({
          en: 'Active Sessions',
          'zh-Hans': '活跃会话',
          fr: 'Sessions actives',
          ja: 'アクティブなセッション',
          ko: '활성 세션',
          'zh-Hant': '目前會話',
        }),
        description: t({
          en: 'Manage your active sessions across devices',
          'zh-Hans': '管理您在各设备上的活跃会话',
          fr: 'Gérer les sessions sur vos appareils',
          ja: 'デバイス間のセッションを管理',
          ko: '기기별 활성 세션 관리',
          'zh-Hant': '管理您在各裝置上的會話',
        }),
        currentSession: t({
          en: 'Current Session',
          'zh-Hans': '当前会话',
          fr: 'Session actuelle',
          ja: '現在のセッション',
          ko: '현재 세션',
          'zh-Hant': '目前會話',
        }),
        revoke: t({
          en: 'Revoke',
          'zh-Hans': '撤销',
          fr: 'Révoquer',
          ja: '無効にする',
          ko: '해지',
          'zh-Hant': '撤銷',
        }),
        revokeAll: t({
          en: 'Revoke All Other Sessions',
          'zh-Hans': '撤销所有其他会话',
          fr: 'Révoquer toutes les autres sessions',
          ja: '他のセッションをすべて無効にする',
          ko: '다른 모든 세션 해지',
          'zh-Hant': '撤銷所有其他會話',
        }),
      },
    },
    notifications: {
      emailNotifications: {
        label: t({
          en: 'Email Notifications',
          'zh-Hans': '邮件通知',
          fr: 'Notifications par e-mail',
          ja: 'メール通知',
          ko: '이메일 알림',
          'zh-Hant': '電子郵件通知',
        }),
        description: t({
          en: 'Receive updates via email',
          'zh-Hans': '通过邮件接收更新',
          fr: 'Recevoir les mises à jour par e-mail',
          ja: 'メールで更新を受け取る',
          ko: '이메일로 업데이트 수신',
          'zh-Hant': '透過電子郵件接收更新',
        }),
      },
      pushNotifications: {
        label: t({
          en: 'Push Notifications',
          'zh-Hans': '推送通知',
          fr: 'Notifications push',
          ja: 'プッシュ通知',
          ko: '푸시 알림',
          'zh-Hant': '推播通知',
        }),
        description: t({
          en: 'Receive push notifications in your browser',
          'zh-Hans': '在浏览器中接收推送通知',
          fr: 'Recevoir les notifications dans le navigateur',
          ja: 'ブラウザでプッシュ通知を受け取る',
          ko: '브라우저에서 푸시 알림 수신',
          'zh-Hant': '在瀏覽器中接收推播通知',
        }),
      },
      marketingEmails: {
        label: t({
          en: 'Marketing Emails',
          'zh-Hans': '营销邮件',
          fr: 'E-mails marketing',
          ja: 'マーケティングメール',
          ko: '마케팅 이메일',
          'zh-Hant': '行銷郵件',
        }),
        description: t({
          en: 'Receive news and product updates',
          'zh-Hans': '接收新闻和产品更新',
          fr: 'Actualités et nouveautés produit',
          ja: 'ニュースと製品アップデートを受け取る',
          ko: '뉴스 및 제품 업데이트 수신',
          'zh-Hant': '接收新聞與產品更新',
        }),
      },
    },
    apiKeys: {
      createButton: t({
        en: 'Create New API Key',
        'zh-Hans': '创建新的 API 密钥',
        fr: 'Créer une clé API',
        ja: '新しい API キーを作成',
        ko: '새 API 키 만들기',
        'zh-Hant': '建立新的 API 金鑰',
      }),
      nameLabel: t({
        en: 'Name',
        'zh-Hans': '名称',
        fr: 'Nom',
        ja: '名前',
        ko: '이름',
        'zh-Hant': '名稱',
      }),
      namePlaceholder: t({
        en: 'e.g., Production API Key',
        'zh-Hans': '例如：生产环境 API 密钥',
        fr: 'ex. Clé API production',
        ja: '例：本番用 API キー',
        ko: '예: 프로덕션 API 키',
        'zh-Hant': '例如：正式環境 API 金鑰',
      }),
      keyCreated: t({
        en: 'Key created successfully',
        'zh-Hans': '密钥创建成功',
        fr: 'Clé créée',
        ja: 'キーを作成しました',
        ko: '키가 생성되었습니다',
        'zh-Hant': '金鑰建立成功',
      }),
      keyDeleted: t({
        en: 'Key deleted successfully',
        'zh-Hans': '密钥删除成功',
        fr: 'Clé supprimée',
        ja: 'キーを削除しました',
        ko: '키가 삭제되었습니다',
        'zh-Hant': '金鑰已刪除',
      }),
      noKeys: t({
        en: 'No API keys yet',
        'zh-Hans': '暂无 API 密钥',
        fr: 'Aucune clé API',
        ja: 'API キーはまだありません',
        ko: 'API 키가 없습니다',
        'zh-Hant': '尚無 API 金鑰',
      }),
      createdAt: t({
        en: 'Created',
        'zh-Hans': '创建时间',
        fr: 'Créé le',
        ja: '作成日時',
        ko: '생성일',
        'zh-Hant': '建立時間',
      }),
      lastUsed: t({
        en: 'Last Used',
        'zh-Hans': '最后使用',
        fr: 'Dernière utilisation',
        ja: '最終使用',
        ko: '마지막 사용',
        'zh-Hant': '最後使用',
      }),
      never: t({
        en: 'Never',
        'zh-Hans': '从未',
        fr: 'Jamais',
        ja: '未使用',
        ko: '사용 안 함',
        'zh-Hant': '從未',
      }),
      copyKey: t({
        en: 'Copy Key',
        'zh-Hans': '复制密钥',
        fr: 'Copier la clé',
        ja: 'キーをコピー',
        ko: '키 복사',
        'zh-Hant': '複製金鑰',
      }),
      deleteKey: t({
        en: 'Delete Key',
        'zh-Hans': '删除密钥',
        fr: 'Supprimer la clé',
        ja: 'キーを削除',
        ko: '키 삭제',
        'zh-Hant': '刪除金鑰',
      }),
    },
    actions: {
      saveChanges: t({
        en: 'Save Changes',
        'zh-Hans': '保存更改',
        fr: 'Enregistrer',
        ja: '変更を保存',
        ko: '저장',
        'zh-Hant': '儲存變更',
      }),
      cancel: t({
        en: 'Cancel',
        'zh-Hans': '取消',
        fr: 'Annuler',
        ja: 'キャンセル',
        ko: '취소',
        'zh-Hant': '取消',
      }),
      deleteAccount: t({
        en: 'Delete Account',
        'zh-Hans': '删除账户',
        fr: 'Supprimer le compte',
        ja: 'アカウントを削除',
        ko: '계정 삭제',
        'zh-Hant': '刪除帳戶',
      }),
    },
    success: {
      profileUpdated: t({
        en: 'Profile updated successfully',
        'zh-Hans': '个人资料更新成功',
        fr: 'Profil mis à jour',
        ja: 'プロフィールを更新しました',
        ko: '프로필이 업데이트되었습니다',
        'zh-Hant': '個人資料已更新',
      }),
      preferencesUpdated: t({
        en: 'Preferences updated successfully',
        'zh-Hans': '偏好设置更新成功',
        fr: 'Préférences mises à jour',
        ja: '設定を更新しました',
        ko: '환경설정이 업데이트되었습니다',
        'zh-Hant': '偏好設定已更新',
      }),
      passwordUpdated: t({
        en: 'Password updated successfully',
        'zh-Hans': '密码更新成功',
        fr: 'Mot de passe mis à jour',
        ja: 'パスワードを更新しました',
        ko: '비밀번호가 업데이트되었습니다',
        'zh-Hant': '密碼已更新',
      }),
    },
    errors: {
      updateFailed: t({
        en: 'Failed to update settings',
        'zh-Hans': '设置更新失败',
        fr: 'Échec de la mise à jour',
        ja: '設定の更新に失敗しました',
        ko: '설정 업데이트에 실패했습니다',
        'zh-Hant': '設定更新失敗',
      }),
      invalidPassword: t({
        en: 'Current password is incorrect',
        'zh-Hans': '当前密码不正确',
        fr: 'Mot de passe actuel incorrect',
        ja: '現在のパスワードが正しくありません',
        ko: '현재 비밀번호가 올바르지 않습니다',
        'zh-Hant': '目前密碼不正確',
      }),
      weakPassword: t({
        en: 'New password is too weak',
        'zh-Hans': '新密码太弱',
        fr: 'Nouveau mot de passe trop faible',
        ja: '新しいパスワードが弱すぎます',
        ko: '새 비밀번호가 너무 약합니다',
        'zh-Hant': '新密碼強度不足',
      }),
    },

    // Plan Settings
    plans: {
      loadingPlanDetails: t({
        en: 'Loading plan details…',
        'zh-Hans': '加载计划详情中…',
        fr: 'Chargement du plan…',
        ja: 'プラン詳細を読み込み中…',
        ko: '플랜 정보 로딩 중…',
        'zh-Hant': '載入方案詳情中…',
      }),
      failedToLoadPlan: t({
        en: 'Failed to load plan information. Please refresh and try again.',
        'zh-Hans': '加载计划信息失败，请刷新后重试。',
        fr: 'Échec du chargement. Actualisez et réessayez.',
        ja: 'プラン情報の読み込みに失敗しました。更新して再試行してください。',
        ko: '플랜 정보를 불러오지 못했습니다. 새로고침 후 다시 시도하세요.',
        'zh-Hant': '載入方案失敗，請重新整理後再試。',
      }),
      planNotConfigured: t({
        en: 'Plan not configured. Set POLAR product IDs in your environment.',
        'zh-Hans': '计划未配置，请在环境中设置 POLAR 产品 ID。',
        fr: 'Plan non configuré. Définissez les ID produit POLAR.',
        ja: 'プランが設定されていません。環境で POLAR 製品 ID を設定してください。',
        ko: '플랜이 설정되지 않았습니다. POLAR 제품 ID를 설정하세요.',
        'zh-Hant': '方案未設定，請在環境中設定 POLAR 產品 ID。',
      }),
      unableToStartCheckout: t({
        en: 'Unable to start checkout. Please try again.',
        'zh-Hans': '无法启动结账流程，请重试。',
        fr: 'Impossible de lancer le paiement. Réessayez.',
        ja: 'チェックアウトを開始できません。もう一度お試しください。',
        ko: '결제를 시작할 수 없습니다. 다시 시도하세요.',
        'zh-Hant': '無法啟動結帳流程，請重試。',
      }),
      creditPackNotConfigured: t({
        en: 'Credit pack not configured. Add the POLAR_PRODUCT_CREDITS_* env vars.',
        'zh-Hans': '积分包未配置，请添加 POLAR_PRODUCT_CREDITS_* 环境变量。',
        fr: 'Pack de crédits non configuré. Ajoutez les variables POLAR_PRODUCT_CREDITS_*.',
        ja: 'クレジットパックが設定されていません。POLAR_PRODUCT_CREDITS_* 環境変数を追加してください。',
        ko: '크레딧 패키지가 설정되지 않았습니다. POLAR_PRODUCT_CREDITS_* 환경 변수를 추가하세요.',
        'zh-Hant': '點數包未設定，請新增 POLAR_PRODUCT_CREDITS_* 環境變數。',
      }),
      manageInPortal: t({
        en: 'Manage in Portal',
        'zh-Hans': '在门户中管理',
        fr: 'Gérer dans le portail',
        ja: 'ポータルで管理',
        ko: '포털에서 관리',
        'zh-Hant': '在入口管理',
      }),
      downgradeToPro: t({
        en: 'Downgrade to Pro',
        'zh-Hans': '降级到 Pro',
        fr: 'Rétrograder en Pro',
        ja: 'Pro にダウングレード',
        ko: 'Pro로 다운그레이드',
        'zh-Hant': '降級至 Pro',
      }),
      upgradeToPro: t({
        en: 'Upgrade to Pro',
        'zh-Hans': '升级到 Pro',
        fr: 'Passer à Pro',
        ja: 'Pro にアップグレード',
        ko: 'Pro로 업그레이드',
        'zh-Hant': '升級至 Pro',
      }),
      upgradeToBusiness: t({
        en: 'Upgrade to Business',
        'zh-Hans': '升级到 Business',
        fr: 'Passer à Business',
        ja: 'Business にアップグレード',
        ko: 'Business로 업그레이드',
        'zh-Hant': '升級至 Business',
      }),
      chooseBusiness: t({
        en: 'Choose Business',
        'zh-Hans': '选择 Business',
        fr: 'Choisir Business',
        ja: 'Business を選択',
        ko: 'Business 선택',
        'zh-Hant': '選擇 Business',
      }),
      needMoreCredits: t({
        en: 'Need more credits?',
        'zh-Hans': '需要更多积分？',
        fr: 'Besoin de plus de crédits ?',
        ja: 'クレジットを追加しますか？',
        ko: '크레딧이 더 필요하신가요?',
        'zh-Hant': '需要更多點數？',
      }),
      creditPackDescription: t({
        en: 'Purchase one-time credit packs that never expire and apply instantly.',
        'zh-Hans': '购买一次性的积分包，永不过期，即时生效。',
        fr: 'Achetez des packs de crédits à usage unique, sans expiration.',
        ja: '一度きりのクレジットパックを購入。有効期限なし、即時反映。',
        ko: '일회용 크레딧 패키지 구매. 만료 없음, 즉시 적용.',
        'zh-Hant': '購買一次性點數包，永不過期，即時生效。',
      }),
      buy50: t({
        en: 'Buy 50',
        'zh-Hans': '购买 50',
        fr: 'Acheter 50',
        ja: '50 を購入',
        ko: '50 구매',
        'zh-Hant': '購買 50',
      }),
      buy100: t({
        en: 'Buy 100',
        'zh-Hans': '购买 100',
        fr: 'Acheter 100',
        ja: '100 を購入',
        ko: '100 구매',
        'zh-Hant': '購買 100',
      }),
      openBillingPortal: t({
        en: 'Open billing portal',
        'zh-Hans': '打开账单门户',
        fr: 'Ouvrir le portail de facturation',
        ja: '請求ポータルを開く',
        ko: '결제 포털 열기',
        'zh-Hant': '開啟帳單入口',
      }),
      subscriptionUpdated: t({
        en: 'Subscription updated',
        'zh-Hans': '订阅已更新',
        fr: 'Abonnement mis à jour',
        ja: 'サブスクリプションを更新しました',
        ko: '구독이 업데이트되었습니다',
        'zh-Hant': '訂閱已更新',
      }),
      planRefreshed: t({
        en: 'Your plan has been refreshed. Give it a moment if credits take a few seconds to sync.',
        'zh-Hans': '您的计划已刷新，如果积分需要几秒钟同步，请稍候。',
        fr: 'Plan actualisé. Les crédits peuvent prendre quelques secondes à synchroniser.',
        ja: 'プランを更新しました。クレジットの同期に数秒かかる場合があります。',
        ko: '플랜이 새로고침되었습니다. 크레딧 동기화에 몇 초 걸릴 수 있습니다.',
        'zh-Hant': '您的方案已重新整理，點數同步可能需要幾秒，請稍候。',
      }),
      dismissSuccessMessage: t({
        en: 'Dismiss success message',
        'zh-Hans': '关闭成功消息',
        fr: 'Fermer le message',
        ja: '成功メッセージを閉じる',
        ko: '성공 메시지 닫기',
        'zh-Hant': '關閉成功訊息',
      }),
      // Plan names and features
      pro: {
        name: t({ en: 'Pro', 'zh-Hans': 'Pro', fr: 'Pro', ja: 'Pro', ko: 'Pro', 'zh-Hant': 'Pro' }),
        price: t({ en: '$25 / month', 'zh-Hans': '$25 / 月', fr: '25 $/mois', ja: '$25/月', ko: '$25/월', 'zh-Hant': '$25 / 月' }),
        feature1: t({ en: '100 monthly credits', 'zh-Hans': '每月 100 积分', fr: '100 crédits/mois', ja: '月100クレジット', ko: '월 100 크레딧', 'zh-Hant': '每月 100 點數' }),
        feature2: t({ en: 'Private projects', 'zh-Hans': '私有项目', fr: 'Projets privés', ja: 'プライベートプロジェクト', ko: '비공개 프로젝트', 'zh-Hant': '私有專案' }),
        feature3: t({ en: 'Roles & permissions', 'zh-Hans': '角色和权限', fr: 'Rôles et permissions', ja: 'ロールと権限', ko: '역할 및 권한', 'zh-Hant': '角色與權限' }),
      },
      business: {
        name: t({ en: 'Business', 'zh-Hans': 'Business', fr: 'Business', ja: 'Business', ko: 'Business', 'zh-Hant': 'Business' }),
        price: t({ en: '$50 / month', 'zh-Hans': '$50 / 月', fr: '50 $/mois', ja: '$50/月', ko: '$50/월', 'zh-Hant': '$50 / 月' }),
        feature1: t({ en: '150 monthly credits', 'zh-Hans': '每月 150 积分', fr: '150 crédits/mois', ja: '月150クレジット', ko: '월 150 크레딧', 'zh-Hant': '每月 150 點數' }),
        feature2: t({ en: 'SSO & audit logs', 'zh-Hans': 'SSO 和审计日志', fr: 'SSO et journaux d\'audit', ja: 'SSOと監査ログ', ko: 'SSO 및 감사 로그', 'zh-Hant': 'SSO 與稽核紀錄' }),
        feature3: t({ en: 'Priority support', 'zh-Hans': '优先支持', fr: 'Support prioritaire', ja: '優先サポート', ko: '우선 지원', 'zh-Hant': '優先支援' }),
      },
      enterprise: {
        name: t({ en: 'Enterprise', 'zh-Hans': '企业版', fr: 'Enterprise', ja: 'Enterprise', ko: 'Enterprise', 'zh-Hant': '企業版' }),
        price: t({ en: 'Custom', 'zh-Hans': '定制', fr: 'Sur mesure', ja: 'カスタム', ko: '맞춤', 'zh-Hant': '自訂' }),
        feature1: t({ en: 'Dedicated support', 'zh-Hans': '专属支持', fr: 'Support dédié', ja: '専用サポート', ko: '전담 지원', 'zh-Hant': '專屬支援' }),
        feature2: t({ en: 'Onboarding & SLAs', 'zh-Hans': '入职培训和 SLA', fr: 'Intégration et SLA', ja: 'オンボーディングとSLA', ko: '온보딩 및 SLA', 'zh-Hant': '入職培訓與 SLA' }),
        feature3: t({ en: 'Custom integrations', 'zh-Hans': '自定义集成', fr: 'Intégrations sur mesure', ja: 'カスタム連携', ko: '맞춤형 연동', 'zh-Hant': '自訂整合' }),
      },
    },

    // Billing Settings
    billing: {
      loadingBillingDetails: t({
        en: 'Loading billing details…',
        'zh-Hans': '加载账单详情中…',
        fr: 'Chargement des facturation…',
        ja: '請求詳細を読み込み中…',
        ko: '결제 정보 로딩 중…',
        'zh-Hant': '載入帳單詳情中…',
      }),
      failedToLoadBillingProfile: t({
        en: 'Failed to load billing profile',
        'zh-Hans': '加载账单资料失败',
        fr: 'Échec du chargement du profil',
        ja: '請求プロフィールの読み込みに失敗',
        ko: '결제 프로필 로드 실패',
        'zh-Hant': '載入帳單資料失敗',
      }),
      failedToLoadInvoices: t({
        en: 'Failed to load invoices',
        'zh-Hans': '加载发票失败',
        fr: 'Échec du chargement des factures',
        ja: '請求書の読み込みに失敗',
        ko: '청구서 로드 실패',
        'zh-Hant': '載入發票失敗',
      }),
      unableToLoadBillingDetails: t({
        en: 'Unable to load billing details.',
        'zh-Hans': '无法加载账单详情。',
        fr: 'Impossible de charger les détails.',
        ja: '請求詳細を読み込めません。',
        ko: '결제 세부정보를 불러올 수 없습니다.',
        'zh-Hant': '無法載入帳單詳情。',
      }),
      billingEmail: t({
        en: 'Billing email',
        'zh-Hans': '账单邮箱',
        fr: 'E-mail de facturation',
        ja: '請求メール',
        ko: '결제 이메일',
        'zh-Hant': '帳單電子郵件',
      }),
      company: t({
        en: 'Company',
        'zh-Hans': '公司',
        fr: 'Entreprise',
        ja: '会社',
        ko: '회사',
        'zh-Hant': '公司',
      }),
      addressLine1: t({
        en: 'Address line 1',
        'zh-Hans': '地址行 1',
        fr: 'Adresse ligne 1',
        ja: '住所1',
        ko: '주소 1',
        'zh-Hant': '地址行 1',
      }),
      addressLine2: t({
        en: 'Address line 2',
        'zh-Hans': '地址行 2',
        fr: 'Adresse ligne 2',
        ja: '住所2',
        ko: '주소 2',
        'zh-Hant': '地址行 2',
      }),
      city: t({
        en: 'City',
        'zh-Hans': '城市',
        fr: 'Ville',
        ja: '市区町村',
        ko: '도시',
        'zh-Hant': '城市',
      }),
      stateRegion: t({
        en: 'State/Region',
        'zh-Hans': '州/地区',
        fr: 'Région',
        ja: '都道府県',
        ko: '주/지역',
        'zh-Hant': '州/地區',
      }),
      postalCode: t({
        en: 'Postal code',
        'zh-Hans': '邮政编码',
        fr: 'Code postal',
        ja: '郵便番号',
        ko: '우편번호',
        'zh-Hant': '郵遞區號',
      }),
      countryISO: t({
        en: 'Country (ISO)',
        'zh-Hans': '国家（ISO 代码）',
        fr: 'Pays (ISO)',
        ja: '国（ISOコード）',
        ko: '국가(ISO)',
        'zh-Hant': '國家（ISO 代碼）',
      }),
      vatTaxId: t({
        en: 'VAT / Tax ID',
        'zh-Hans': '增值税 / 税号',
        fr: 'TVA / N° fiscal',
        ja: 'VAT/税番号',
        ko: 'VAT/세금 ID',
        'zh-Hant': '增值稅 / 稅號',
      }),
      saving: t({
        en: 'Saving…',
        'zh-Hans': '保存中…',
        fr: 'Enregistrement…',
        ja: '保存中…',
        ko: '저장 중…',
        'zh-Hant': '儲存中…',
      }),
      saveBillingDetails: t({
        en: 'Save billing details',
        'zh-Hans': '保存账单详情',
        fr: 'Enregistrer les détails',
        ja: '請求詳細を保存',
        ko: '결제 세부정보 저장',
        'zh-Hant': '儲存帳單詳情',
      }),
      unableToOpenPortal: t({
        en: 'Unable to open customer portal. Please try again.',
        'zh-Hans': '无法打开客户门户，请重试。',
        fr: 'Impossible d\'ouvrir le portail. Réessayez.',
        ja: 'カスタマーポータルを開けません。もう一度お試しください。',
        ko: '고객 포털을 열 수 없습니다. 다시 시도하세요.',
        'zh-Hant': '無法開啟客戶入口，請重試。',
      }),
      openCustomerPortal: t({
        en: 'Open customer portal',
        'zh-Hans': '打开客户门户',
        fr: 'Ouvrir le portail client',
        ja: 'カスタマーポータルを開く',
        ko: '고객 포털 열기',
        'zh-Hant': '開啟客戶入口',
      }),
      failedToSaveBilling: t({
        en: 'Failed to save billing settings',
        'zh-Hans': '保存账单设置失败',
        fr: 'Échec de l\'enregistrement',
        ja: '請求設定の保存に失敗',
        ko: '결제 설정 저장 실패',
        'zh-Hant': '儲存帳單設定失敗',
      }),
      invoices: t({
        en: 'Invoices',
        'zh-Hans': '发票',
        fr: 'Factures',
        ja: '請求書',
        ko: '청구서',
        'zh-Hant': '發票',
      }),
      invoicesDescription: t({
        en: 'Download receipts or generate invoices for recent purchases.',
        'zh-Hans': '下载收据或为最近的购买生成发票。',
        fr: 'Télécharger les reçus ou générer des factures.',
        ja: '領収書のダウンロードまたは請求書の生成。',
        ko: '영수증 다운로드 또는 최근 구매 청구서 생성.',
        'zh-Hant': '下載收據或為最近購買產生發票。',
      }),
      failedToGenerateInvoice: t({
        en: 'Failed to generate invoice.',
        'zh-Hans': '生成发票失败。',
        fr: 'Échec de la génération de la facture.',
        ja: '請求書の生成に失敗しました。',
        ko: '청구서 생성에 실패했습니다.',
        'zh-Hant': '產生發票失敗。',
      }),
    },

    // Organization Settings
    organization: {
      nameRequired: t({
        en: 'Organization name is required',
        'zh-Hans': '组织名称必填',
        fr: 'Le nom de l\'organisation est requis',
        ja: '組織名は必須です',
        ko: '조직 이름을 입력하세요',
        'zh-Hant': '組織名稱為必填',
      }),
      slugRequired: t({
        en: 'Slug is required',
        'zh-Hans': 'Slug 必填',
        fr: 'Le slug est requis',
        ja: 'Slugは必須です',
        ko: 'Slug를 입력하세요',
        'zh-Hant': 'Slug 為必填',
      }),
      slugInvalid: t({
        en: 'Slug must contain only lowercase letters, numbers, and hyphens',
        'zh-Hans': 'Slug 只能包含小写字母、数字和连字符',
        fr: 'Le slug ne doit contenir que des minuscules, chiffres et tirets',
        ja: 'Slugは小文字、数字、ハイフンのみ使用できます',
        ko: 'Slug는 소문자, 숫자, 하이픈만 사용 가능합니다',
        'zh-Hant': 'Slug 僅能包含小寫字母、數字與連字號',
      }),
      failedToLoadOrganizations: t({
        en: 'Failed to load organizations',
        'zh-Hans': '加载组织失败',
        fr: 'Échec du chargement des organisations',
        ja: '組織の読み込みに失敗',
        ko: '조직 로드 실패',
        'zh-Hant': '載入組織失敗',
      }),
      failedToCreateOrganization: t({
        en: 'Failed to create organization',
        'zh-Hans': '创建组织失败',
        fr: 'Échec de la création de l\'organisation',
        ja: '組織の作成に失敗',
        ko: '조직 생성 실패',
        'zh-Hant': '建立組織失敗',
      }),
      owner: t({
        en: 'Owner',
        'zh-Hans': '所有者',
        fr: 'Propriétaire',
        ja: 'オーナー',
        ko: '소유자',
        'zh-Hant': '擁有者',
      }),
      admin: t({
        en: 'Admin',
        'zh-Hans': '管理员',
        fr: 'Admin',
        ja: '管理者',
        ko: '관리자',
        'zh-Hant': '管理員',
      }),
      member: t({
        en: 'Member',
        'zh-Hans': '成员',
        fr: 'Membre',
        ja: 'メンバー',
        ko: '멤버',
        'zh-Hant': '成員',
      }),
      createOrganization: t({
        en: 'Create Organization',
        'zh-Hans': '创建组织',
        fr: 'Créer une organisation',
        ja: '組織を作成',
        ko: '조직 만들기',
        'zh-Hant': '建立組織',
      }),
      createOrgDescription: t({
        en: 'Create an organization to manage permissions and collaborate with your team. You will automatically become the owner of the organization.',
        'zh-Hans': '创建组织以管理权限并与团队协作。您将自动成为组织的所有者。',
        fr: 'Créez une organisation pour gérer les permissions et collaborer. Vous en serez le propriétaire.',
        ja: '権限の管理とチームとの協働のための組織を作成します。自動的にオーナーになります。',
        ko: '권한 관리 및 팀 협업을 위한 조직을 만드세요. 자동으로 소유자가 됩니다.',
        'zh-Hant': '建立組織以管理權限並與團隊協作。您將自動成為組織擁有者。',
      }),
      orgNameLabel: t({
        en: 'Organization Name *',
        'zh-Hans': '组织名称 *',
        fr: 'Nom de l\'organisation *',
        ja: '組織名 *',
        ko: '조직 이름 *',
        'zh-Hant': '組織名稱 *',
      }),
      orgNamePlaceholder: t({
        en: 'My Organization',
        'zh-Hans': '我的组织',
        fr: 'Mon organisation',
        ja: 'マイ組織',
        ko: '내 조직',
        'zh-Hant': '我的組織',
      }),
      slugLabel: t({
        en: 'Slug (Optional)',
        'zh-Hans': 'Slug（可选）',
        fr: 'Slug (optionnel)',
        ja: 'Slug（任意）',
        ko: 'Slug (선택)',
        'zh-Hant': 'Slug（選填）',
      }),
      slugPlaceholder: t({
        en: 'my-org',
        'zh-Hans': 'my-org',
        fr: 'my-org',
        ja: 'my-org',
        ko: 'my-org',
        'zh-Hant': 'my-org',
      }),
      slugHelpText: t({
        en: 'Unique identifier for your organization. Leave empty to auto-generate.',
        'zh-Hans': '组织的唯一标识符，留空以自动生成。',
        fr: 'Identifiant unique. Laissez vide pour auto-générer.',
        ja: '組織の一意の識別子。空欄で自動生成。',
        ko: '조직 고유 식별자. 비워두면 자동 생성.',
        'zh-Hant': '組織的唯一識別碼，留空則自動產生。',
      }),
      orgCreatedSuccess: t({
        en: 'Organization created successfully! You are now the owner.',
        'zh-Hans': '组织创建成功！您现在是所有者。',
        fr: 'Organisation créée ! Vous en êtes le propriétaire.',
        ja: '組織を作成しました。オーナーになりました。',
        ko: '조직이 생성되었습니다. 소유자입니다.',
        'zh-Hant': '組織已建立！您現在是擁有者。',
      }),
      creating: t({
        en: 'Creating...',
        'zh-Hans': '创建中...',
        fr: 'Création…',
        ja: '作成中…',
        ko: '생성 중…',
        'zh-Hant': '建立中…',
      }),
      createOrgButton: t({
        en: 'Create Organization',
        'zh-Hans': '创建组织',
        fr: 'Créer l\'organisation',
        ja: '組織を作成',
        ko: '조직 만들기',
        'zh-Hant': '建立組織',
      }),
      yourOrganizations: t({
        en: 'Your Organizations',
        'zh-Hans': '您的组织',
        fr: 'Vos organisations',
        ja: 'あなたの組織',
        ko: '내 조직',
        'zh-Hant': '您的組織',
      }),
      yourOrgsDescription: t({
        en: 'Organizations you are a member of',
        'zh-Hans': '您所属的组织',
        fr: 'Organisations dont vous êtes membre',
        ja: '所属している組織',
        ko: '소속된 조직',
        'zh-Hant': '您所屬的組織',
      }),
      loading: t({
        en: 'Loading...',
        'zh-Hans': '加载中...',
        fr: 'Chargement…',
        ja: '読み込み中…',
        ko: '로딩 중…',
        'zh-Hant': '載入中…',
      }),
      noOrganizations: t({
        en: 'You are not a member of any organization yet. Create one above to get started.',
        'zh-Hans': '您还不是任何组织的成员，请在上方创建一个以开始。',
        fr: 'Vous n\'êtes membre d\'aucune organisation. Créez-en une ci-dessus.',
        ja: 'まだどの組織にも所属していません。上で作成して開始してください。',
        ko: '아직 어떤 조직에도 소속되어 있지 않습니다. 위에서 생성하세요.',
        'zh-Hant': '您尚非任何組織成員，請在上方建立一個以開始。',
      }),
      slug: t({
        en: 'Slug: {slug}',
        'zh-Hans': 'Slug：{slug}',
        fr: 'Slug : {slug}',
        ja: 'Slug: {slug}',
        ko: 'Slug: {slug}',
        'zh-Hant': 'Slug：{slug}',
      }),
      orgOwnerBenefits: t({
        en: 'Organization Owner Benefits: As an organization owner, you can configure permission modes, enable Bash tool access, and manage team members. Visit the Permissions settings after creating an organization.',
        'zh-Hans': '组织所有者权益：作为组织所有者，您可以配置权限模式、启用 Bash 工具访问并管理团队成员。创建组织后请访问权限设置。',
        fr: 'En tant que propriétaire, vous pouvez configurer les permissions, activer Bash et gérer les membres. Voir Paramètres > Permissions après création.',
        ja: 'オーナーは権限モードの設定、Bash ツールの有効化、メンバー管理ができます。組織作成後は権限設定をご確認ください。',
        ko: '소유자는 권한 모드 설정, Bash 도구 활성화, 멤버 관리가 가능합니다. 조직 생성 후 권한 설정을 확인하세요.',
        'zh-Hant': '組織擁有者權益：您可設定權限模式、啟用 Bash 工具並管理成員。建立組織後請至權限設定。',
      }),
    },

    // Preferences Settings
    ui: {
      interfaceTheme: t({
        en: 'Interface & Theme',
        'zh-Hans': '界面与主题',
        fr: 'Interface et thème',
        ja: 'インターフェースとテーマ',
        ko: '인터페이스 및 테마',
        'zh-Hant': '介面與主題',
      }),
      customizeAppearance: t({
        en: 'Customize the appearance of your Codefetch interface',
        'zh-Hans': '自定义 Codefetch 界面的外观',
        fr: 'Personnaliser l\'apparence de l\'interface',
        ja: 'インターフェースの外観をカスタマイズ',
        ko: '인터페이스 모양 사용자 지정',
        'zh-Hant': '自訂介面外觀',
      }),
      theme: t({
        en: 'Theme',
        'zh-Hans': '主题',
        fr: 'Thème',
        ja: 'テーマ',
        ko: '테마',
        'zh-Hant': '主題',
      }),
      light: t({
        en: 'Light',
        'zh-Hans': '浅色',
        fr: 'Clair',
        ja: 'ライト',
        ko: '라이트',
        'zh-Hant': '淺色',
      }),
      dark: t({
        en: 'Dark',
        'zh-Hans': '深色',
        fr: 'Sombre',
        ja: 'ダーク',
        ko: '다크',
        'zh-Hant': '深色',
      }),
      system: t({
        en: 'System',
        'zh-Hans': '系统',
        fr: 'Système',
        ja: 'システム',
        ko: '시스템',
        'zh-Hant': '系統',
      }),
      lightDescription: t({
        en: 'Bright and clean interface',
        'zh-Hans': '明亮清爽的界面',
        fr: 'Interface lumineuse et épurée',
        ja: '明るくすっきりしたインターフェース',
        ko: '밝고 깔끔한 인터페이스',
        'zh-Hant': '明亮清爽的介面',
      }),
      darkDescription: t({
        en: 'Easy on the eyes in low light',
        'zh-Hans': '弱光下保护眼睛',
        fr: 'Confortable en faible luminosité',
        ja: '暗い環境で目に優しい',
        ko: '어두운 환경에 적합',
        'zh-Hant': '弱光下較不傷眼',
      }),
      systemDescription: t({
        en: 'Follow your system preference',
        'zh-Hans': '跟随系统偏好',
        fr: 'Suivre les préférences système',
        ja: 'システムの設定に従う',
        ko: '시스템 설정 따름',
        'zh-Hant': '跟隨系統偏好',
      }),
      currentTheme: t({
        en: 'Current Theme',
        'zh-Hans': '当前主题',
        fr: 'Thème actuel',
        ja: '現在のテーマ',
        ko: '현재 테마',
        'zh-Hant': '目前主題',
      }),
      mode: t({
        en: '{theme} mode',
        'zh-Hans': '{theme} 模式',
        fr: 'Mode {theme}',
        ja: '{theme} モード',
        ko: '{theme} 모드',
        'zh-Hant': '{theme} 模式',
      }),
      languageTitle: t({
        en: 'Language',
        'zh-Hans': '语言',
        fr: 'Langue',
        ja: '言語',
        ko: '언어',
        'zh-Hant': '語言',
      }),
      languageDescription: t({
        en: 'Choose the display language for the interface',
        'zh-Hans': '选择界面显示语言',
        fr: 'Choisir la langue d\'affichage',
        ja: '表示言語を選択',
        ko: '인터페이스 표시 언어 선택',
        'zh-Hant': '選擇介面顯示語言',
      }),
      currentLanguage: t({
        en: 'Current Language',
        'zh-Hans': '当前语言',
        fr: 'Langue actuelle',
        ja: '現在の言語',
        ko: '현재 언어',
        'zh-Hant': '目前語言',
      }),
    },
  },
  key: 'settings',
} satisfies Dictionary;

export default settingsContent;
