import type { Dictionary } from 'intlayer';
import { t } from 'intlayer';

const skillsContent = {
  content: {
    // Route header
    header: {
      title: t({ en: 'Skills Management', 'zh-Hans': 'Skills 管理', fr: 'Gestion Skills', ja: 'Skills 管理', ko: 'Skills 관리', 'zh-Hant': 'Skills 管理' }),
      description: t({
        en: 'Manage your AI skills ({count} skills)',
        'zh-Hans': '管理您的 AI 技能（{count} 个）',
        fr: 'Gérer vos Skills IA ({count} skills)',
        ja: 'AI スキルを管理（{count} 件）',
        ko: 'AI 스킬 관리 ({count}개)',
        'zh-Hant': '管理您的 AI 技能（{count} 個）',
      }),
      uploadButton: t({ en: 'Upload New Skill', 'zh-Hans': '上传新技能', fr: 'Télécharger un Skill', ja: '新規スキルをアップロード', ko: '새 스킬 업로드', 'zh-Hant': '上傳新技能' }),
      githubInstallButton: t({ en: 'GitHub Install', 'zh-Hans': 'GitHub 安装', fr: 'Installer via GitHub', ja: 'GitHub インストール', ko: 'GitHub 설치', 'zh-Hant': 'GitHub 安裝' }),
    },

    // Categories
    categories: {
      all: t({ en: 'All Skills', 'zh-Hans': 'All Skills', fr: 'Tous les Skills', ja: 'すべてのスキル', ko: '모든 Skills', 'zh-Hant': 'All Skills' }),
      development: t({ en: 'Development', 'zh-Hans': 'Development', fr: 'Développement', ja: 'Development', ko: 'Development', 'zh-Hant': 'Development' }),
      design: t({ en: 'Design', 'zh-Hans': 'Design', fr: 'Design', ja: 'Design', ko: 'Design', 'zh-Hant': 'Design' }),
      productivity: t({ en: 'Productivity', 'zh-Hans': 'Productivity', fr: 'Productivité', ja: 'Productivity', ko: 'Productivity', 'zh-Hant': 'Productivity' }),
      integration: t({ en: 'Integration', 'zh-Hans': 'Integration', fr: 'Intégration', ja: 'Integration', ko: 'Integration', 'zh-Hant': 'Integration' }),
      installed: t({ en: 'Installed', 'zh-Hans': 'Installed', fr: 'Installés', ja: 'インストール済み', ko: '설치됨', 'zh-Hant': 'Installed' }),
    },

    // Sidebar
    sidebar: {
      title: t({ en: 'Skills', 'zh-Hans': 'Skills', fr: 'Skills', ja: 'Skills', ko: 'Skills', 'zh-Hant': 'Skills' }),
    },

    // Toolbar
    toolbar: {
      searchPlaceholder: t({ en: 'Search skills...', 'zh-Hans': '搜索技能...', fr: 'Rechercher des skills...', ja: 'スキルを検索...', ko: '스킬 검색...', 'zh-Hant': '搜尋技能...' }),
      allSkills: t({ en: 'All Skills', 'zh-Hans': 'All Skills', fr: 'Tous les Skills', ja: 'すべてのスキル', ko: '모든 Skills', 'zh-Hant': 'All Skills' }),
      refresh: t({ en: 'Refresh', 'zh-Hans': '刷新', fr: 'Actualiser', ja: '更新', ko: '새로고침', 'zh-Hant': '重新整理' }),
      newSkill: t({ en: 'New skill', 'zh-Hans': '新建技能', fr: 'Nouveau skill', ja: '新規スキル', ko: '새 스킬', 'zh-Hant': '新建技能' }),
    },

    // Page
    page: {
      title: t({ en: 'Skills', 'zh-Hans': 'Skills', fr: 'Skills', ja: 'Skills', ko: 'Skills', 'zh-Hant': 'Skills' }),
      subtitle: t({ en: 'Give your AI superpowers.', 'zh-Hans': '赋予你的 AI 超能力。', fr: 'Donnez des super pouvoirs à votre IA.', ja: 'AI に超能力を与えましょう。', ko: 'AI에게 초능력을 부여하세요.', 'zh-Hant': '賦予你的 AI 超能力。' }),
      learnMore: t({ en: 'Learn more', 'zh-Hans': '了解更多', fr: 'En savoir plus', ja: '詳細を見る', ko: '더 알아보기', 'zh-Hant': '了解更多' }),
    },

    // Sections
    sections: {
      installed: t({ en: 'Installed', 'zh-Hans': '已安装', fr: 'Installés', ja: 'インストール済み', ko: '설치됨', 'zh-Hant': '已安裝' }),
      recommended: t({ en: 'Recommended', 'zh-Hans': '推荐', fr: 'Recommandés', ja: 'おすすめ', ko: '추천', 'zh-Hant': '推薦' }),
    },

    // Curated catalog (DB-backed curated-100 preview — Skills S1a)
    curated: {
      title: t({ en: 'Curated Skill Library', 'zh-Hans': '精选技能库', fr: 'Bibliothèque de Skills sélectionnés', ja: '厳選スキルライブラリ', ko: '엄선 스킬 라이브러리', 'zh-Hant': '精選技能庫' }),
      previewBadge: t({ en: 'Preview', 'zh-Hans': '预览', fr: 'Aperçu', ja: 'プレビュー', ko: '미리보기', 'zh-Hant': '預覽' }),
      subtitle: t({
        en: 'A curated catalog of high-quality skills. Enabling them inside the agent is coming soon.',
        'zh-Hans': '精选的高质量技能目录。在 agent 中启用运行即将支持。',
        fr: 'Un catalogue de skills de qualité. L\'activation dans l\'agent arrive bientôt.',
        ja: '厳選された高品質スキルのカタログ。エージェント内での有効化は近日対応。',
        ko: '엄선된 고품질 스킬 카탈로그. 에이전트 내 활성화는 곧 지원됩니다.',
        'zh-Hant': '精選的高品質技能目錄。在 agent 中啟用執行即將支援。',
      }),
      count: t({ en: '{count} curated skills', 'zh-Hans': '{count} 个精选技能', fr: '{count} skills sélectionnés', ja: '{count} 件の厳選スキル', ko: '엄선 스킬 {count}개', 'zh-Hant': '{count} 個精選技能' }),
      searchPlaceholder: t({ en: 'Search curated skills...', 'zh-Hans': '搜索精选技能...', fr: 'Rechercher...', ja: '厳選スキルを検索...', ko: '엄선 스킬 검색...', 'zh-Hant': '搜尋精選技能...' }),
      allCategories: t({ en: 'All', 'zh-Hans': '全部', fr: 'Tous', ja: 'すべて', ko: '전체', 'zh-Hant': '全部' }),
      viewOnGithub: t({ en: 'View on GitHub', 'zh-Hans': '在 GitHub 查看', fr: 'Voir sur GitHub', ja: 'GitHub で見る', ko: 'GitHub에서 보기', 'zh-Hant': '在 GitHub 檢視' }),
      empty: t({ en: 'No curated skills match your filters', 'zh-Hans': '没有符合条件的精选技能', fr: 'Aucun skill ne correspond', ja: '条件に合う厳選スキルがありません', ko: '조건에 맞는 엄선 스킬이 없습니다', 'zh-Hant': '沒有符合條件的精選技能' }),
      categories: {
        ai_engineering: t({ en: 'AI Engineering', 'zh-Hans': 'AI 工程', fr: 'Ingénierie IA', ja: 'AI エンジニアリング', ko: 'AI 엔지니어링', 'zh-Hant': 'AI 工程' }),
        research: t({ en: 'Research', 'zh-Hans': '研究', fr: 'Recherche', ja: 'リサーチ', ko: '리서치', 'zh-Hant': '研究' }),
        writing: t({ en: 'Writing', 'zh-Hans': '写作', fr: 'Rédaction', ja: 'ライティング', ko: '글쓰기', 'zh-Hant': '寫作' }),
        design_frontend: t({ en: 'Design & Frontend', 'zh-Hans': '设计与前端', fr: 'Design & Frontend', ja: 'デザイン・フロント', ko: '디자인·프론트', 'zh-Hant': '設計與前端' }),
        automation: t({ en: 'Automation', 'zh-Hans': '自动化', fr: 'Automatisation', ja: '自動化', ko: '자동화', 'zh-Hant': '自動化' }),
        learning: t({ en: 'Learning', 'zh-Hans': '学习', fr: 'Apprentissage', ja: '学習', ko: '학습', 'zh-Hant': '學習' }),
        security: t({ en: 'Security', 'zh-Hans': '安全', fr: 'Sécurité', ja: 'セキュリティ', ko: '보안', 'zh-Hant': '安全' }),
      },
    },

    // Empty state
    empty: {
      title: t({ en: 'No skills found', 'zh-Hans': '未找到技能', fr: 'Aucun skill trouvé', ja: 'スキルが見つかりません', ko: '스킬을 찾을 수 없습니다', 'zh-Hant': '未找到技能' }),
      subtitle: t({ en: 'Try adjusting your search or filter', 'zh-Hans': '尝试调整搜索或筛选条件', fr: 'Modifiez la recherche ou les filtres', ja: '検索またはフィルターを調整してください', ko: '검색 또는 필터를 조정해 보세요', 'zh-Hant': '嘗試調整搜尋或篩選條件' }),
    },

    // Skill card
    card: {
      globalEnabled: t({ en: 'Globally Enabled', 'zh-Hans': '全局启用中', fr: 'Activé globalement', ja: 'グローバルで有効', ko: '전역 활성화', 'zh-Hant': '全域啟用中' }),
      custom: t({ en: 'Custom', 'zh-Hans': '自定义', fr: 'Personnalisé', ja: 'カスタム', ko: '맞춤', 'zh-Hant': '自訂' }),
      github: t({ en: 'GitHub', 'zh-Hans': 'GitHub', fr: 'GitHub', ja: 'GitHub', ko: 'GitHub', 'zh-Hant': 'GitHub' }),
      enableButton: t({ en: 'Enable', 'zh-Hans': '启用', fr: 'Activer', ja: '有効にする', ko: '활성화', 'zh-Hant': '啟用' }),
      disableButton: t({ en: 'Disable', 'zh-Hans': '禁用', fr: 'Désactiver', ja: '無効にする', ko: '비활성화', 'zh-Hant': '停用' }),
      globalLabel: t({ en: 'Global', 'zh-Hans': '全局', fr: 'Global', ja: 'グローバル', ko: '전역', 'zh-Hant': '全域' }),
      manageSchemaTitle: t({ en: 'Manage Schema', 'zh-Hans': '管理 Schema', fr: 'Gérer le Schema', ja: 'Schema を管理', ko: 'Schema 관리', 'zh-Hant': '管理 Schema' }),
      viewDetailsTitle: t({ en: 'View Details', 'zh-Hans': '查看详情', fr: 'Voir les détails', ja: '詳細を見る', ko: '상세 보기', 'zh-Hant': '查看詳情' }),
      deleteCustomTitle: t({ en: 'Delete Custom Skill', 'zh-Hans': '删除自定义技能', fr: 'Supprimer le Skill personnalisé', ja: 'カスタムスキルを削除', ko: '맞춤 스킬 삭제', 'zh-Hant': '刪除自訂技能' }),
      deleteGithubTitle: t({ en: 'Delete GitHub-installed Skill', 'zh-Hans': '删除 GitHub 安装的技能', fr: 'Supprimer le Skill GitHub', ja: 'GitHub インストールスキルを削除', ko: 'GitHub 설치 스킬 삭제', 'zh-Hant': '刪除 GitHub 安裝的技能' }),
      regenerateIconTitle: t({ en: 'Regenerate Icon', 'zh-Hans': '重新生成图标', fr: 'Régénérer l\'icône', ja: 'アイコンを再生成', ko: '아이콘 재생성', 'zh-Hant': '重新生成圖標' }),
      enabledTooltip: t({ en: 'Globally enabled, cannot disable', 'zh-Hans': '已全局启用，无法关闭', fr: 'Activé globalement, impossible à désactiver', ja: 'グローバルで有効、無効にできません', ko: '전역 활성화됨, 비활성화 불가', 'zh-Hant': '已全域啟用，無法關閉' }),
      schemaStatus: {
        missing: t({ en: 'Missing', 'zh-Hans': 'Missing', fr: 'Manquant', ja: 'Missing', ko: 'Missing', 'zh-Hant': 'Missing' }),
        valid: t({ en: 'Valid', 'zh-Hans': 'Valid', fr: 'Valide', ja: 'Valid', ko: 'Valid', 'zh-Hant': 'Valid' }),
        invalid: t({ en: 'Invalid', 'zh-Hans': 'Invalid', fr: 'Invalide', ja: 'Invalid', ko: 'Invalid', 'zh-Hant': 'Invalid' }),
        stale: t({ en: 'Stale', 'zh-Hans': 'Stale', fr: 'Obsolète', ja: 'Stale', ko: 'Stale', 'zh-Hant': 'Stale' }),
        failed: t({ en: 'Failed', 'zh-Hans': 'Failed', fr: 'Échec', ja: 'Failed', ko: 'Failed', 'zh-Hant': 'Failed' }),
        loading: t({ en: 'Loading', 'zh-Hans': 'Loading', fr: 'Chargement', ja: 'Loading', ko: 'Loading', 'zh-Hant': 'Loading' }),
      },
    },

    // Toast messages
    toast: {
      skillNotFound: t({ en: 'Skill not found', 'zh-Hans': '未找到技能', fr: 'Skill introuvable', ja: 'スキルが見つかりません', ko: '스킬을 찾을 수 없습니다', 'zh-Hant': '未找到技能' }),
      globalEnabledError: t({
        en: 'This skill has been globally enabled by administrator and cannot be disabled.',
        'zh-Hans': '该技能已被管理员全局启用，无法关闭。',
        fr: 'Ce skill a été activé globalement par l\'admin et ne peut pas être désactivé.',
        ja: 'このスキルは管理者によりグローバルで有効化されており、無効にできません。',
        ko: '이 스킬은 관리자가 전역 활성화하여 비활성화할 수 없습니다.',
        'zh-Hant': '該技能已被管理員全域啟用，無法關閉。',
      }),
      toggleFailed: t({ en: 'Failed to toggle skill', 'zh-Hans': '启用技能失败', fr: 'Échec du basculement du skill', ja: 'スキルの切り替えに失敗しました', ko: '스킬 전환 실패', 'zh-Hant': '啟用技能失敗' }),
      skillNotSynced: t({
        en: 'Skill not synced to runtime directory: {slug}. Current enable will not take effect.',
        'zh-Hans': '技能未同步到运行时目录：{slug}。当前启用不会生效。',
        fr: 'Skill non synchronisé : {slug}. L\'activation actuelle ne prendra pas effet.',
        ja: 'スキルがランタイムに同期されていません：{slug}。現在の有効化は反映されません。',
        ko: '스킬이 런타임 디렉터리에 동기화되지 않음: {slug}. 현재 활성화는 적용되지 않습니다.',
        'zh-Hant': '技能未同步至執行時目錄：{slug}。目前啟用不會生效。',
      }),
      globalEnableFailed: t({ en: 'Failed to enable globally', 'zh-Hans': '全局启用失败', fr: 'Échec de l\'activation globale', ja: 'グローバル有効化に失敗しました', ko: '전역 활성화 실패', 'zh-Hant': '全域啟用失敗' }),
      cannotDeleteOfficial: t({
        en: 'This is a built-in skill and cannot be deleted.',
        'zh-Hans': '这是内置技能，无法删除',
        fr: 'Skill intégré, impossible à supprimer.',
        ja: '組み込みスキルのため削除できません。',
        ko: '내장 스킬이라 삭제할 수 없습니다.',
        'zh-Hant': '這是內建技能，無法刪除',
      }),
      deleteConfirmCustom: t({
        en: 'Are you sure you want to delete this custom skill? This action cannot be undone.',
        'zh-Hans': '确定要删除这个自定义技能吗？此操作无法撤销。',
        fr: 'Supprimer ce skill personnalisé ? Cette action est irréversible.',
        ja: 'このカスタムスキルを削除しますか？元に戻せません。',
        ko: '이 맞춤 스킬을 삭제할까요? 되돌릴 수 없습니다.',
        'zh-Hant': '確定要刪除這個自訂技能嗎？此操作無法復原。',
      }),
      deleteConfirmGithub: t({
        en: 'Are you sure you want to delete this GitHub skill from the global store? All users will no longer see this skill.',
        'zh-Hans': '确定要从全局技能库删除这个 GitHub 技能吗？所有用户将无法再看到此技能。',
        fr: 'Supprimer ce skill GitHub du store global ? Tous les utilisateurs ne le verront plus.',
        ja: 'グローバルストアからこの GitHub スキルを削除しますか？全ユーザーから非表示になります。',
        ko: '전역 스토어에서 이 GitHub 스킬을 삭제할까요? 모든 사용자에게서 사라집니다.',
        'zh-Hant': '確定要從全域技能庫刪除這個 GitHub 技能嗎？所有使用者將無法再看到此技能。',
      }),
      deleteFailed: t({ en: 'Failed to delete skill', 'zh-Hans': '删除技能失败', fr: 'Échec de la suppression du skill', ja: 'スキルの削除に失敗しました', ko: '스킬 삭제 실패', 'zh-Hant': '刪除技能失敗' }),
      iconGenerating: t({ en: 'Generating icon...', 'zh-Hans': '正在生成图标...', fr: 'Génération de l\'icône...', ja: 'アイコンを生成中...', ko: '아이콘 생성 중...', 'zh-Hant': '正在生成圖標...' }),
      iconGenerated: t({ en: 'Icon generated successfully', 'zh-Hans': '图标生成成功', fr: 'Icône générée avec succès', ja: 'アイコンが生成されました', ko: '아이콘이 생성되었습니다', 'zh-Hant': '圖標生成成功' }),
      iconGenerateFailed: t({ en: 'Failed to generate icon', 'zh-Hans': '图标生成失败', fr: 'Échec de la génération de l\'icône', ja: 'アイコンの生成に失敗しました', ko: '아이콘 생성 실패', 'zh-Hant': '圖標生成失敗' }),
    },

    // Upload dialog
    upload: {
      title: t({ en: 'Upload Skill', 'zh-Hans': '上传技能', fr: 'Télécharger un Skill', ja: 'スキルをアップロード', ko: '스킬 업로드', 'zh-Hant': '上傳技能' }),
      description: t({
        en: 'Upload a skill package containing SKILL.md, supports .zip or .skill format',
        'zh-Hans': '上传包含 SKILL.md 的技能包，支持 .zip 或 .skill 格式',
        fr: 'Uploadez un paquet contenant SKILL.md, formats .zip ou .skill',
        ja: 'SKILL.md を含むスキルパッケージをアップロード、.zip または .skill 対応',
        ko: 'SKILL.md를 포함한 스킬 패키지 업로드, .zip 또는 .skill 형식',
        'zh-Hant': '上傳包含 SKILL.md 的技能包，支援 .zip 或 .skill 格式',
      }),
      dragPrompt: t({
        en: 'Drag and drop file here, or',
        'zh-Hans': '拖拽文件到此处，或',
        fr: 'Glissez-déposez le fichier ici, ou',
        ja: 'ここにファイルをドラッグ＆ドロップ、または',
        ko: '파일을 여기에 끌어다 놓거나',
        'zh-Hant': '拖曳檔案到此處，或',
      }),
      clickToSelect: t({ en: 'Click to select file', 'zh-Hans': '点击选择文件', fr: 'Cliquez pour sélectionner', ja: 'クリックしてファイルを選択', ko: '클릭하여 파일 선택', 'zh-Hant': '點擊選擇檔案' }),
      formatHelp: t({
        en: 'Supports .zip or .skill format, max 10 MB. Must contain SKILL.md file.',
        'zh-Hans': 'Supports .zip or .skill format, max 10 MB<br />Must contain SKILL.md file',
        fr: 'Formats .zip ou .skill, max 10 Mo. Doit contenir SKILL.md.',
        ja: '.zip または .skill、最大 10 MB。SKILL.md 必須。',
        ko: '.zip 또는 .skill, 최대 10MB. SKILL.md 필수.',
        'zh-Hant': '支援 .zip 或 .skill，最大 10 MB。須包含 SKILL.md。',
      }),
      parsing: t({ en: 'Parsing file...', 'zh-Hans': '解析文件中...', fr: 'Analyse du fichier...', ja: 'ファイルを解析中...', ko: '파일 파싱 중...', 'zh-Hant': '解析檔案中...' }),
      filesCount: t({ en: '{count} files', 'zh-Hans': '{count} 个文件', fr: '{count} fichier(s)', ja: '{count} ファイル', ko: '파일 {count}개', 'zh-Hant': '{count} 個檔案' }),
      reselect: t({ en: 'Reselect', 'zh-Hans': '重新选择', fr: 'Resélectionner', ja: '再選択', ko: '다시 선택', 'zh-Hant': '重新選擇' }),
      compatibilityWarning: t({ en: 'Compatibility Warning', 'zh-Hans': '兼容性警告', fr: 'Avertissement de compatibilité', ja: '互換性の警告', ko: '호환성 경고', 'zh-Hant': '相容性警告' }),
      compatibilityAdvice: t({
        en: 'Install with caution. If you still want to upload, click "Upload" again to continue.',
        'zh-Hans': '建议谨慎安装。如仍要上传，请再次点击"上传"按钮继续。',
        fr: 'Installez avec précaution. Pour continuer, recliquez sur "Télécharger".',
        ja: '注意してインストールしてください。続行するには「アップロード」を再度クリック。',
        ko: '주의해서 설치하세요. 계속하려면 "업로드"를 다시 클릭하세요.',
        'zh-Hant': '建議謹慎安裝。如仍要上傳，請再次點擊「上傳」繼續。',
      }),
      recheck: t({ en: 'Recheck', 'zh-Hans': '重新检查', fr: 'Revérifier', ja: '再確認', ko: '다시 확인', 'zh-Hant': '重新檢查' }),
      cancel: t({ en: 'Cancel', 'zh-Hans': '取消', fr: 'Annuler', ja: 'キャンセル', ko: '취소', 'zh-Hant': '取消' }),
      uploadButton: t({ en: 'Upload', 'zh-Hans': '上传', fr: 'Télécharger', ja: 'アップロード', ko: '업로드', 'zh-Hant': '上傳' }),
      checking: t({ en: 'Checking...', 'zh-Hans': '检查中...', fr: 'Vérification...', ja: '確認中...', ko: '확인 중...', 'zh-Hant': '檢查中...' }),
      uploading: t({ en: 'Uploading...', 'zh-Hans': '上传中...', fr: 'Téléchargement...', ja: 'アップロード中...', ko: '업로드 중...', 'zh-Hant': '上傳中...' }),
      stillUpload: t({ en: 'Upload Anyway', 'zh-Hans': '仍然上传', fr: 'Quand même télécharger', ja: 'それでもアップロード', ko: '그래도 업로드', 'zh-Hant': '仍然上傳' }),
      errorInvalidFormat: t({
        en: 'Only .zip or .skill format files are supported',
        'zh-Hans': '仅支持 .zip 或 .skill 格式的文件',
        fr: 'Seuls les formats .zip ou .skill sont acceptés',
        ja: '.zip または .skill 形式のみ対応',
        ko: '.zip 또는 .skill 형식만 지원',
        'zh-Hant': '僅支援 .zip 或 .skill 格式的檔案',
      }),
      errorFileSize: t({ en: 'File size cannot exceed 10 MB', 'zh-Hans': '文件大小不能超过 10 MB', fr: 'Taille max 10 Mo', ja: 'ファイルサイズは10MB以内', ko: '파일 크기 10MB 이하', 'zh-Hant': '檔案大小不能超過 10 MB' }),
      errorTooManyFiles: t({ en: 'File count exceeds limit (max 100 files)', 'zh-Hans': '文件数量超过限制（最多 100 个文件）', fr: 'Max 100 fichiers', ja: '100ファイル以内', ko: '최대 100개 파일', 'zh-Hant': '檔案數量超過限制（最多 100 個檔案）' }),
      errorNoSkillMd: t({ en: 'Skill package must contain SKILL.md file', 'zh-Hans': '技能包必须包含 SKILL.md 文件', fr: 'Le paquet doit contenir SKILL.md', ja: 'SKILL.md ファイルが必須です', ko: 'SKILL.md 파일 필수', 'zh-Hant': '技能包須包含 SKILL.md 檔案' }),
      errorParseFailed: t({ en: 'Failed to parse file', 'zh-Hans': '解析文件失败', fr: 'Échec de l\'analyse du fichier', ja: 'ファイルの解析に失敗しました', ko: '파일 파싱 실패', 'zh-Hant': '解析檔案失敗' }),
      errorSelectFile: t({ en: 'Please select a valid skill package first', 'zh-Hans': '请先选择有效的技能包', fr: 'Veuillez sélectionner un paquet skill valide', ja: '有効なスキルパッケージを選択してください', ko: '유효한 스킬 패키지를 먼저 선택하세요', 'zh-Hant': '請先選擇有效的技能包' }),
      errorCompatCheck: t({ en: 'Compatibility check failed', 'zh-Hans': '兼容性检查失败', fr: 'Échec de la vérification de compatibilité', ja: '互換性チェックに失敗しました', ko: '호환성 확인 실패', 'zh-Hant': '相容性檢查失敗' }),
      errorUploadFailed: t({ en: 'Upload failed', 'zh-Hans': '上传失败', fr: 'Échec du téléchargement', ja: 'アップロードに失敗しました', ko: '업로드 실패', 'zh-Hant': '上傳失敗' }),
      errorNoSkillMdFound: t({ en: 'SKILL.md file not found', 'zh-Hans': '未找到 SKILL.md 文件', fr: 'Fichier SKILL.md introuvable', ja: 'SKILL.md ファイルが見つかりません', ko: 'SKILL.md 파일 없음', 'zh-Hant': '未找到 SKILL.md 檔案' }),
    },

    // GitHub installer
    github: {
      title: t({ en: 'Install from GitHub', 'zh-Hans': '从 GitHub 安装技能', fr: 'Installer depuis GitHub', ja: 'GitHub からインストール', ko: 'GitHub에서 설치', 'zh-Hant': '從 GitHub 安裝技能' }),
      description: t({
        en: 'Install skills from GitHub repositories using npx skills add command format',
        'zh-Hans': '使用 npx skills add 命令格式从 GitHub 仓库安装技能',
        fr: 'Installez des skills depuis GitHub avec la commande npx skills add',
        ja: 'npx skills add 形式で GitHub リポジトリからスキルをインストール',
        ko: 'npx skills add 명령 형식으로 GitHub 저장소에서 스킬 설치',
        'zh-Hant': '使用 npx skills add 命令格式從 GitHub 倉庫安裝技能',
      }),
      commandLabel: t({ en: 'Install Command', 'zh-Hans': '安装命令', fr: 'Commande d\'installation', ja: 'インストールコマンド', ko: '설치 명령', 'zh-Hant': '安裝命令' }),
      commandPlaceholder: t({ en: 'npx skills add owner/repo --skill skill-name', 'zh-Hans': 'npx skills add owner/repo --skill skill-name', fr: 'npx skills add owner/repo --skill skill-name', ja: 'npx skills add owner/repo --skill skill-name', ko: 'npx skills add owner/repo --skill skill-name', 'zh-Hant': 'npx skills add owner/repo --skill skill-name' }),
      formatHelp: t({ en: 'Supported formats:', 'zh-Hans': '支持的格式：', fr: 'Formats supportés :', ja: '対応形式：', ko: '지원 형식:', 'zh-Hant': '支援的格式：' }),
      parseSuccess: t({ en: 'Parse Successful', 'zh-Hans': '解析成功', fr: 'Analyse réussie', ja: '解析成功', ko: '파싱 성공', 'zh-Hant': '解析成功' }),
      repoLabel: t({ en: 'Repository:', 'zh-Hans': '仓库：', fr: 'Dépôt :', ja: 'リポジトリ：', ko: '저장소:', 'zh-Hant': '倉庫：' }),
      skillNameLabel: t({ en: 'Skill Name:', 'zh-Hans': '技能名称：', fr: 'Nom du Skill :', ja: 'スキル名：', ko: '스킬 이름:', 'zh-Hant': '技能名稱：' }),
      parseError: t({
        en: 'Invalid command format. Use: npx skills add <repo-url> --skill <skill-name>',
        'zh-Hans': '命令格式无效。请使用：npx skills add <仓库地址> --skill <技能名称>',
        fr: 'Format invalide. Utilisez : npx skills add <repo> --skill <nom>',
        ja: '無効な形式。npx skills add <リポジトリ> --skill <スキル名> を使用',
        ko: '잘못된 형식. npx skills add <저장소> --skill <스킬명> 사용',
        'zh-Hant': '命令格式無效。請使用：npx skills add <倉庫位址> --skill <技能名稱>',
      }),
      installSuccess: t({ en: 'Installation Successful', 'zh-Hans': '安装成功', fr: 'Installation réussie', ja: 'インストール成功', ko: '설치 성공', 'zh-Hant': '安裝成功' }),
      installedMessage: t({
        en: 'Skill <strong>{name}</strong> has been added to the skill store',
        'zh-Hans': '技能 <strong>{name}</strong> 已添加到技能库',
        fr: 'Le skill <strong>{name}</strong> a été ajouté au store',
        ja: 'スキル <strong>{name}</strong> をスキルストアに追加しました',
        ko: '스킬 <strong>{name}</strong>이(가) 스킬 스토어에 추가됨',
        'zh-Hant': '技能 <strong>{name}</strong> 已加入技能庫',
      }),
      installFailed: t({ en: 'Installation Failed', 'zh-Hans': '安装失败', fr: 'Échec de l\'installation', ja: 'インストールに失敗しました', ko: '설치 실패', 'zh-Hant': '安裝失敗' }),
      invalidCommand: t({ en: 'Please enter a valid install command', 'zh-Hans': '请输入有效的安装命令', fr: 'Veuillez entrer une commande valide', ja: '有効なインストールコマンドを入力してください', ko: '유효한 설치 명령을 입력하세요', 'zh-Hant': '請輸入有效的安裝命令' }),
      recheck: t({ en: 'Recheck', 'zh-Hans': '重新检查', fr: 'Revérifier', ja: '再確認', ko: '다시 확인', 'zh-Hant': '重新檢查' }),
      cancel: t({ en: 'Cancel', 'zh-Hans': '取消', fr: 'Annuler', ja: 'キャンセル', ko: '취소', 'zh-Hant': '取消' }),
      checking: t({ en: 'Checking...', 'zh-Hans': '检查中...', fr: 'Vérification...', ja: '確認中...', ko: '확인 중...', 'zh-Hant': '檢查中...' }),
      installing: t({ en: 'Installing...', 'zh-Hans': '安装中...', fr: 'Installation...', ja: 'インストール中...', ko: '설치 중...', 'zh-Hant': '安裝中...' }),
      complete: t({ en: 'Complete', 'zh-Hans': '完成', fr: 'Terminé', ja: '完了', ko: '완료', 'zh-Hant': '完成' }),
      installAnyway: t({ en: 'Install Anyway', 'zh-Hans': '仍然安装', fr: 'Quand même installer', ja: 'それでもインストール', ko: '그래도 설치', 'zh-Hant': '仍然安裝' }),
      install: t({ en: 'Install', 'zh-Hans': '安装', fr: 'Installer', ja: 'インストール', ko: '설치', 'zh-Hant': '安裝' }),
      compatCheckFailed: t({ en: 'Compatibility check failed', 'zh-Hans': '兼容性检查失败', fr: 'Échec de la vérification de compatibilité', ja: '互換性チェックに失敗しました', ko: '호환성 확인 실패', 'zh-Hant': '相容性檢查失敗' }),
    },

    // Skill detail dialog
    detail: {
      filesLabel: t({ en: 'Files', 'zh-Hans': '文件', fr: 'Fichiers', ja: 'ファイル', ko: '파일', 'zh-Hant': '檔案' }),
      selectFile: t({ en: 'Select a file to view its content', 'zh-Hans': '选择文件查看内容', fr: 'Sélectionnez un fichier pour voir son contenu', ja: 'ファイルを選択して内容を表示', ko: '파일을 선택해 내용 보기', 'zh-Hant': '選擇檔案以檢視內容' }),
      noContent: t({ en: 'No content available', 'zh-Hans': '暂无内容', fr: 'Aucun contenu', ja: 'コンテンツがありません', ko: '내용 없음', 'zh-Hant': '無可用內容' }),
      binaryFile: t({ en: 'Binary file - preview not available', 'zh-Hans': '二进制文件 - 无法预览', fr: 'Fichier binaire - pas d\'aperçu', ja: 'バイナリファイル - プレビュー不可', ko: '바이너리 파일 - 미리보기 불가', 'zh-Hant': '二進位檔案 - 無法預覽' }),
      tooLarge: t({ en: 'File too large for preview (>1MB)', 'zh-Hans': '文件过大，无法预览 (>1MB)', fr: 'Fichier trop volumineux (>1 Mo)', ja: 'プレビューには大きすぎます（>1MB）', ko: '미리보기에는 너무 큼 (>1MB)', 'zh-Hant': '檔案過大無法預覽（>1MB）' }),
      directoryNoContent: t({ en: 'Directories have no content preview', 'zh-Hans': '目录无法预览', fr: 'Les répertoires n\'ont pas d\'aperçu', ja: 'ディレクトリにはプレビューがありません', ko: '디렉터리는 미리보기 없음', 'zh-Hant': '目錄無內容預覽' }),
      copy: t({ en: 'Copy', 'zh-Hans': '复制', fr: 'Copier', ja: 'コピー', ko: '복사', 'zh-Hant': '複製' }),
      copied: t({ en: 'Copied', 'zh-Hans': '已复制', fr: 'Copié', ja: 'コピー済み', ko: '복사됨', 'zh-Hant': '已複製' }),
      install: t({ en: 'Install', 'zh-Hans': '安装', fr: 'Installer', ja: 'インストール', ko: '설치', 'zh-Hant': '安裝' }),
      uninstall: t({ en: 'Uninstall', 'zh-Hans': '卸载', fr: 'Désinstaller', ja: 'アンインストール', ko: '제거', 'zh-Hant': '解除安裝' }),
    },

    // Schema manage dialog
    schema: {
      title: t({ en: 'Schema Management', 'zh-Hans': 'Schema 管理', fr: 'Gestion du Schema', ja: 'Schema 管理', ko: 'Schema 관리', 'zh-Hant': 'Schema 管理' }),
      description: t({ en: 'Manage JSON Schema for <code>{name}</code>', 'zh-Hans': '管理 <code>{name}</code> 的 JSON Schema', fr: 'Gérer le JSON Schema pour <code>{name}</code>', ja: '<code>{name}</code> の JSON Schema を管理', ko: '<code>{name}</code>의 JSON Schema 관리', 'zh-Hant': '管理 <code>{name}</code> 的 JSON Schema' }),
      loading: t({ en: 'Loading...', 'zh-Hans': '加载中...', fr: 'Chargement...', ja: '読み込み中...', ko: '로딩 중...', 'zh-Hant': '載入中...' }),
      statusLabel: t({ en: 'Status:', 'zh-Hans': '状态：', fr: 'Statut :', ja: '状態：', ko: '상태:', 'zh-Hant': '狀態：' }),
      needsReview: t({ en: 'Needs Manual Review', 'zh-Hans': '需人工校验', fr: 'Révision manuelle requise', ja: '手動確認が必要', ko: '수동 검토 필요', 'zh-Hant': '需人工校驗' }),
      metadata: t({ en: 'Metadata', 'zh-Hans': '元数据', fr: 'Métadonnées', ja: 'メタデータ', ko: '메타데이터', 'zh-Hant': '元資料' }),
      generatedAt: t({ en: 'Generated:', 'zh-Hans': '生成时间：', fr: 'Généré :', ja: '生成：', ko: '생성:', 'zh-Hant': '產生時間：' }),
      lastAttempt: t({ en: 'Last Attempt:', 'zh-Hans': '上次尝试：', fr: 'Dernière tentative :', ja: '前回の試行：', ko: '마지막 시도:', 'zh-Hant': '上次嘗試：' }),
      generatedBy: t({ en: 'Generated By:', 'zh-Hans': '生成者：', fr: 'Généré par :', ja: '生成者：', ko: '생성자:', 'zh-Hant': '產生者：' }),
      model: t({ en: 'Model:', 'zh-Hans': '模型：', fr: 'Modèle :', ja: 'モデル：', ko: '모델:', 'zh-Hant': '模型：' }),
      skillMdHash: t({ en: 'SKILL.md Hash:', 'zh-Hans': 'SKILL.md Hash:', fr: 'SKILL.md Hash :', ja: 'SKILL.md Hash:', ko: 'SKILL.md Hash:', 'zh-Hant': 'SKILL.md Hash:' }),
      lastError: t({ en: 'Last Error:', 'zh-Hans': '上次错误:', fr: 'Dernière erreur :', ja: '前回のエラー:', ko: '마지막 오류:', 'zh-Hant': '上次錯誤:' }),
      reviewWarning: t({
        en: 'This schema was generated in fallback mode. Please verify manually before using.',
        'zh-Hans': '该 Schema 由容错模式生成，请人工核对后再使用。',
        fr: 'Ce schema a été généré en mode secours. Vérifiez manuellement avant utilisation.',
        ja: 'この Schema はフォールバックモードで生成されました。使用前に手動で確認してください。',
        ko: '이 Schema는 폴백 모드로 생성되었습니다. 사용 전 수동 확인하세요.',
        'zh-Hant': '該 Schema 由容錯模式產生，請人工核對後再使用。',
      }),
      formPreview: t({ en: 'Form Preview', 'zh-Hans': '表单预览', fr: 'Aperçu du formulaire', ja: 'フォームプレビュー', ko: '폼 미리보기', 'zh-Hant': '表單預覽' }),
      jsonPreview: t({ en: 'JSON Preview', 'zh-Hans': 'JSON 预览', fr: 'Aperçu JSON', ja: 'JSON プレビュー', ko: 'JSON 미리보기', 'zh-Hant': 'JSON 預覽' }),
      fieldCount: t({ en: 'Fields: {count} ({required} required)', 'zh-Hans': '字段数: {count}（必填 {required}）', fr: 'Champs : {count} ({required} requis)', ja: 'フィールド：{count}（必須 {required}）', ko: '필드: {count}(필수 {required})', 'zh-Hant': '欄位數：{count}（必填 {required}）' }),
      noFields: t({ en: 'No input fields', 'zh-Hans': '暂无输入字段', fr: 'Aucun champ de saisie', ja: '入力フィールドがありません', ko: '입력 필드 없음', 'zh-Hant': '暫無輸入欄位' }),
      noFieldsPreview: t({ en: 'No input fields to preview', 'zh-Hans': '暂无可预览的输入字段', fr: 'Aucun champ à prévisualiser', ja: 'プレビューする入力フィールドがありません', ko: '미리보기할 입력 필드 없음', 'zh-Hant': '暫無可預覽的輸入欄位' }),
      required: t({ en: 'Required', 'zh-Hans': '必填', fr: 'Requis', ja: '必須', ko: '필수', 'zh-Hant': '必填' }),
      placeholderLabel: t({ en: 'Placeholder:', 'zh-Hans': '占位提示：', fr: 'Placeholder :', ja: 'プレースホルダー：', ko: '플레이스홀더:', 'zh-Hant': '佔位提示：' }),
      selectPlaceholder: t({ en: 'Please select', 'zh-Hans': '请选择', fr: 'Veuillez sélectionner', ja: '選択してください', ko: '선택하세요', 'zh-Hant': '請選擇' }),
      noOptions: t({ en: 'No options available', 'zh-Hans': '无可选项', fr: 'Aucune option', ja: 'オプションがありません', ko: '선택 옵션 없음', 'zh-Hant': '無可選項' }),
      booleanLabel: t({ en: 'Yes / No', 'zh-Hans': '是 / 否', fr: 'Oui / Non', ja: 'はい / いいえ', ko: '예 / 아니오', 'zh-Hant': '是 / 否' }),
      optionLabel: t({ en: 'Option', 'zh-Hans': '选项', fr: 'Option', ja: 'オプション', ko: '옵션', 'zh-Hant': '選項' }),
      closeButton: t({ en: 'Close', 'zh-Hans': '关闭', fr: 'Fermer', ja: '閉じる', ko: '닫기', 'zh-Hant': '關閉' }),
      saveButton: t({ en: 'Save Changes', 'zh-Hans': '保存修改', fr: 'Enregistrer', ja: '変更を保存', ko: '변경 저장', 'zh-Hant': '儲存變更' }),
      saving: t({ en: 'Saving...', 'zh-Hans': '保存中...', fr: 'Enregistrement...', ja: '保存中...', ko: '저장 중...', 'zh-Hant': '儲存中...' }),
      generateButton: t({ en: 'Generate Schema', 'zh-Hans': '生成 Schema', fr: 'Générer le Schema', ja: 'Schema を生成', ko: 'Schema 생성', 'zh-Hant': '產生 Schema' }),
      regenerateButton: t({ en: 'Regenerate', 'zh-Hans': '重新生成', fr: 'Régénérer', ja: '再生成', ko: '다시 생성', 'zh-Hant': '重新產生' }),
      generating: t({ en: 'Generating...', 'zh-Hans': '生成中...', fr: 'Génération...', ja: '生成中...', ko: '생성 중...', 'zh-Hant': '產生中...' }),
      costWarning: t({
        en: 'Note: Generating/regenerating Schema will call AI API and incur costs. Only operate when necessary.',
        'zh-Hans': '注意：生成/重新生成 Schema 会调用 AI API，会产生费用。建议仅在必要时操作。',
        fr: 'Générer/régénérer le Schema appelle l\'API IA et engendre des coûts. À faire uniquement si nécessaire.',
        ja: 'Schema の生成/再生成は AI API を呼び出し費用がかかります。必要な時のみ操作してください。',
        ko: 'Schema 생성/재생성은 AI API를 호출해 비용이 발생합니다. 필요할 때만 진행하세요.',
        'zh-Hant': '注意：產生/重新產生 Schema 會呼叫 AI API並產生費用。建議僅在必要時操作。',
      }),
      statusDescriptions: {
        missing: t({ en: 'Schema not generated', 'zh-Hans': 'Schema 未生成', fr: 'Schema non généré', ja: 'Schema 未生成', ko: 'Schema 미생성', 'zh-Hant': 'Schema 未產生' }),
        valid: t({ en: 'Schema is valid and up to date', 'zh-Hans': 'Schema 有效且最新', fr: 'Schema valide et à jour', ja: 'Schema は有効で最新です', ko: 'Schema 유효하고 최신', 'zh-Hant': 'Schema 有效且最新' }),
        invalid: t({ en: 'Schema exists but failed to parse', 'zh-Hans': 'Schema 存在但解析失败', fr: 'Schema existant mais échec du parsing', ja: 'Schema は存在するが解析に失敗', ko: 'Schema 존재하나 파싱 실패', 'zh-Hant': 'Schema 存在但解析失敗' }),
        stale: t({ en: 'Schema is stale, SKILL.md has been updated', 'zh-Hans': 'Schema 过期，SKILL.md 已更新', fr: 'Schema obsolète, SKILL.md mis à jour', ja: 'Schema は古い、SKILL.md が更新されました', ko: 'Schema 만료, SKILL.md 업데이트됨', 'zh-Hant': 'Schema 過期，SKILL.md 已更新' }),
        failed: t({ en: 'Last generation failed', 'zh-Hans': '上次生成失败', fr: 'Dernière génération échouée', ja: '前回の生成に失敗', ko: '마지막 생성 실패', 'zh-Hant': '上次產生失敗' }),
        generating: t({ en: 'Generating Schema...', 'zh-Hans': '正在生成 Schema...', fr: 'Génération du Schema...', ja: 'Schema を生成中...', ko: 'Schema 생성 중...', 'zh-Hant': '正在產生 Schema...' }),
        unknown: t({ en: 'Schema status unknown', 'zh-Hans': 'Schema 状态未知', fr: 'Statut du Schema inconnu', ja: 'Schema の状態が不明', ko: 'Schema 상태 알 수 없음', 'zh-Hant': 'Schema 狀態未知' }),
      },
      unknown: t({ en: 'Unknown', 'zh-Hans': '未知', fr: 'Inconnu', ja: '不明', ko: '알 수 없음', 'zh-Hant': '未知' }),
    },
  },
  key: 'skills',
} satisfies Dictionary;

export default skillsContent;
